package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("disability_history_info")
public class DisabilityHistoryInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disability_history_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disability_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disability_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disability_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disability_history_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disability_history_info.disability
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String disability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disability_history_info.disability_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date disabilityTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disability_history_info.disability_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String disabilityCode;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disability_history_info.pk
     *
     * @param pk the value for disability_history_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disability_history_info.domain_id
     *
     * @return the value of disability_history_info.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disability_history_info.domain_id
     *
     * @param domainId the value for disability_history_info.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disability_history_info.unique_id
     *
     * @return the value of disability_history_info.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disability_history_info.unique_id
     *
     * @param uniqueId the value for disability_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disability_history_info.xds_type
     *
     * @return the value of disability_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disability_history_info.xds_type
     *
     * @param xdsType the value for disability_history_info.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disability_history_info.xds_version
     *
     * @return the value of disability_history_info.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disability_history_info.xds_version
     *
     * @param xdsVersion the value for disability_history_info.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disability_history_info.disability
     *
     * @return the value of disability_history_info.disability
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDisability() {
        return disability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disability_history_info.disability
     *
     * @param disability the value for disability_history_info.disability
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDisability(String disability) {
        this.disability = disability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disability_history_info.disability_time
     *
     * @return the value of disability_history_info.disability_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getDisabilityTime() {
        return disabilityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disability_history_info.disability_time
     *
     * @param disabilityTime the value for disability_history_info.disability_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDisabilityTime(Date disabilityTime) {
        this.disabilityTime = disabilityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disability_history_info.disability_code
     *
     * @return the value of disability_history_info.disability_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDisabilityCode() {
        return disabilityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disability_history_info.disability_code
     *
     * @param disabilityCode the value for disability_history_info.disability_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDisabilityCode(String disabilityCode) {
        this.disabilityCode = disabilityCode;
    }
}