package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("disease_history_info")
public class DiseaseHistoryInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_history_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_history_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_history_info.diag_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date diagDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_history_info.sick_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sickType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_history_info.sick_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sickTypeCode;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_history_info.pk
     *
     * @param pk the value for disease_history_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_history_info.domain_id
     *
     * @return the value of disease_history_info.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_history_info.domain_id
     *
     * @param domainId the value for disease_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_history_info.unique_id
     *
     * @return the value of disease_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_history_info.unique_id
     *
     * @param uniqueId the value for disease_history_info.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_history_info.xds_type
     *
     * @return the value of disease_history_info.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_history_info.xds_type
     *
     * @param xdsType the value for disease_history_info.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_history_info.xds_version
     *
     * @return the value of disease_history_info.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_history_info.xds_version
     *
     * @param xdsVersion the value for disease_history_info.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_history_info.diag_date
     *
     * @return the value of disease_history_info.diag_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getDiagDate() {
        return diagDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_history_info.diag_date
     *
     * @param diagDate the value for disease_history_info.diag_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDiagDate(Date diagDate) {
        this.diagDate = diagDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_history_info.sick_type
     *
     * @return the value of disease_history_info.sick_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSickType() {
        return sickType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_history_info.sick_type
     *
     * @param sickType the value for disease_history_info.sick_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSickType(String sickType) {
        this.sickType = sickType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_history_info.sick_type_code
     *
     * @return the value of disease_history_info.sick_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSickTypeCode() {
        return sickTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_history_info.sick_type_code
     *
     * @param sickTypeCode the value for disease_history_info.sick_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSickTypeCode(String sickTypeCode) {
        this.sickTypeCode = sickTypeCode;
    }
}