package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("guardian_info")
public class GuardianInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.relation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String relationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.relation_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String relationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String telecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.occupation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.occupation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String occupationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String township;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String houseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guardian_info.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String streetName;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.pk
     *
     * @param pk the value for guardian_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.domain_id
     *
     * @return the value of guardian_info.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.domain_id
     *
     * @param domainId the value for guardian_info.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.unique_id
     *
     * @return the value of guardian_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.unique_id
     *
     * @param uniqueId the value for guardian_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.xds_type
     *
     * @return the value of guardian_info.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.xds_type
     *
     * @param xdsType the value for guardian_info.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.xds_version
     *
     * @return the value of guardian_info.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.xds_version
     *
     * @param xdsVersion the value for guardian_info.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.relation_code
     *
     * @return the value of guardian_info.relation_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRelationCode() {
        return relationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.relation_code
     *
     * @param relationCode the value for guardian_info.relation_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRelationCode(String relationCode) {
        this.relationCode = relationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.relation_name
     *
     * @return the value of guardian_info.relation_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRelationName() {
        return relationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.relation_name
     *
     * @param relationName the value for guardian_info.relation_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRelationName(String relationName) {
        this.relationName = relationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.birth
     *
     * @return the value of guardian_info.birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.birth
     *
     * @param birth the value for guardian_info.birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.telecom
     *
     * @return the value of guardian_info.telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTelecom() {
        return telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.telecom
     *
     * @param telecom the value for guardian_info.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTelecom(String telecom) {
        this.telecom = telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.name
     *
     * @return the value of guardian_info.name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.name
     *
     * @param name the value for guardian_info.name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.occupation
     *
     * @return the value of guardian_info.occupation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.occupation
     *
     * @param occupation the value for guardian_info.occupation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.occupation_code
     *
     * @return the value of guardian_info.occupation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOccupationCode() {
        return occupationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.occupation_code
     *
     * @param occupationCode the value for guardian_info.occupation_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOccupationCode(String occupationCode) {
        this.occupationCode = occupationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.province
     *
     * @return the value of guardian_info.province
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.province
     *
     * @param province the value for guardian_info.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.city
     *
     * @return the value of guardian_info.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.city
     *
     * @param city the value for guardian_info.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.county
     *
     * @return the value of guardian_info.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.county
     *
     * @param county the value for guardian_info.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.township
     *
     * @return the value of guardian_info.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTownship() {
        return township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.township
     *
     * @param township the value for guardian_info.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTownship(String township) {
        this.township = township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.house_number
     *
     * @return the value of guardian_info.house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.house_number
     *
     * @param houseNumber the value for guardian_info.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guardian_info.street_name
     *
     * @return the value of guardian_info.street_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guardian_info.street_name
     *
     * @param streetName the value for guardian_info.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
}