package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;

@Data
@TableName("health_guide")
public class HealthGuide extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_guide.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_guide.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_guide.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_guide.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_guide.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_guide.health_guide
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthGuide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column health_guide.health_guide_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthGuideCode;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_guide.pk
     *
     * @param pk the value for health_guide.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_guide.domain_id
     *
     * @return the value of health_guide.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_guide.domain_id
     *
     * @param domainId the value for health_guide.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_guide.unique_id
     *
     * @return the value of health_guide.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_guide.unique_id
     *
     * @param uniqueId the value for health_guide.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_guide.xds_type
     *
     * @return the value of health_guide.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_guide.xds_type
     *
     * @param xdsType the value for health_guide.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_guide.xds_version
     *
     * @return the value of health_guide.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_guide.xds_version
     *
     * @param xdsVersion the value for health_guide.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_guide.health_guide
     *
     * @return the value of health_guide.health_guide
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthGuide() {
        return healthGuide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_guide.health_guide
     *
     * @param healthGuide the value for health_guide.health_guide
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthGuide(String healthGuide) {
        this.healthGuide = healthGuide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column health_guide.health_guide_code
     *
     * @return the value of health_guide.health_guide_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthGuideCode() {
        return healthGuideCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column health_guide.health_guide_code
     *
     * @param healthGuideCode the value for health_guide.health_guide_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthGuideCode(String healthGuideCode) {
        this.healthGuideCode = healthGuideCode;
    }
}