package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("home_bed_info")
public class HomeBedInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_bed_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_bed_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_bed_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_bed_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_bed_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_bed_info.build_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String buildReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_bed_info.bulid_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date bulidDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_bed_info.fmedical_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fmedicalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_bed_info.fmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fmiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_bed_info.fmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fmiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_bed_info.removal_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date removalDate;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_bed_info.pk
     *
     * @param pk the value for home_bed_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_bed_info.domain_id
     *
     * @return the value of home_bed_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_bed_info.domain_id
     *
     * @param domainId the value for home_bed_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_bed_info.unique_id
     *
     * @return the value of home_bed_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_bed_info.unique_id
     *
     * @param uniqueId the value for home_bed_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_bed_info.xds_type
     *
     * @return the value of home_bed_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_bed_info.xds_type
     *
     * @param xdsType the value for home_bed_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_bed_info.xds_version
     *
     * @return the value of home_bed_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_bed_info.xds_version
     *
     * @param xdsVersion the value for home_bed_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_bed_info.build_reason
     *
     * @return the value of home_bed_info.build_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getBuildReason() {
        return buildReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_bed_info.build_reason
     *
     * @param buildReason the value for home_bed_info.build_reason
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBuildReason(String buildReason) {
        this.buildReason = buildReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_bed_info.bulid_date
     *
     * @return the value of home_bed_info.bulid_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getBulidDate() {
        return bulidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_bed_info.bulid_date
     *
     * @param bulidDate the value for home_bed_info.bulid_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBulidDate(Date bulidDate) {
        this.bulidDate = bulidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_bed_info.fmedical_no
     *
     * @return the value of home_bed_info.fmedical_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFmedicalNo() {
        return fmedicalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_bed_info.fmedical_no
     *
     * @param fmedicalNo the value for home_bed_info.fmedical_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFmedicalNo(String fmedicalNo) {
        this.fmedicalNo = fmedicalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_bed_info.fmi_code
     *
     * @return the value of home_bed_info.fmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFmiCode() {
        return fmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_bed_info.fmi_code
     *
     * @param fmiCode the value for home_bed_info.fmi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFmiCode(String fmiCode) {
        this.fmiCode = fmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_bed_info.fmi_name
     *
     * @return the value of home_bed_info.fmi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFmiName() {
        return fmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_bed_info.fmi_name
     *
     * @param fmiName the value for home_bed_info.fmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFmiName(String fmiName) {
        this.fmiName = fmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_bed_info.removal_date
     *
     * @return the value of home_bed_info.removal_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getRemovalDate() {
        return removalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_bed_info.removal_date
     *
     * @param removalDate the value for home_bed_info.removal_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRemovalDate(Date removalDate) {
        this.removalDate = removalDate;
    }
}