package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("HSDA00_01")
public class Hsda0001 extends BaseBean implements Serializable {
    private static final long serialVersionUID = 7283715044223197838L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.poultry_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String poultryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.category_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.marital_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String maritalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.occupation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String occupationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.rh_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String rhCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.exhaust_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean exhaustMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.wc_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String wcTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.abo_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String aboCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.edu_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String eduCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.drinking_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String drinkingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String streetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.hereditary
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String hereditary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.workplace
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String workplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.pay_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.identify_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String identifyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.fuel_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fuelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.poultry_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String poultryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.ethnic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ethnic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.occupation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.rh
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String rh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ostalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.exhaust_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String exhaustCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.wc_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String wcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String categoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String maritalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.edu_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String eduName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.abo
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String abo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.drinking_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String drinkingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String township;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.addr_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean addrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.fuel_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fuelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String houseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.ethnic_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ethnicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.pay_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String payCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String telecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDA00_01.exhaust_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String exhaustName;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.pk
     *
     * @param pk the value for HSDA00_01.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.domain_id
     *
     * @return the value of HSDA00_01.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.domain_id
     *
     * @param domainId the value for HSDA00_01.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.unique_id
     *
     * @return the value of HSDA00_01.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.unique_id
     *
     * @param uniqueId the value for HSDA00_01.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.xds_type
     *
     * @return the value of HSDA00_01.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.xds_type
     *
     * @param xdsType the value for HSDA00_01.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.xds_version
     *
     * @return the value of HSDA00_01.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.xds_version
     *
     * @param xdsVersion the value for HSDA00_01.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.poultry_code
     *
     * @return the value of HSDA00_01.poultry_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPoultryCode() {
        return poultryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.poultry_code
     *
     * @param poultryCode the value for HSDA00_01.poultry_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPoultryCode(String poultryCode) {
        this.poultryCode = poultryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.custodian_name
     *
     * @return the value of HSDA00_01.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.custodian_name
     *
     * @param custodianName the value for HSDA00_01.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.category_name
     *
     * @return the value of HSDA00_01.category_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.category_name
     *
     * @param categoryName the value for HSDA00_01.category_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.encounter_id
     *
     * @return the value of HSDA00_01.encounter_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.encounter_id
     *
     * @param encounterId the value for HSDA00_01.encounter_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.marital_code
     *
     * @return the value of HSDA00_01.marital_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMaritalCode() {
        return maritalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.marital_code
     *
     * @param maritalCode the value for HSDA00_01.marital_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMaritalCode(String maritalCode) {
        this.maritalCode = maritalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.occupation_code
     *
     * @return the value of HSDA00_01.occupation_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOccupationCode() {
        return occupationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.occupation_code
     *
     * @param occupationCode the value for HSDA00_01.occupation_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOccupationCode(String occupationCode) {
        this.occupationCode = occupationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.rh_code
     *
     * @return the value of HSDA00_01.rh_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRhCode() {
        return rhCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.rh_code
     *
     * @param rhCode the value for HSDA00_01.rh_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRhCode(String rhCode) {
        this.rhCode = rhCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.province
     *
     * @return the value of HSDA00_01.province
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.province
     *
     * @param province the value for HSDA00_01.province
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.exhaust_mark
     *
     * @return the value of HSDA00_01.exhaust_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getExhaustMark() {
        return exhaustMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.exhaust_mark
     *
     * @param exhaustMark the value for HSDA00_01.exhaust_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setExhaustMark(Boolean exhaustMark) {
        this.exhaustMark = exhaustMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.mi_addr
     *
     * @return the value of HSDA00_01.mi_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.mi_addr
     *
     * @param miAddr the value for HSDA00_01.mi_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.class_name
     *
     * @return the value of HSDA00_01.class_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.class_name
     *
     * @param className the value for HSDA00_01.class_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.status
     *
     * @return the value of HSDA00_01.status
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.status
     *
     * @param status the value for HSDA00_01.status
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.birth
     *
     * @return the value of HSDA00_01.birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.birth
     *
     * @param birth the value for HSDA00_01.birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.wc_type_code
     *
     * @return the value of HSDA00_01.wc_type_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWcTypeCode() {
        return wcTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.wc_type_code
     *
     * @param wcTypeCode the value for HSDA00_01.wc_type_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWcTypeCode(String wcTypeCode) {
        this.wcTypeCode = wcTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.abo_code
     *
     * @return the value of HSDA00_01.abo_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAboCode() {
        return aboCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.abo_code
     *
     * @param aboCode the value for HSDA00_01.abo_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAboCode(String aboCode) {
        this.aboCode = aboCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.county
     *
     * @return the value of HSDA00_01.county
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.county
     *
     * @param county the value for HSDA00_01.county
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.edu_code
     *
     * @return the value of HSDA00_01.edu_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEduCode() {
        return eduCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.edu_code
     *
     * @param eduCode the value for HSDA00_01.edu_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEduCode(String eduCode) {
        this.eduCode = eduCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.mi_code
     *
     * @return the value of HSDA00_01.mi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.mi_code
     *
     * @param miCode the value for HSDA00_01.mi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.xds_name
     *
     * @return the value of HSDA00_01.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.xds_name
     *
     * @param xdsName the value for HSDA00_01.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.sex_code
     *
     * @return the value of HSDA00_01.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.sex_code
     *
     * @param sexCode the value for HSDA00_01.sex_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.drinking_code
     *
     * @return the value of HSDA00_01.drinking_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDrinkingCode() {
        return drinkingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.drinking_code
     *
     * @param drinkingCode the value for HSDA00_01.drinking_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDrinkingCode(String drinkingCode) {
        this.drinkingCode = drinkingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.street_name
     *
     * @return the value of HSDA00_01.street_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.street_name
     *
     * @param streetName the value for HSDA00_01.street_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.hereditary
     *
     * @return the value of HSDA00_01.hereditary
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHereditary() {
        return hereditary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.hereditary
     *
     * @param hereditary the value for HSDA00_01.hereditary
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHereditary(String hereditary) {
        this.hereditary = hereditary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.workplace
     *
     * @return the value of HSDA00_01.workplace
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWorkplace() {
        return workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.workplace
     *
     * @param workplace the value for HSDA00_01.workplace
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWorkplace(String workplace) {
        this.workplace = workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.author_code
     *
     * @return the value of HSDA00_01.author_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.author_code
     *
     * @param authorCode the value for HSDA00_01.author_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.pay_name
     *
     * @return the value of HSDA00_01.pay_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.pay_name
     *
     * @param payName the value for HSDA00_01.pay_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPayName(String payName) {
        this.payName = payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.identify_no
     *
     * @return the value of HSDA00_01.identify_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIdentifyNo() {
        return identifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.identify_no
     *
     * @param identifyNo the value for HSDA00_01.identify_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIdentifyNo(String identifyNo) {
        this.identifyNo = identifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.fuel_code
     *
     * @return the value of HSDA00_01.fuel_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFuelCode() {
        return fuelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.fuel_code
     *
     * @param fuelCode the value for HSDA00_01.fuel_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuelCode(String fuelCode) {
        this.fuelCode = fuelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.poultry_type
     *
     * @return the value of HSDA00_01.poultry_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPoultryType() {
        return poultryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.poultry_type
     *
     * @param poultryType the value for HSDA00_01.poultry_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPoultryType(String poultryType) {
        this.poultryType = poultryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.custodian_telecom
     *
     * @return the value of HSDA00_01.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.custodian_telecom
     *
     * @param custodianTelecom the value for HSDA00_01.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.health_no
     *
     * @return the value of HSDA00_01.health_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthNo() {
        return healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.health_no
     *
     * @param healthNo the value for HSDA00_01.health_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthNo(String healthNo) {
        this.healthNo = healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.ethnic
     *
     * @return the value of HSDA00_01.ethnic
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEthnic() {
        return ethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.ethnic
     *
     * @param ethnic the value for HSDA00_01.ethnic
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEthnic(String ethnic) {
        this.ethnic = ethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.occupation
     *
     * @return the value of HSDA00_01.occupation
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.occupation
     *
     * @param occupation the value for HSDA00_01.occupation
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.rh
     *
     * @return the value of HSDA00_01.rh
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRh() {
        return rh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.rh
     *
     * @param rh the value for HSDA00_01.rh
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRh(String rh) {
        this.rh = rh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.register_model
     *
     * @return the value of HSDA00_01.register_model
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.register_model
     *
     * @param registerModel the value for HSDA00_01.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.ostal_code
     *
     * @return the value of HSDA00_01.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOstalCode() {
        return ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.ostal_code
     *
     * @param ostalCode the value for HSDA00_01.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOstalCode(String ostalCode) {
        this.ostalCode = ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.exhaust_code
     *
     * @return the value of HSDA00_01.exhaust_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getExhaustCode() {
        return exhaustCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.exhaust_code
     *
     * @param exhaustCode the value for HSDA00_01.exhaust_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setExhaustCode(String exhaustCode) {
        this.exhaustCode = exhaustCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.wc_type
     *
     * @return the value of HSDA00_01.wc_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWcType() {
        return wcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.wc_type
     *
     * @param wcType the value for HSDA00_01.wc_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWcType(String wcType) {
        this.wcType = wcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.custodian_code
     *
     * @return the value of HSDA00_01.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.custodian_code
     *
     * @param custodianCode the value for HSDA00_01.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.category_code
     *
     * @return the value of HSDA00_01.category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.category_code
     *
     * @param categoryCode the value for HSDA00_01.category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.class_code
     *
     * @return the value of HSDA00_01.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.class_code
     *
     * @param classCode the value for HSDA00_01.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.empi
     *
     * @return the value of HSDA00_01.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.empi
     *
     * @param empi the value for HSDA00_01.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.marital_name
     *
     * @return the value of HSDA00_01.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMaritalName() {
        return maritalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.marital_name
     *
     * @param maritalName the value for HSDA00_01.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMaritalName(String maritalName) {
        this.maritalName = maritalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.edu_name
     *
     * @return the value of HSDA00_01.edu_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEduName() {
        return eduName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.edu_name
     *
     * @param eduName the value for HSDA00_01.edu_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEduName(String eduName) {
        this.eduName = eduName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.abo
     *
     * @return the value of HSDA00_01.abo
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAbo() {
        return abo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.abo
     *
     * @param abo the value for HSDA00_01.abo
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAbo(String abo) {
        this.abo = abo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.city
     *
     * @return the value of HSDA00_01.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.city
     *
     * @param city the value for HSDA00_01.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.mi_name
     *
     * @return the value of HSDA00_01.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.mi_name
     *
     * @param miName the value for HSDA00_01.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.effective_time
     *
     * @return the value of HSDA00_01.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.effective_time
     *
     * @param effectiveTime the value for HSDA00_01.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.upload_time
     *
     * @return the value of HSDA00_01.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.upload_time
     *
     * @param uploadTime the value for HSDA00_01.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.sex
     *
     * @return the value of HSDA00_01.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.sex
     *
     * @param sex the value for HSDA00_01.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.drinking_name
     *
     * @return the value of HSDA00_01.drinking_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDrinkingName() {
        return drinkingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.drinking_name
     *
     * @param drinkingName the value for HSDA00_01.drinking_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDrinkingName(String drinkingName) {
        this.drinkingName = drinkingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.township
     *
     * @return the value of HSDA00_01.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTownship() {
        return township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.township
     *
     * @param township the value for HSDA00_01.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTownship(String township) {
        this.township = township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.addr_code
     *
     * @return the value of HSDA00_01.addr_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getAddrCode() {
        return addrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.addr_code
     *
     * @param addrCode the value for HSDA00_01.addr_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAddrCode(Boolean addrCode) {
        this.addrCode = addrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.author_name
     *
     * @return the value of HSDA00_01.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.author_name
     *
     * @param authorName the value for HSDA00_01.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.patient_name
     *
     * @return the value of HSDA00_01.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.patient_name
     *
     * @param patientName the value for HSDA00_01.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.fuel_type
     *
     * @return the value of HSDA00_01.fuel_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFuelType() {
        return fuelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.fuel_type
     *
     * @param fuelType the value for HSDA00_01.fuel_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuelType(String fuelType) {
        this.fuelType = fuelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.custodian_addr
     *
     * @return the value of HSDA00_01.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.custodian_addr
     *
     * @param custodianAddr the value for HSDA00_01.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.house_number
     *
     * @return the value of HSDA00_01.house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.house_number
     *
     * @param houseNumber the value for HSDA00_01.house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.ethnic_code
     *
     * @return the value of HSDA00_01.ethnic_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEthnicCode() {
        return ethnicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.ethnic_code
     *
     * @param ethnicCode the value for HSDA00_01.ethnic_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEthnicCode(String ethnicCode) {
        this.ethnicCode = ethnicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.write_time
     *
     * @return the value of HSDA00_01.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.write_time
     *
     * @param writeTime the value for HSDA00_01.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.pay_code
     *
     * @return the value of HSDA00_01.pay_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.pay_code
     *
     * @param payCode the value for HSDA00_01.pay_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.template_oid
     *
     * @return the value of HSDA00_01.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.template_oid
     *
     * @param templateOid the value for HSDA00_01.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.telecom
     *
     * @return the value of HSDA00_01.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTelecom() {
        return telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.telecom
     *
     * @param telecom the value for HSDA00_01.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTelecom(String telecom) {
        this.telecom = telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDA00_01.exhaust_name
     *
     * @return the value of HSDA00_01.exhaust_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getExhaustName() {
        return exhaustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDA00_01.exhaust_name
     *
     * @param exhaustName the value for HSDA00_01.exhaust_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setExhaustName(String exhaustName) {
        this.exhaustName = exhaustName;
    }
}