package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("HSDB01_03")
public class Hsdb0103 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.height_evaluation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String heightEvaluation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.front_tension
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String frontTension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.teething
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String teething;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.genitals_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String genitalsResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.rickets_symptom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ricketsSymptom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.right_chyperopia
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float rightChyperopia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.palpation_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String palpationDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.trauma_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String traumaTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.front_ld
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float frontLd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.fu_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date fuDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.os_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean osMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.spine_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String spineDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.complexion_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String complexionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.pass_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean passMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.right_ndiastolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float rightNdiastolic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.lungs_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String lungsDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.pneumonia_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String pneumoniaTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.asc_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean ascMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.listen_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String listenCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.extremities_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String extremitiesDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.develop_evaluate_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String developEvaluateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.mass_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String massDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.auscultation_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String auscultationResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.outdoor_duration
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float outdoorDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.height
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.gait_sign
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean gaitSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.ear_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean earMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.uc_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ucResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.weight_evaluation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String weightEvaluationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.head_dimension
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float headDimension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.dental_caries
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String dentalCaries;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.anus_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean anusMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.rickets_signs_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ricketsSignsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.referral_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean referralMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.eye_shape_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean eyeShapeMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.uc_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean ucMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.illness
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String illness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.height_evaluation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String heightEvaluationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.front_tension_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String frontTensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.os_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String osResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.genitals_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean genitalsMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.rickets_symptom_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ricketsSymptomCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.left_chyperopia
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float leftChyperopia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.abdomen_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean abdomenMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.diarrhea_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String diarrheaTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.front_td
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float frontTd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.listen_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String listenResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.spine_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean spineMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.complexion_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String complexionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.develop_evaluate
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String developEvaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.left_ndiastolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float leftNdiastolic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.lungs_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean lungsMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.sick_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean sickMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.skin_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean skinMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.ear_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String earResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.extremities_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean extremitiesMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.weight_evaluation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String weightEvaluation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.mass_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean massMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.auscultation_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean auscultationMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.anus_check
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String anusCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.length
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.rickets_signs
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ricketsSigns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String referralReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.eye_shape
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String eyeShape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.uc_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ucCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_03.hemoglobin
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String hemoglobin;


    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.status
     *
     * @param status the value for HSDB01_03.status
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.height_evaluation
     *
     * @return the value of HSDB01_03.height_evaluation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHeightEvaluation() {
        return heightEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.height_evaluation
     *
     * @param heightEvaluation the value for HSDB01_03.height_evaluation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHeightEvaluation(String heightEvaluation) {
        this.heightEvaluation = heightEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.front_tension
     *
     * @return the value of HSDB01_03.front_tension
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFrontTension() {
        return frontTension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.front_tension
     *
     * @param frontTension the value for HSDB01_03.front_tension
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFrontTension(String frontTension) {
        this.frontTension = frontTension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.teething
     *
     * @return the value of HSDB01_03.teething
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTeething() {
        return teething;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.teething
     *
     * @param teething the value for HSDB01_03.teething
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTeething(String teething) {
        this.teething = teething;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.patient_name
     *
     * @return the value of HSDB01_03.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.patient_name
     *
     * @param patientName the value for HSDB01_03.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.genitals_result
     *
     * @return the value of HSDB01_03.genitals_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getGenitalsResult() {
        return genitalsResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.genitals_result
     *
     * @param genitalsResult the value for HSDB01_03.genitals_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setGenitalsResult(String genitalsResult) {
        this.genitalsResult = genitalsResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.custodian_telecom
     *
     * @return the value of HSDB01_03.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.custodian_telecom
     *
     * @param custodianTelecom the value for HSDB01_03.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.rickets_symptom
     *
     * @return the value of HSDB01_03.rickets_symptom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRicketsSymptom() {
        return ricketsSymptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.rickets_symptom
     *
     * @param ricketsSymptom the value for HSDB01_03.rickets_symptom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRicketsSymptom(String ricketsSymptom) {
        this.ricketsSymptom = ricketsSymptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.right_chyperopia
     *
     * @return the value of HSDB01_03.right_chyperopia
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getRightChyperopia() {
        return rightChyperopia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.right_chyperopia
     *
     * @param rightChyperopia the value for HSDB01_03.right_chyperopia
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRightChyperopia(Float rightChyperopia) {
        this.rightChyperopia = rightChyperopia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.template_oid
     *
     * @return the value of HSDB01_03.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.template_oid
     *
     * @param templateOid the value for HSDB01_03.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.palpation_desc
     *
     * @return the value of HSDB01_03.palpation_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPalpationDesc() {
        return palpationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.palpation_desc
     *
     * @param palpationDesc the value for HSDB01_03.palpation_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPalpationDesc(String palpationDesc) {
        this.palpationDesc = palpationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.mi_code
     *
     * @return the value of HSDB01_03.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.mi_code
     *
     * @param miCode the value for HSDB01_03.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.trauma_times
     *
     * @return the value of HSDB01_03.trauma_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTraumaTimes() {
        return traumaTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.trauma_times
     *
     * @param traumaTimes the value for HSDB01_03.trauma_times
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTraumaTimes(String traumaTimes) {
        this.traumaTimes = traumaTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.front_ld
     *
     * @return the value of HSDB01_03.front_ld
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getFrontLd() {
        return frontLd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.front_ld
     *
     * @param frontLd the value for HSDB01_03.front_ld
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFrontLd(Float frontLd) {
        this.frontLd = frontLd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.fu_date
     *
     * @return the value of HSDB01_03.fu_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getFuDate() {
        return fuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.fu_date
     *
     * @param fuDate the value for HSDB01_03.fu_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuDate(Date fuDate) {
        this.fuDate = fuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.os_mark
     *
     * @return the value of HSDB01_03.os_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getOsMark() {
        return osMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.os_mark
     *
     * @param osMark the value for HSDB01_03.os_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOsMark(Boolean osMark) {
        this.osMark = osMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.xds_version
     *
     * @return the value of HSDB01_03.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.xds_version
     *
     * @param xdsVersion the value for HSDB01_03.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.spine_desc
     *
     * @return the value of HSDB01_03.spine_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSpineDesc() {
        return spineDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.spine_desc
     *
     * @param spineDesc the value for HSDB01_03.spine_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSpineDesc(String spineDesc) {
        this.spineDesc = spineDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.custodian_code
     *
     * @return the value of HSDB01_03.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.custodian_code
     *
     * @param custodianCode the value for HSDB01_03.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.pk
     *
     * @return the value of HSDB01_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.pk
     *
     * @param pk the value for HSDB01_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.complexion_name
     *
     * @return the value of HSDB01_03.complexion_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getComplexionName() {
        return complexionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.complexion_name
     *
     * @param complexionName the value for HSDB01_03.complexion_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setComplexionName(String complexionName) {
        this.complexionName = complexionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.pass_mark
     *
     * @return the value of HSDB01_03.pass_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getPassMark() {
        return passMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.pass_mark
     *
     * @param passMark the value for HSDB01_03.pass_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPassMark(Boolean passMark) {
        this.passMark = passMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.right_ndiastolic
     *
     * @return the value of HSDB01_03.right_ndiastolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getRightNdiastolic() {
        return rightNdiastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.right_ndiastolic
     *
     * @param rightNdiastolic the value for HSDB01_03.right_ndiastolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRightNdiastolic(Float rightNdiastolic) {
        this.rightNdiastolic = rightNdiastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.lungs_desc
     *
     * @return the value of HSDB01_03.lungs_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getLungsDesc() {
        return lungsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.lungs_desc
     *
     * @param lungsDesc the value for HSDB01_03.lungs_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLungsDesc(String lungsDesc) {
        this.lungsDesc = lungsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.author_code
     *
     * @return the value of HSDB01_03.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.author_code
     *
     * @param authorCode the value for HSDB01_03.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.pneumonia_times
     *
     * @return the value of HSDB01_03.pneumonia_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPneumoniaTimes() {
        return pneumoniaTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.pneumonia_times
     *
     * @param pneumoniaTimes the value for HSDB01_03.pneumonia_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPneumoniaTimes(String pneumoniaTimes) {
        this.pneumoniaTimes = pneumoniaTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.asc_mark
     *
     * @return the value of HSDB01_03.asc_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getAscMark() {
        return ascMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.asc_mark
     *
     * @param ascMark the value for HSDB01_03.asc_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAscMark(Boolean ascMark) {
        this.ascMark = ascMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.inmi_code
     *
     * @return the value of HSDB01_03.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiCode() {
        return inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.inmi_code
     *
     * @param inmiCode the value for HSDB01_03.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiCode(String inmiCode) {
        this.inmiCode = inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.listen_code
     *
     * @return the value of HSDB01_03.listen_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getListenCode() {
        return listenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.listen_code
     *
     * @param listenCode the value for HSDB01_03.listen_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setListenCode(String listenCode) {
        this.listenCode = listenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.class_name
     *
     * @return the value of HSDB01_03.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.class_name
     *
     * @param className the value for HSDB01_03.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.extremities_desc
     *
     * @return the value of HSDB01_03.extremities_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getExtremitiesDesc() {
        return extremitiesDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.extremities_desc
     *
     * @param extremitiesDesc the value for HSDB01_03.extremities_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setExtremitiesDesc(String extremitiesDesc) {
        this.extremitiesDesc = extremitiesDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.domain_id
     *
     * @return the value of HSDB01_03.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.domain_id
     *
     * @param domainId the value for HSDB01_03.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.develop_evaluate_code
     *
     * @return the value of HSDB01_03.develop_evaluate_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDevelopEvaluateCode() {
        return developEvaluateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.develop_evaluate_code
     *
     * @param developEvaluateCode the value for HSDB01_03.develop_evaluate_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDevelopEvaluateCode(String developEvaluateCode) {
        this.developEvaluateCode = developEvaluateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.mass_desc
     *
     * @return the value of HSDB01_03.mass_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMassDesc() {
        return massDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.mass_desc
     *
     * @param massDesc the value for HSDB01_03.mass_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMassDesc(String massDesc) {
        this.massDesc = massDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.auscultation_result
     *
     * @return the value of HSDB01_03.auscultation_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuscultationResult() {
        return auscultationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.auscultation_result
     *
     * @param auscultationResult the value for HSDB01_03.auscultation_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuscultationResult(String auscultationResult) {
        this.auscultationResult = auscultationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.birth
     *
     * @return the value of HSDB01_03.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.birth
     *
     * @param birth the value for HSDB01_03.birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.outdoor_duration
     *
     * @return the value of HSDB01_03.outdoor_duration
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getOutdoorDuration() {
        return outdoorDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.outdoor_duration
     *
     * @param outdoorDuration the value for HSDB01_03.outdoor_duration
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOutdoorDuration(Float outdoorDuration) {
        this.outdoorDuration = outdoorDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.height
     *
     * @return the value of HSDB01_03.height
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.height
     *
     * @param height the value for HSDB01_03.height
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.gait_sign
     *
     * @return the value of HSDB01_03.gait_sign
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getGaitSign() {
        return gaitSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.gait_sign
     *
     * @param gaitSign the value for HSDB01_03.gait_sign
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setGaitSign(Boolean gaitSign) {
        this.gaitSign = gaitSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.indept_code
     *
     * @return the value of HSDB01_03.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIndeptCode() {
        return indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.indept_code
     *
     * @param indeptCode the value for HSDB01_03.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptCode(String indeptCode) {
        this.indeptCode = indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.ear_mark
     *
     * @return the value of HSDB01_03.ear_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getEarMark() {
        return earMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.ear_mark
     *
     * @param earMark the value for HSDB01_03.ear_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEarMark(Boolean earMark) {
        this.earMark = earMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.xds_name
     *
     * @return the value of HSDB01_03.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.xds_name
     *
     * @param xdsName the value for HSDB01_03.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.uc_result
     *
     * @return the value of HSDB01_03.uc_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUcResult() {
        return ucResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.uc_result
     *
     * @param ucResult the value for HSDB01_03.uc_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUcResult(String ucResult) {
        this.ucResult = ucResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.empi
     *
     * @return the value of HSDB01_03.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.empi
     *
     * @param empi the value for HSDB01_03.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.weight_evaluation_code
     *
     * @return the value of HSDB01_03.weight_evaluation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWeightEvaluationCode() {
        return weightEvaluationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.weight_evaluation_code
     *
     * @param weightEvaluationCode the value for HSDB01_03.weight_evaluation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWeightEvaluationCode(String weightEvaluationCode) {
        this.weightEvaluationCode = weightEvaluationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.head_dimension
     *
     * @return the value of HSDB01_03.head_dimension
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getHeadDimension() {
        return headDimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.head_dimension
     *
     * @param headDimension the value for HSDB01_03.head_dimension
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHeadDimension(Float headDimension) {
        this.headDimension = headDimension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.dental_caries
     *
     * @return the value of HSDB01_03.dental_caries
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDentalCaries() {
        return dentalCaries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.dental_caries
     *
     * @param dentalCaries the value for HSDB01_03.dental_caries
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDentalCaries(String dentalCaries) {
        this.dentalCaries = dentalCaries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.sex_code
     *
     * @return the value of HSDB01_03.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.sex_code
     *
     * @param sexCode the value for HSDB01_03.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.anus_mark
     *
     * @return the value of HSDB01_03.anus_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getAnusMark() {
        return anusMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.anus_mark
     *
     * @param anusMark the value for HSDB01_03.anus_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAnusMark(Boolean anusMark) {
        this.anusMark = anusMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.custodian_addr
     *
     * @return the value of HSDB01_03.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.custodian_addr
     *
     * @param custodianAddr the value for HSDB01_03.custodian_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.rickets_signs_code
     *
     * @return the value of HSDB01_03.rickets_signs_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRicketsSignsCode() {
        return ricketsSignsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.rickets_signs_code
     *
     * @param ricketsSignsCode the value for HSDB01_03.rickets_signs_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRicketsSignsCode(String ricketsSignsCode) {
        this.ricketsSignsCode = ricketsSignsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.referral_mark
     *
     * @return the value of HSDB01_03.referral_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getReferralMark() {
        return referralMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.referral_mark
     *
     * @param referralMark the value for HSDB01_03.referral_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralMark(Boolean referralMark) {
        this.referralMark = referralMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.eye_shape_mark
     *
     * @return the value of HSDB01_03.eye_shape_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getEyeShapeMark() {
        return eyeShapeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.eye_shape_mark
     *
     * @param eyeShapeMark the value for HSDB01_03.eye_shape_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEyeShapeMark(Boolean eyeShapeMark) {
        this.eyeShapeMark = eyeShapeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.unique_id
     *
     * @return the value of HSDB01_03.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.unique_id
     *
     * @param uniqueId the value for HSDB01_03.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.uc_mark
     *
     * @return the value of HSDB01_03.uc_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getUcMark() {
        return ucMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.uc_mark
     *
     * @param ucMark the value for HSDB01_03.uc_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUcMark(Boolean ucMark) {
        this.ucMark = ucMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.mi_name
     *
     * @return the value of HSDB01_03.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.mi_name
     *
     * @param miName the value for HSDB01_03.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.illness
     *
     * @return the value of HSDB01_03.illness
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIllness() {
        return illness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.illness
     *
     * @param illness the value for HSDB01_03.illness
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIllness(String illness) {
        this.illness = illness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.upload_time
     *
     * @return the value of HSDB01_03.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.upload_time
     *
     * @param uploadTime the value for HSDB01_03.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.height_evaluation_code
     *
     * @return the value of HSDB01_03.height_evaluation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHeightEvaluationCode() {
        return heightEvaluationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.height_evaluation_code
     *
     * @param heightEvaluationCode the value for HSDB01_03.height_evaluation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHeightEvaluationCode(String heightEvaluationCode) {
        this.heightEvaluationCode = heightEvaluationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.front_tension_code
     *
     * @return the value of HSDB01_03.front_tension_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFrontTensionCode() {
        return frontTensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.front_tension_code
     *
     * @param frontTensionCode the value for HSDB01_03.front_tension_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFrontTensionCode(String frontTensionCode) {
        this.frontTensionCode = frontTensionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.os_result
     *
     * @return the value of HSDB01_03.os_result
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOsResult() {
        return osResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.os_result
     *
     * @param osResult the value for HSDB01_03.os_result
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOsResult(String osResult) {
        this.osResult = osResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.health_no
     *
     * @return the value of HSDB01_03.health_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthNo() {
        return healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.health_no
     *
     * @param healthNo the value for HSDB01_03.health_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthNo(String healthNo) {
        this.healthNo = healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.genitals_mark
     *
     * @return the value of HSDB01_03.genitals_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getGenitalsMark() {
        return genitalsMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.genitals_mark
     *
     * @param genitalsMark the value for HSDB01_03.genitals_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setGenitalsMark(Boolean genitalsMark) {
        this.genitalsMark = genitalsMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.custodian_name
     *
     * @return the value of HSDB01_03.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.custodian_name
     *
     * @param custodianName the value for HSDB01_03.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.rickets_symptom_code
     *
     * @return the value of HSDB01_03.rickets_symptom_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRicketsSymptomCode() {
        return ricketsSymptomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.rickets_symptom_code
     *
     * @param ricketsSymptomCode the value for HSDB01_03.rickets_symptom_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRicketsSymptomCode(String ricketsSymptomCode) {
        this.ricketsSymptomCode = ricketsSymptomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.left_chyperopia
     *
     * @return the value of HSDB01_03.left_chyperopia
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getLeftChyperopia() {
        return leftChyperopia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.left_chyperopia
     *
     * @param leftChyperopia the value for HSDB01_03.left_chyperopia
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLeftChyperopia(Float leftChyperopia) {
        this.leftChyperopia = leftChyperopia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.register_model
     *
     * @return the value of HSDB01_03.register_model
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.register_model
     *
     * @param registerModel the value for HSDB01_03.register_model
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.abdomen_mark
     *
     * @return the value of HSDB01_03.abdomen_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getAbdomenMark() {
        return abdomenMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.abdomen_mark
     *
     * @param abdomenMark the value for HSDB01_03.abdomen_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAbdomenMark(Boolean abdomenMark) {
        this.abdomenMark = abdomenMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.author_name
     *
     * @return the value of HSDB01_03.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.author_name
     *
     * @param authorName the value for HSDB01_03.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.diarrhea_times
     *
     * @return the value of HSDB01_03.diarrhea_times
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDiarrheaTimes() {
        return diarrheaTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.diarrhea_times
     *
     * @param diarrheaTimes the value for HSDB01_03.diarrhea_times
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDiarrheaTimes(String diarrheaTimes) {
        this.diarrheaTimes = diarrheaTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.front_td
     *
     * @return the value of HSDB01_03.front_td
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getFrontTd() {
        return frontTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.front_td
     *
     * @param frontTd the value for HSDB01_03.front_td
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFrontTd(Float frontTd) {
        this.frontTd = frontTd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.inmi_name
     *
     * @return the value of HSDB01_03.inmi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiName() {
        return inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.inmi_name
     *
     * @param inmiName the value for HSDB01_03.inmi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiName(String inmiName) {
        this.inmiName = inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.listen_result
     *
     * @return the value of HSDB01_03.listen_result
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getListenResult() {
        return listenResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.listen_result
     *
     * @param listenResult the value for HSDB01_03.listen_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setListenResult(String listenResult) {
        this.listenResult = listenResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.class_code
     *
     * @return the value of HSDB01_03.class_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.class_code
     *
     * @param classCode the value for HSDB01_03.class_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.spine_mark
     *
     * @return the value of HSDB01_03.spine_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getSpineMark() {
        return spineMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.spine_mark
     *
     * @param spineMark the value for HSDB01_03.spine_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSpineMark(Boolean spineMark) {
        this.spineMark = spineMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.mi_addr
     *
     * @return the value of HSDB01_03.mi_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.mi_addr
     *
     * @param miAddr the value for HSDB01_03.mi_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.complexion_code
     *
     * @return the value of HSDB01_03.complexion_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getComplexionCode() {
        return complexionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.complexion_code
     *
     * @param complexionCode the value for HSDB01_03.complexion_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setComplexionCode(String complexionCode) {
        this.complexionCode = complexionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.develop_evaluate
     *
     * @return the value of HSDB01_03.develop_evaluate
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDevelopEvaluate() {
        return developEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.develop_evaluate
     *
     * @param developEvaluate the value for HSDB01_03.develop_evaluate
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDevelopEvaluate(String developEvaluate) {
        this.developEvaluate = developEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.left_ndiastolic
     *
     * @return the value of HSDB01_03.left_ndiastolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getLeftNdiastolic() {
        return leftNdiastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.left_ndiastolic
     *
     * @param leftNdiastolic the value for HSDB01_03.left_ndiastolic
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLeftNdiastolic(Float leftNdiastolic) {
        this.leftNdiastolic = leftNdiastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.lungs_mark
     *
     * @return the value of HSDB01_03.lungs_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getLungsMark() {
        return lungsMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.lungs_mark
     *
     * @param lungsMark the value for HSDB01_03.lungs_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLungsMark(Boolean lungsMark) {
        this.lungsMark = lungsMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.write_time
     *
     * @return the value of HSDB01_03.write_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.write_time
     *
     * @param writeTime the value for HSDB01_03.write_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.sick_mark
     *
     * @return the value of HSDB01_03.sick_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getSickMark() {
        return sickMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.sick_mark
     *
     * @param sickMark the value for HSDB01_03.sick_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSickMark(Boolean sickMark) {
        this.sickMark = sickMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.skin_mark
     *
     * @return the value of HSDB01_03.skin_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getSkinMark() {
        return skinMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.skin_mark
     *
     * @param skinMark the value for HSDB01_03.skin_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSkinMark(Boolean skinMark) {
        this.skinMark = skinMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.indept_name
     *
     * @return the value of HSDB01_03.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIndeptName() {
        return indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.indept_name
     *
     * @param indeptName the value for HSDB01_03.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptName(String indeptName) {
        this.indeptName = indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.ear_result
     *
     * @return the value of HSDB01_03.ear_result
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEarResult() {
        return earResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.ear_result
     *
     * @param earResult the value for HSDB01_03.ear_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEarResult(String earResult) {
        this.earResult = earResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.effective_time
     *
     * @return the value of HSDB01_03.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.effective_time
     *
     * @param effectiveTime the value for HSDB01_03.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.extremities_mark
     *
     * @return the value of HSDB01_03.extremities_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getExtremitiesMark() {
        return extremitiesMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.extremities_mark
     *
     * @param extremitiesMark the value for HSDB01_03.extremities_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setExtremitiesMark(Boolean extremitiesMark) {
        this.extremitiesMark = extremitiesMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.encounter_id
     *
     * @return the value of HSDB01_03.encounter_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.encounter_id
     *
     * @param encounterId the value for HSDB01_03.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.weight_evaluation
     *
     * @return the value of HSDB01_03.weight_evaluation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWeightEvaluation() {
        return weightEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.weight_evaluation
     *
     * @param weightEvaluation the value for HSDB01_03.weight_evaluation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWeightEvaluation(String weightEvaluation) {
        this.weightEvaluation = weightEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.mass_mark
     *
     * @return the value of HSDB01_03.mass_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getMassMark() {
        return massMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.mass_mark
     *
     * @param massMark the value for HSDB01_03.mass_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMassMark(Boolean massMark) {
        this.massMark = massMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.auscultation_mark
     *
     * @return the value of HSDB01_03.auscultation_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getAuscultationMark() {
        return auscultationMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.auscultation_mark
     *
     * @param auscultationMark the value for HSDB01_03.auscultation_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuscultationMark(Boolean auscultationMark) {
        this.auscultationMark = auscultationMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.sex
     *
     * @return the value of HSDB01_03.sex
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.sex
     *
     * @param sex the value for HSDB01_03.sex
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.anus_check
     *
     * @return the value of HSDB01_03.anus_check
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAnusCheck() {
        return anusCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.anus_check
     *
     * @param anusCheck the value for HSDB01_03.anus_check
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAnusCheck(String anusCheck) {
        this.anusCheck = anusCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.length
     *
     * @return the value of HSDB01_03.length
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.length
     *
     * @param length the value for HSDB01_03.length
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLength(Float length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.rickets_signs
     *
     * @return the value of HSDB01_03.rickets_signs
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRicketsSigns() {
        return ricketsSigns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.rickets_signs
     *
     * @param ricketsSigns the value for HSDB01_03.rickets_signs
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRicketsSigns(String ricketsSigns) {
        this.ricketsSigns = ricketsSigns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.referral_reason
     *
     * @return the value of HSDB01_03.referral_reason
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getReferralReason() {
        return referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.referral_reason
     *
     * @param referralReason the value for HSDB01_03.referral_reason
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralReason(String referralReason) {
        this.referralReason = referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.eye_shape
     *
     * @return the value of HSDB01_03.eye_shape
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEyeShape() {
        return eyeShape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.eye_shape
     *
     * @param eyeShape the value for HSDB01_03.eye_shape
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEyeShape(String eyeShape) {
        this.eyeShape = eyeShape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.xds_type
     *
     * @return the value of HSDB01_03.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.xds_type
     *
     * @param xdsType the value for HSDB01_03.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.uc_code
     *
     * @return the value of HSDB01_03.uc_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUcCode() {
        return ucCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.uc_code
     *
     * @param ucCode the value for HSDB01_03.uc_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUcCode(String ucCode) {
        this.ucCode = ucCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_03.hemoglobin
     *
     * @return the value of HSDB01_03.hemoglobin
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHemoglobin() {
        return hemoglobin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_03.hemoglobin
     *
     * @param hemoglobin the value for HSDB01_03.hemoglobin
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHemoglobin(String hemoglobin) {
        this.hemoglobin = hemoglobin;
    }
}