package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("HSDB03_02")
public class Hsdb0302 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.revise_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String reviseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.workplace_township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String workplaceTownship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.onset_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String onsetCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.workplace_house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String workplaceHouseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.census_county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String streetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.ownership_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ownershipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.workplace
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String workplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.census_street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusStreetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.infectious_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String infectiousType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.identify_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String identifyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.report_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String reportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.workplace_province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String workplaceProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.diag_status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String diagStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ostalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.occupation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String occupationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.death_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date deathDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.workplace_county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String workplaceCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.onset_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String onsetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.workplace_street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String workplaceStreetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.census_city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.oinfectious_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String oinfectiousName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.first_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date firstDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String township;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.check_out
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String checkOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.workplace_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String workplaceTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.censustownship
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censustownship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String houseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.ownership_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ownershipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.census_house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusHouseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.infectious_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String infectiousTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String telecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.occupation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.report_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String reportTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.workplace_city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String workplaceCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.diag_status_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String diagStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_02.census_province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusProvince;


    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.class_name
     *
     * @param className the value for HSDB03_02.class_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.revise_name
     *
     * @return the value of HSDB03_02.revise_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getReviseName() {
        return reviseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.revise_name
     *
     * @param reviseName the value for HSDB03_02.revise_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReviseName(String reviseName) {
        this.reviseName = reviseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.birth
     *
     * @return the value of HSDB03_02.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.birth
     *
     * @param birth the value for HSDB03_02.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.workplace_township
     *
     * @return the value of HSDB03_02.workplace_township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWorkplaceTownship() {
        return workplaceTownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.workplace_township
     *
     * @param workplaceTownship the value for HSDB03_02.workplace_township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWorkplaceTownship(String workplaceTownship) {
        this.workplaceTownship = workplaceTownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.mi_name
     *
     * @return the value of HSDB03_02.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.mi_name
     *
     * @param miName the value for HSDB03_02.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.onset_code
     *
     * @return the value of HSDB03_02.onset_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOnsetCode() {
        return onsetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.onset_code
     *
     * @param onsetCode the value for HSDB03_02.onset_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOnsetCode(String onsetCode) {
        this.onsetCode = onsetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.county
     *
     * @return the value of HSDB03_02.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.county
     *
     * @param county the value for HSDB03_02.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.workplace_house_number
     *
     * @return the value of HSDB03_02.workplace_house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWorkplaceHouseNumber() {
        return workplaceHouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.workplace_house_number
     *
     * @param workplaceHouseNumber the value for HSDB03_02.workplace_house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWorkplaceHouseNumber(String workplaceHouseNumber) {
        this.workplaceHouseNumber = workplaceHouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.census_county
     *
     * @return the value of HSDB03_02.census_county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusCounty() {
        return censusCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.census_county
     *
     * @param censusCounty the value for HSDB03_02.census_county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusCounty(String censusCounty) {
        this.censusCounty = censusCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.xds_name
     *
     * @return the value of HSDB03_02.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.xds_name
     *
     * @param xdsName the value for HSDB03_02.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.sex_code
     *
     * @return the value of HSDB03_02.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.sex_code
     *
     * @param sexCode the value for HSDB03_02.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.domain_id
     *
     * @return the value of HSDB03_02.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.domain_id
     *
     * @param domainId the value for HSDB03_02.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.author_name
     *
     * @return the value of HSDB03_02.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.author_name
     *
     * @param authorName the value for HSDB03_02.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.custodian_addr
     *
     * @return the value of HSDB03_02.custodian_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.custodian_addr
     *
     * @param custodianAddr the value for HSDB03_02.custodian_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.street_name
     *
     * @return the value of HSDB03_02.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.street_name
     *
     * @param streetName the value for HSDB03_02.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.ownership_name
     *
     * @return the value of HSDB03_02.ownership_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOwnershipName() {
        return ownershipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.ownership_name
     *
     * @param ownershipName the value for HSDB03_02.ownership_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOwnershipName(String ownershipName) {
        this.ownershipName = ownershipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.workplace
     *
     * @return the value of HSDB03_02.workplace
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWorkplace() {
        return workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.workplace
     *
     * @param workplace the value for HSDB03_02.workplace
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWorkplace(String workplace) {
        this.workplace = workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.census_street_name
     *
     * @return the value of HSDB03_02.census_street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusStreetName() {
        return censusStreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.census_street_name
     *
     * @param censusStreetName the value for HSDB03_02.census_street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusStreetName(String censusStreetName) {
        this.censusStreetName = censusStreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.unique_id
     *
     * @return the value of HSDB03_02.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.unique_id
     *
     * @param uniqueId the value for HSDB03_02.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.infectious_type
     *
     * @return the value of HSDB03_02.infectious_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInfectiousType() {
        return infectiousType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.infectious_type
     *
     * @param infectiousType the value for HSDB03_02.infectious_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInfectiousType(String infectiousType) {
        this.infectiousType = infectiousType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.identify_no
     *
     * @return the value of HSDB03_02.identify_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIdentifyNo() {
        return identifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.identify_no
     *
     * @param identifyNo the value for HSDB03_02.identify_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIdentifyNo(String identifyNo) {
        this.identifyNo = identifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.empi
     *
     * @return the value of HSDB03_02.empi
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.empi
     *
     * @param empi the value for HSDB03_02.empi
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.write_time
     *
     * @return the value of HSDB03_02.write_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.write_time
     *
     * @param writeTime the value for HSDB03_02.write_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.custodian_name
     *
     * @return the value of HSDB03_02.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.custodian_name
     *
     * @param custodianName the value for HSDB03_02.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.health_no
     *
     * @return the value of HSDB03_02.health_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthNo() {
        return healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.health_no
     *
     * @param healthNo the value for HSDB03_02.health_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthNo(String healthNo) {
        this.healthNo = healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.report_type
     *
     * @return the value of HSDB03_02.report_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.report_type
     *
     * @param reportType the value for HSDB03_02.report_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.workplace_province
     *
     * @return the value of HSDB03_02.workplace_province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWorkplaceProvince() {
        return workplaceProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.workplace_province
     *
     * @param workplaceProvince the value for HSDB03_02.workplace_province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWorkplaceProvince(String workplaceProvince) {
        this.workplaceProvince = workplaceProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.register_model
     *
     * @return the value of HSDB03_02.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.register_model
     *
     * @param registerModel the value for HSDB03_02.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.diag_status
     *
     * @return the value of HSDB03_02.diag_status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDiagStatus() {
        return diagStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.diag_status
     *
     * @param diagStatus the value for HSDB03_02.diag_status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDiagStatus(String diagStatus) {
        this.diagStatus = diagStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.ostal_code
     *
     * @return the value of HSDB03_02.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOstalCode() {
        return ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.ostal_code
     *
     * @param ostalCode the value for HSDB03_02.ostal_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOstalCode(String ostalCode) {
        this.ostalCode = ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.upload_time
     *
     * @return the value of HSDB03_02.upload_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.upload_time
     *
     * @param uploadTime the value for HSDB03_02.upload_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.occupation_code
     *
     * @return the value of HSDB03_02.occupation_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOccupationCode() {
        return occupationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.occupation_code
     *
     * @param occupationCode the value for HSDB03_02.occupation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOccupationCode(String occupationCode) {
        this.occupationCode = occupationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.class_code
     *
     * @return the value of HSDB03_02.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.class_code
     *
     * @param classCode the value for HSDB03_02.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.death_date
     *
     * @return the value of HSDB03_02.death_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getDeathDate() {
        return deathDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.death_date
     *
     * @param deathDate the value for HSDB03_02.death_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDeathDate(Date deathDate) {
        this.deathDate = deathDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.workplace_county
     *
     * @return the value of HSDB03_02.workplace_county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWorkplaceCounty() {
        return workplaceCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.workplace_county
     *
     * @param workplaceCounty the value for HSDB03_02.workplace_county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWorkplaceCounty(String workplaceCounty) {
        this.workplaceCounty = workplaceCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.mi_addr
     *
     * @return the value of HSDB03_02.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.mi_addr
     *
     * @param miAddr the value for HSDB03_02.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.onset_type
     *
     * @return the value of HSDB03_02.onset_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOnsetType() {
        return onsetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.onset_type
     *
     * @param onsetType the value for HSDB03_02.onset_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOnsetType(String onsetType) {
        this.onsetType = onsetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.city
     *
     * @return the value of HSDB03_02.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.city
     *
     * @param city the value for HSDB03_02.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.workplace_street_name
     *
     * @return the value of HSDB03_02.workplace_street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWorkplaceStreetName() {
        return workplaceStreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.workplace_street_name
     *
     * @param workplaceStreetName the value for HSDB03_02.workplace_street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWorkplaceStreetName(String workplaceStreetName) {
        this.workplaceStreetName = workplaceStreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.census_city
     *
     * @return the value of HSDB03_02.census_city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusCity() {
        return censusCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.census_city
     *
     * @param censusCity the value for HSDB03_02.census_city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusCity(String censusCity) {
        this.censusCity = censusCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.effective_time
     *
     * @return the value of HSDB03_02.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.effective_time
     *
     * @param effectiveTime the value for HSDB03_02.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.oinfectious_name
     *
     * @return the value of HSDB03_02.oinfectious_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOinfectiousName() {
        return oinfectiousName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.oinfectious_name
     *
     * @param oinfectiousName the value for HSDB03_02.oinfectious_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOinfectiousName(String oinfectiousName) {
        this.oinfectiousName = oinfectiousName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.sex
     *
     * @return the value of HSDB03_02.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.sex
     *
     * @param sex the value for HSDB03_02.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.mi_code
     *
     * @return the value of HSDB03_02.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.mi_code
     *
     * @param miCode the value for HSDB03_02.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.first_date
     *
     * @return the value of HSDB03_02.first_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getFirstDate() {
        return firstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.first_date
     *
     * @param firstDate the value for HSDB03_02.first_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFirstDate(Date firstDate) {
        this.firstDate = firstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.township
     *
     * @return the value of HSDB03_02.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTownship() {
        return township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.township
     *
     * @param township the value for HSDB03_02.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTownship(String township) {
        this.township = township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.check_out
     *
     * @return the value of HSDB03_02.check_out
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCheckOut() {
        return checkOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.check_out
     *
     * @param checkOut the value for HSDB03_02.check_out
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCheckOut(String checkOut) {
        this.checkOut = checkOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.workplace_telecom
     *
     * @return the value of HSDB03_02.workplace_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWorkplaceTelecom() {
        return workplaceTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.workplace_telecom
     *
     * @param workplaceTelecom the value for HSDB03_02.workplace_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWorkplaceTelecom(String workplaceTelecom) {
        this.workplaceTelecom = workplaceTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.censustownship
     *
     * @return the value of HSDB03_02.censustownship
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensustownship() {
        return censustownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.censustownship
     *
     * @param censustownship the value for HSDB03_02.censustownship
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensustownship(String censustownship) {
        this.censustownship = censustownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.xds_type
     *
     * @return the value of HSDB03_02.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.xds_type
     *
     * @param xdsType the value for HSDB03_02.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.patient_name
     *
     * @return the value of HSDB03_02.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.patient_name
     *
     * @param patientName the value for HSDB03_02.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.encounter_id
     *
     * @return the value of HSDB03_02.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.encounter_id
     *
     * @param encounterId the value for HSDB03_02.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.author_code
     *
     * @return the value of HSDB03_02.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.author_code
     *
     * @param authorCode the value for HSDB03_02.author_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.custodian_telecom
     *
     * @return the value of HSDB03_02.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.custodian_telecom
     *
     * @param custodianTelecom the value for HSDB03_02.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.house_number
     *
     * @return the value of HSDB03_02.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.house_number
     *
     * @param houseNumber the value for HSDB03_02.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.ownership_code
     *
     * @return the value of HSDB03_02.ownership_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOwnershipCode() {
        return ownershipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.ownership_code
     *
     * @param ownershipCode the value for HSDB03_02.ownership_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOwnershipCode(String ownershipCode) {
        this.ownershipCode = ownershipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.census_house_number
     *
     * @return the value of HSDB03_02.census_house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusHouseNumber() {
        return censusHouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.census_house_number
     *
     * @param censusHouseNumber the value for HSDB03_02.census_house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusHouseNumber(String censusHouseNumber) {
        this.censusHouseNumber = censusHouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.template_oid
     *
     * @return the value of HSDB03_02.template_oid
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.template_oid
     *
     * @param templateOid the value for HSDB03_02.template_oid
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.infectious_type_code
     *
     * @return the value of HSDB03_02.infectious_type_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInfectiousTypeCode() {
        return infectiousTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.infectious_type_code
     *
     * @param infectiousTypeCode the value for HSDB03_02.infectious_type_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInfectiousTypeCode(String infectiousTypeCode) {
        this.infectiousTypeCode = infectiousTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.telecom
     *
     * @return the value of HSDB03_02.telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTelecom() {
        return telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.telecom
     *
     * @param telecom the value for HSDB03_02.telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTelecom(String telecom) {
        this.telecom = telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.status
     *
     * @return the value of HSDB03_02.status
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.status
     *
     * @param status the value for HSDB03_02.status
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.occupation
     *
     * @return the value of HSDB03_02.occupation
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.occupation
     *
     * @param occupation the value for HSDB03_02.occupation
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.custodian_code
     *
     * @return the value of HSDB03_02.custodian_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.custodian_code
     *
     * @param custodianCode the value for HSDB03_02.custodian_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.xds_version
     *
     * @return the value of HSDB03_02.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.xds_version
     *
     * @param xdsVersion the value for HSDB03_02.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.report_type_code
     *
     * @return the value of HSDB03_02.report_type_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getReportTypeCode() {
        return reportTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.report_type_code
     *
     * @param reportTypeCode the value for HSDB03_02.report_type_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReportTypeCode(String reportTypeCode) {
        this.reportTypeCode = reportTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.workplace_city
     *
     * @return the value of HSDB03_02.workplace_city
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWorkplaceCity() {
        return workplaceCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.workplace_city
     *
     * @param workplaceCity the value for HSDB03_02.workplace_city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWorkplaceCity(String workplaceCity) {
        this.workplaceCity = workplaceCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.diag_status_code
     *
     * @return the value of HSDB03_02.diag_status_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDiagStatusCode() {
        return diagStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.diag_status_code
     *
     * @param diagStatusCode the value for HSDB03_02.diag_status_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDiagStatusCode(String diagStatusCode) {
        this.diagStatusCode = diagStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.province
     *
     * @return the value of HSDB03_02.province
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.province
     *
     * @param province the value for HSDB03_02.province
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.pk
     *
     * @return the value of HSDB03_02.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.pk
     *
     * @param pk the value for HSDB03_02.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_02.census_province
     *
     * @return the value of HSDB03_02.census_province
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusProvince() {
        return censusProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_02.census_province
     *
     * @param censusProvince the value for HSDB03_02.census_province
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusProvince(String censusProvince) {
        this.censusProvince = censusProvince;
    }
}