package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("HSDB04_03")
public class Hsdb0403 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.onset_age
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String onsetAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.diag_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date diagDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.signer_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String signerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.treatment_effect_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String treatmentEffectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.agreer
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String agreer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.economic_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String economicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.signer_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date signerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.treatment_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date treatmentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.doctor_opinion
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String doctorOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.lock_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String lockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.treatment_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String treatmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.diagmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String diagmiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.sick_effect
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sickEffect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.mental_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mentalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.treatment_effect
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String treatmentEffect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.agree_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date agreeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.economic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String economic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.in_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.agree_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean agreeMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.lock_happen
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String lockHappen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.treatment
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String treatment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.diagmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String diagmiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.effect_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String effectTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.mental_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mentalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.signer_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String signerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.effect_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String effectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_03.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianAddr;


    public String getOnsetAge() {
        return onsetAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.onset_age
     *
     * @param onsetAge the value for HSDB04_03.onset_age
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOnsetAge(String onsetAge) {
        this.onsetAge = onsetAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.sex_code
     *
     * @return the value of HSDB04_03.sex_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.sex_code
     *
     * @param sexCode the value for HSDB04_03.sex_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.diag_date
     *
     * @return the value of HSDB04_03.diag_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getDiagDate() {
        return diagDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.diag_date
     *
     * @param diagDate the value for HSDB04_03.diag_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDiagDate(Date diagDate) {
        this.diagDate = diagDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.empi
     *
     * @return the value of HSDB04_03.empi
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.empi
     *
     * @param empi the value for HSDB04_03.empi
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.signer_code
     *
     * @return the value of HSDB04_03.signer_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSignerCode() {
        return signerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.signer_code
     *
     * @param signerCode the value for HSDB04_03.signer_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSignerCode(String signerCode) {
        this.signerCode = signerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.unique_id
     *
     * @return the value of HSDB04_03.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.unique_id
     *
     * @param uniqueId the value for HSDB04_03.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.treatment_effect_code
     *
     * @return the value of HSDB04_03.treatment_effect_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTreatmentEffectCode() {
        return treatmentEffectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.treatment_effect_code
     *
     * @param treatmentEffectCode the value for HSDB04_03.treatment_effect_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTreatmentEffectCode(String treatmentEffectCode) {
        this.treatmentEffectCode = treatmentEffectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.custodian_name
     *
     * @return the value of HSDB04_03.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.custodian_name
     *
     * @param custodianName the value for HSDB04_03.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.agreer
     *
     * @return the value of HSDB04_03.agreer
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAgreer() {
        return agreer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.agreer
     *
     * @param agreer the value for HSDB04_03.agreer
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAgreer(String agreer) {
        this.agreer = agreer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.health_no
     *
     * @return the value of HSDB04_03.health_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthNo() {
        return healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.health_no
     *
     * @param healthNo the value for HSDB04_03.health_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthNo(String healthNo) {
        this.healthNo = healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.economic_code
     *
     * @return the value of HSDB04_03.economic_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEconomicCode() {
        return economicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.economic_code
     *
     * @param economicCode the value for HSDB04_03.economic_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEconomicCode(String economicCode) {
        this.economicCode = economicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.upload_time
     *
     * @return the value of HSDB04_03.upload_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.upload_time
     *
     * @param uploadTime the value for HSDB04_03.upload_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.signer_time
     *
     * @return the value of HSDB04_03.signer_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getSignerTime() {
        return signerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.signer_time
     *
     * @param signerTime the value for HSDB04_03.signer_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSignerTime(Date signerTime) {
        this.signerTime = signerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.register_model
     *
     * @return the value of HSDB04_03.register_model
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.register_model
     *
     * @param registerModel the value for HSDB04_03.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.treatment_date
     *
     * @return the value of HSDB04_03.treatment_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getTreatmentDate() {
        return treatmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.treatment_date
     *
     * @param treatmentDate the value for HSDB04_03.treatment_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTreatmentDate(Date treatmentDate) {
        this.treatmentDate = treatmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.doctor_opinion
     *
     * @return the value of HSDB04_03.doctor_opinion
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDoctorOpinion() {
        return doctorOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.doctor_opinion
     *
     * @param doctorOpinion the value for HSDB04_03.doctor_opinion
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDoctorOpinion(String doctorOpinion) {
        this.doctorOpinion = doctorOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.mi_addr
     *
     * @return the value of HSDB04_03.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.mi_addr
     *
     * @param miAddr the value for HSDB04_03.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.class_code
     *
     * @return the value of HSDB04_03.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.class_code
     *
     * @param classCode the value for HSDB04_03.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.lock_code
     *
     * @return the value of HSDB04_03.lock_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getLockCode() {
        return lockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.lock_code
     *
     * @param lockCode the value for HSDB04_03.lock_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLockCode(String lockCode) {
        this.lockCode = lockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.treatment_code
     *
     * @return the value of HSDB04_03.treatment_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTreatmentCode() {
        return treatmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.treatment_code
     *
     * @param treatmentCode the value for HSDB04_03.treatment_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTreatmentCode(String treatmentCode) {
        this.treatmentCode = treatmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.diagmi_code
     *
     * @return the value of HSDB04_03.diagmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDiagmiCode() {
        return diagmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.diagmi_code
     *
     * @param diagmiCode the value for HSDB04_03.diagmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDiagmiCode(String diagmiCode) {
        this.diagmiCode = diagmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.mi_code
     *
     * @return the value of HSDB04_03.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.mi_code
     *
     * @param miCode the value for HSDB04_03.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.effective_time
     *
     * @return the value of HSDB04_03.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.effective_time
     *
     * @param effectiveTime the value for HSDB04_03.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.sick_effect
     *
     * @return the value of HSDB04_03.sick_effect
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSickEffect() {
        return sickEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.sick_effect
     *
     * @param sickEffect the value for HSDB04_03.sick_effect
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSickEffect(String sickEffect) {
        this.sickEffect = sickEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.sex
     *
     * @return the value of HSDB04_03.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.sex
     *
     * @param sex the value for HSDB04_03.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.mental_code
     *
     * @return the value of HSDB04_03.mental_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMentalCode() {
        return mentalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.mental_code
     *
     * @param mentalCode the value for HSDB04_03.mental_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMentalCode(String mentalCode) {
        this.mentalCode = mentalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.encounter_id
     *
     * @return the value of HSDB04_03.encounter_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.encounter_id
     *
     * @param encounterId the value for HSDB04_03.encounter_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.author_name
     *
     * @return the value of HSDB04_03.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.author_name
     *
     * @param authorName the value for HSDB04_03.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.xds_type
     *
     * @return the value of HSDB04_03.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.xds_type
     *
     * @param xdsType the value for HSDB04_03.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.treatment_effect
     *
     * @return the value of HSDB04_03.treatment_effect
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTreatmentEffect() {
        return treatmentEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.treatment_effect
     *
     * @param treatmentEffect the value for HSDB04_03.treatment_effect
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTreatmentEffect(String treatmentEffect) {
        this.treatmentEffect = treatmentEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.custodian_telecom
     *
     * @return the value of HSDB04_03.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.custodian_telecom
     *
     * @param custodianTelecom the value for HSDB04_03.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.agree_date
     *
     * @return the value of HSDB04_03.agree_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getAgreeDate() {
        return agreeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.agree_date
     *
     * @param agreeDate the value for HSDB04_03.agree_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAgreeDate(Date agreeDate) {
        this.agreeDate = agreeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.patient_name
     *
     * @return the value of HSDB04_03.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.patient_name
     *
     * @param patientName the value for HSDB04_03.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.economic
     *
     * @return the value of HSDB04_03.economic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEconomic() {
        return economic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.economic
     *
     * @param economic the value for HSDB04_03.economic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEconomic(String economic) {
        this.economic = economic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.status
     *
     * @return the value of HSDB04_03.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.status
     *
     * @param status the value for HSDB04_03.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.author_code
     *
     * @return the value of HSDB04_03.author_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.author_code
     *
     * @param authorCode the value for HSDB04_03.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.template_oid
     *
     * @return the value of HSDB04_03.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.template_oid
     *
     * @param templateOid the value for HSDB04_03.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.in_times
     *
     * @return the value of HSDB04_03.in_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInTimes() {
        return inTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.in_times
     *
     * @param inTimes the value for HSDB04_03.in_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInTimes(String inTimes) {
        this.inTimes = inTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.custodian_code
     *
     * @return the value of HSDB04_03.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.custodian_code
     *
     * @param custodianCode the value for HSDB04_03.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.agree_mark
     *
     * @return the value of HSDB04_03.agree_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getAgreeMark() {
        return agreeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.agree_mark
     *
     * @param agreeMark the value for HSDB04_03.agree_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAgreeMark(Boolean agreeMark) {
        this.agreeMark = agreeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.xds_version
     *
     * @return the value of HSDB04_03.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.xds_version
     *
     * @param xdsVersion the value for HSDB04_03.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.lock_happen
     *
     * @return the value of HSDB04_03.lock_happen
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getLockHappen() {
        return lockHappen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.lock_happen
     *
     * @param lockHappen the value for HSDB04_03.lock_happen
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLockHappen(String lockHappen) {
        this.lockHappen = lockHappen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.pk
     *
     * @return the value of HSDB04_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.pk
     *
     * @param pk the value for HSDB04_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.write_time
     *
     * @return the value of HSDB04_03.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.write_time
     *
     * @param writeTime the value for HSDB04_03.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.treatment
     *
     * @return the value of HSDB04_03.treatment
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTreatment() {
        return treatment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.treatment
     *
     * @param treatment the value for HSDB04_03.treatment
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.diagmi_name
     *
     * @return the value of HSDB04_03.diagmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDiagmiName() {
        return diagmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.diagmi_name
     *
     * @param diagmiName the value for HSDB04_03.diagmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDiagmiName(String diagmiName) {
        this.diagmiName = diagmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.mi_name
     *
     * @return the value of HSDB04_03.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.mi_name
     *
     * @param miName the value for HSDB04_03.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.class_name
     *
     * @return the value of HSDB04_03.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.class_name
     *
     * @param className the value for HSDB04_03.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.effect_times
     *
     * @return the value of HSDB04_03.effect_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEffectTimes() {
        return effectTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.effect_times
     *
     * @param effectTimes the value for HSDB04_03.effect_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectTimes(String effectTimes) {
        this.effectTimes = effectTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.birth
     *
     * @return the value of HSDB04_03.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.birth
     *
     * @param birth the value for HSDB04_03.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.mental_name
     *
     * @return the value of HSDB04_03.mental_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMentalName() {
        return mentalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.mental_name
     *
     * @param mentalName the value for HSDB04_03.mental_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMentalName(String mentalName) {
        this.mentalName = mentalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.domain_id
     *
     * @return the value of HSDB04_03.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.domain_id
     *
     * @param domainId the value for HSDB04_03.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.signer_name
     *
     * @return the value of HSDB04_03.signer_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSignerName() {
        return signerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.signer_name
     *
     * @param signerName the value for HSDB04_03.signer_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSignerName(String signerName) {
        this.signerName = signerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.xds_name
     *
     * @return the value of HSDB04_03.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.xds_name
     *
     * @param xdsName the value for HSDB04_03.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.effect_code
     *
     * @return the value of HSDB04_03.effect_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEffectCode() {
        return effectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.effect_code
     *
     * @param effectCode the value for HSDB04_03.effect_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectCode(String effectCode) {
        this.effectCode = effectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_03.custodian_addr
     *
     * @return the value of HSDB04_03.custodian_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_03.custodian_addr
     *
     * @param custodianAddr the value for HSDB04_03.custodian_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }
}