package com.ylz.hf.bean;
import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("HSDB04_04")
public class Hsdb0404 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.features_ecode
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String featuresEcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.cm_category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String cmCategoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String houseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.spirit_symptom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String spiritSymptom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String telecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.fu_result_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fuResultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.features_tcode
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String featuresTcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.inspection_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inspectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.danager
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String danager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.lock_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String lockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.diet_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String dietTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.check_item
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String checkItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.referral_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean referralMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.sick_effect
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sickEffect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.visit_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean visitMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.sleep_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sleepCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.check_sign
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean checkSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.spirit_measure
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String spiritMeasure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.features_ename
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String featuresEname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.cm_category
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String cmCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String streetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.sk_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String skCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.fu_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fuResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.features_tname
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String featuresTname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.check_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String checkResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.spirit_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String spiritCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.lock_happen
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String lockHappen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ostalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.diet_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String dietType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.inspection_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inspectionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String referralReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.danager_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String danagerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.effect_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String effectTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.sleep
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sleep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.inspection_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date inspectionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.measure_guide
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String measureGuide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.effect_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String effectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String township;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.fu_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date fuDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.sk_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String skResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_04.spirit_measure_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String spiritMeasureCode;


    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.empi
     *
     * @param empi the value for HSDB04_04.empi
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.features_ecode
     *
     * @return the value of HSDB04_04.features_ecode
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFeaturesEcode() {
        return featuresEcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.features_ecode
     *
     * @param featuresEcode the value for HSDB04_04.features_ecode
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFeaturesEcode(String featuresEcode) {
        this.featuresEcode = featuresEcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.cm_category_code
     *
     * @return the value of HSDB04_04.cm_category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCmCategoryCode() {
        return cmCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.cm_category_code
     *
     * @param cmCategoryCode the value for HSDB04_04.cm_category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCmCategoryCode(String cmCategoryCode) {
        this.cmCategoryCode = cmCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.house_number
     *
     * @return the value of HSDB04_04.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.house_number
     *
     * @param houseNumber the value for HSDB04_04.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.custodian_name
     *
     * @return the value of HSDB04_04.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.custodian_name
     *
     * @param custodianName the value for HSDB04_04.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.inmi_code
     *
     * @return the value of HSDB04_04.inmi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiCode() {
        return inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.inmi_code
     *
     * @param inmiCode the value for HSDB04_04.inmi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiCode(String inmiCode) {
        this.inmiCode = inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.spirit_symptom
     *
     * @return the value of HSDB04_04.spirit_symptom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSpiritSymptom() {
        return spiritSymptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.spirit_symptom
     *
     * @param spiritSymptom the value for HSDB04_04.spirit_symptom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSpiritSymptom(String spiritSymptom) {
        this.spiritSymptom = spiritSymptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.template_oid
     *
     * @return the value of HSDB04_04.template_oid
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.template_oid
     *
     * @param templateOid the value for HSDB04_04.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.telecom
     *
     * @return the value of HSDB04_04.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTelecom() {
        return telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.telecom
     *
     * @param telecom the value for HSDB04_04.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTelecom(String telecom) {
        this.telecom = telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.fu_result_code
     *
     * @return the value of HSDB04_04.fu_result_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFuResultCode() {
        return fuResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.fu_result_code
     *
     * @param fuResultCode the value for HSDB04_04.fu_result_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuResultCode(String fuResultCode) {
        this.fuResultCode = fuResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.upload_time
     *
     * @return the value of HSDB04_04.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.upload_time
     *
     * @param uploadTime the value for HSDB04_04.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.features_tcode
     *
     * @return the value of HSDB04_04.features_tcode
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFeaturesTcode() {
        return featuresTcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.features_tcode
     *
     * @param featuresTcode the value for HSDB04_04.features_tcode
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFeaturesTcode(String featuresTcode) {
        this.featuresTcode = featuresTcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.inspection_name
     *
     * @return the value of HSDB04_04.inspection_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInspectionName() {
        return inspectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.inspection_name
     *
     * @param inspectionName the value for HSDB04_04.inspection_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInspectionName(String inspectionName) {
        this.inspectionName = inspectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.xds_version
     *
     * @return the value of HSDB04_04.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.xds_version
     *
     * @param xdsVersion the value for HSDB04_04.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.mi_addr
     *
     * @return the value of HSDB04_04.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.mi_addr
     *
     * @param miAddr the value for HSDB04_04.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.indept_code
     *
     * @return the value of HSDB04_04.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIndeptCode() {
        return indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.indept_code
     *
     * @param indeptCode the value for HSDB04_04.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptCode(String indeptCode) {
        this.indeptCode = indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.danager
     *
     * @return the value of HSDB04_04.danager
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDanager() {
        return danager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.danager
     *
     * @param danager the value for HSDB04_04.danager
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDanager(String danager) {
        this.danager = danager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.lock_code
     *
     * @return the value of HSDB04_04.lock_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getLockCode() {
        return lockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.lock_code
     *
     * @param lockCode the value for HSDB04_04.lock_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLockCode(String lockCode) {
        this.lockCode = lockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.province
     *
     * @return the value of HSDB04_04.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.province
     *
     * @param province the value for HSDB04_04.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.diet_type_code
     *
     * @return the value of HSDB04_04.diet_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDietTypeCode() {
        return dietTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.diet_type_code
     *
     * @param dietTypeCode the value for HSDB04_04.diet_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDietTypeCode(String dietTypeCode) {
        this.dietTypeCode = dietTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.check_item
     *
     * @return the value of HSDB04_04.check_item
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCheckItem() {
        return checkItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.check_item
     *
     * @param checkItem the value for HSDB04_04.check_item
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCheckItem(String checkItem) {
        this.checkItem = checkItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.class_name
     *
     * @return the value of HSDB04_04.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.class_name
     *
     * @param className the value for HSDB04_04.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.mi_code
     *
     * @return the value of HSDB04_04.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.mi_code
     *
     * @param miCode the value for HSDB04_04.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.referral_mark
     *
     * @return the value of HSDB04_04.referral_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getReferralMark() {
        return referralMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.referral_mark
     *
     * @param referralMark the value for HSDB04_04.referral_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralMark(Boolean referralMark) {
        this.referralMark = referralMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.sick_effect
     *
     * @return the value of HSDB04_04.sick_effect
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSickEffect() {
        return sickEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.sick_effect
     *
     * @param sickEffect the value for HSDB04_04.sick_effect
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSickEffect(String sickEffect) {
        this.sickEffect = sickEffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.county
     *
     * @return the value of HSDB04_04.county
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.county
     *
     * @param county the value for HSDB04_04.county
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.visit_mark
     *
     * @return the value of HSDB04_04.visit_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getVisitMark() {
        return visitMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.visit_mark
     *
     * @param visitMark the value for HSDB04_04.visit_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setVisitMark(Boolean visitMark) {
        this.visitMark = visitMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.sleep_code
     *
     * @return the value of HSDB04_04.sleep_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSleepCode() {
        return sleepCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.sleep_code
     *
     * @param sleepCode the value for HSDB04_04.sleep_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSleepCode(String sleepCode) {
        this.sleepCode = sleepCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.check_sign
     *
     * @return the value of HSDB04_04.check_sign
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getCheckSign() {
        return checkSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.check_sign
     *
     * @param checkSign the value for HSDB04_04.check_sign
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCheckSign(Boolean checkSign) {
        this.checkSign = checkSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.xds_name
     *
     * @return the value of HSDB04_04.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.xds_name
     *
     * @param xdsName the value for HSDB04_04.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.author_code
     *
     * @return the value of HSDB04_04.author_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.author_code
     *
     * @param authorCode the value for HSDB04_04.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.spirit_measure
     *
     * @return the value of HSDB04_04.spirit_measure
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSpiritMeasure() {
        return spiritMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.spirit_measure
     *
     * @param spiritMeasure the value for HSDB04_04.spirit_measure
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSpiritMeasure(String spiritMeasure) {
        this.spiritMeasure = spiritMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.encounter_id
     *
     * @return the value of HSDB04_04.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.encounter_id
     *
     * @param encounterId the value for HSDB04_04.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.features_ename
     *
     * @return the value of HSDB04_04.features_ename
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFeaturesEname() {
        return featuresEname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.features_ename
     *
     * @param featuresEname the value for HSDB04_04.features_ename
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFeaturesEname(String featuresEname) {
        this.featuresEname = featuresEname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.cm_category
     *
     * @return the value of HSDB04_04.cm_category
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCmCategory() {
        return cmCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.cm_category
     *
     * @param cmCategory the value for HSDB04_04.cm_category
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCmCategory(String cmCategory) {
        this.cmCategory = cmCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.street_name
     *
     * @return the value of HSDB04_04.street_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.street_name
     *
     * @param streetName the value for HSDB04_04.street_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.custodian_telecom
     *
     * @return the value of HSDB04_04.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.custodian_telecom
     *
     * @param custodianTelecom the value for HSDB04_04.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.inmi_name
     *
     * @return the value of HSDB04_04.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiName() {
        return inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.inmi_name
     *
     * @param inmiName the value for HSDB04_04.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiName(String inmiName) {
        this.inmiName = inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.sk_code
     *
     * @return the value of HSDB04_04.sk_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSkCode() {
        return skCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.sk_code
     *
     * @param skCode the value for HSDB04_04.sk_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSkCode(String skCode) {
        this.skCode = skCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.unique_id
     *
     * @return the value of HSDB04_04.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.unique_id
     *
     * @param uniqueId the value for HSDB04_04.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.patient_name
     *
     * @return the value of HSDB04_04.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.patient_name
     *
     * @param patientName the value for HSDB04_04.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.fu_result
     *
     * @return the value of HSDB04_04.fu_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFuResult() {
        return fuResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.fu_result
     *
     * @param fuResult the value for HSDB04_04.fu_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuResult(String fuResult) {
        this.fuResult = fuResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.status
     *
     * @return the value of HSDB04_04.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.status
     *
     * @param status the value for HSDB04_04.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.features_tname
     *
     * @return the value of HSDB04_04.features_tname
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFeaturesTname() {
        return featuresTname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.features_tname
     *
     * @param featuresTname the value for HSDB04_04.features_tname
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFeaturesTname(String featuresTname) {
        this.featuresTname = featuresTname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.check_result
     *
     * @return the value of HSDB04_04.check_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.check_result
     *
     * @param checkResult the value for HSDB04_04.check_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.health_no
     *
     * @return the value of HSDB04_04.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthNo() {
        return healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.health_no
     *
     * @param healthNo the value for HSDB04_04.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthNo(String healthNo) {
        this.healthNo = healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.custodian_code
     *
     * @return the value of HSDB04_04.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.custodian_code
     *
     * @param custodianCode the value for HSDB04_04.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.indept_name
     *
     * @return the value of HSDB04_04.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIndeptName() {
        return indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.indept_name
     *
     * @param indeptName the value for HSDB04_04.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptName(String indeptName) {
        this.indeptName = indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.spirit_code
     *
     * @return the value of HSDB04_04.spirit_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSpiritCode() {
        return spiritCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.spirit_code
     *
     * @param spiritCode the value for HSDB04_04.spirit_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSpiritCode(String spiritCode) {
        this.spiritCode = spiritCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.lock_happen
     *
     * @return the value of HSDB04_04.lock_happen
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getLockHappen() {
        return lockHappen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.lock_happen
     *
     * @param lockHappen the value for HSDB04_04.lock_happen
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLockHappen(String lockHappen) {
        this.lockHappen = lockHappen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.register_model
     *
     * @return the value of HSDB04_04.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.register_model
     *
     * @param registerModel the value for HSDB04_04.register_model
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.ostal_code
     *
     * @return the value of HSDB04_04.ostal_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOstalCode() {
        return ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.ostal_code
     *
     * @param ostalCode the value for HSDB04_04.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOstalCode(String ostalCode) {
        this.ostalCode = ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.pk
     *
     * @return the value of HSDB04_04.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.pk
     *
     * @param pk the value for HSDB04_04.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.diet_type
     *
     * @return the value of HSDB04_04.diet_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDietType() {
        return dietType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.diet_type
     *
     * @param dietType the value for HSDB04_04.diet_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDietType(String dietType) {
        this.dietType = dietType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.inspection_code
     *
     * @return the value of HSDB04_04.inspection_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInspectionCode() {
        return inspectionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.inspection_code
     *
     * @param inspectionCode the value for HSDB04_04.inspection_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInspectionCode(String inspectionCode) {
        this.inspectionCode = inspectionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.class_code
     *
     * @return the value of HSDB04_04.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.class_code
     *
     * @param classCode the value for HSDB04_04.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.mi_name
     *
     * @return the value of HSDB04_04.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.mi_name
     *
     * @param miName the value for HSDB04_04.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.referral_reason
     *
     * @return the value of HSDB04_04.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getReferralReason() {
        return referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.referral_reason
     *
     * @param referralReason the value for HSDB04_04.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralReason(String referralReason) {
        this.referralReason = referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.danager_code
     *
     * @return the value of HSDB04_04.danager_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDanagerCode() {
        return danagerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.danager_code
     *
     * @param danagerCode the value for HSDB04_04.danager_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDanagerCode(String danagerCode) {
        this.danagerCode = danagerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.effect_times
     *
     * @return the value of HSDB04_04.effect_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEffectTimes() {
        return effectTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.effect_times
     *
     * @param effectTimes the value for HSDB04_04.effect_times
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectTimes(String effectTimes) {
        this.effectTimes = effectTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.city
     *
     * @return the value of HSDB04_04.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.city
     *
     * @param city the value for HSDB04_04.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.sleep
     *
     * @return the value of HSDB04_04.sleep
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSleep() {
        return sleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.sleep
     *
     * @param sleep the value for HSDB04_04.sleep
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSleep(String sleep) {
        this.sleep = sleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.inspection_date
     *
     * @return the value of HSDB04_04.inspection_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getInspectionDate() {
        return inspectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.inspection_date
     *
     * @param inspectionDate the value for HSDB04_04.inspection_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInspectionDate(Date inspectionDate) {
        this.inspectionDate = inspectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.effective_time
     *
     * @return the value of HSDB04_04.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.effective_time
     *
     * @param effectiveTime the value for HSDB04_04.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.author_name
     *
     * @return the value of HSDB04_04.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.author_name
     *
     * @param authorName the value for HSDB04_04.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.measure_guide
     *
     * @return the value of HSDB04_04.measure_guide
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMeasureGuide() {
        return measureGuide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.measure_guide
     *
     * @param measureGuide the value for HSDB04_04.measure_guide
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMeasureGuide(String measureGuide) {
        this.measureGuide = measureGuide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.domain_id
     *
     * @return the value of HSDB04_04.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.domain_id
     *
     * @param domainId the value for HSDB04_04.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.effect_code
     *
     * @return the value of HSDB04_04.effect_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEffectCode() {
        return effectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.effect_code
     *
     * @param effectCode the value for HSDB04_04.effect_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectCode(String effectCode) {
        this.effectCode = effectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.township
     *
     * @return the value of HSDB04_04.township
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTownship() {
        return township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.township
     *
     * @param township the value for HSDB04_04.township
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTownship(String township) {
        this.township = township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.custodian_addr
     *
     * @return the value of HSDB04_04.custodian_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.custodian_addr
     *
     * @param custodianAddr the value for HSDB04_04.custodian_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.fu_date
     *
     * @return the value of HSDB04_04.fu_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getFuDate() {
        return fuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.fu_date
     *
     * @param fuDate the value for HSDB04_04.fu_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuDate(Date fuDate) {
        this.fuDate = fuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.sk_result
     *
     * @return the value of HSDB04_04.sk_result
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSkResult() {
        return skResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.sk_result
     *
     * @param skResult the value for HSDB04_04.sk_result
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSkResult(String skResult) {
        this.skResult = skResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.xds_type
     *
     * @return the value of HSDB04_04.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.xds_type
     *
     * @param xdsType the value for HSDB04_04.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.write_time
     *
     * @return the value of HSDB04_04.write_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.write_time
     *
     * @param writeTime the value for HSDB04_04.write_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_04.spirit_measure_code
     *
     * @return the value of HSDB04_04.spirit_measure_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSpiritMeasureCode() {
        return spiritMeasureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_04.spirit_measure_code
     *
     * @param spiritMeasureCode the value for HSDB04_04.spirit_measure_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSpiritMeasureCode(String spiritMeasureCode) {
        this.spiritMeasureCode = spiritMeasureCode;
    }
}