package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("HSDB02_03")
public class Hsdb0203 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.heal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String referralReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.temperature
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.palace_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean palaceMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.systolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String systolic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.fu_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date fuDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.lochia_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean lochiaMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.guide_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String guideDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.health_situation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.right_check_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String rightCheckCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.heal_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.left_check_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String leftCheckCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.palace_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String palaceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.referral_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean referralMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.diastolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String diastolic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.visited_place
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String visitedPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.lochia
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String lochia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.mental_situation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mentalSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.right_check
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String rightCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.guide_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean guideMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB02_03.left_check
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String leftCheck;


    public String getHealCode() {
        return healCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.heal_code
     *
     * @param healCode the value for HSDB02_03.heal_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealCode(String healCode) {
        this.healCode = healCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.unique_id
     *
     * @return the value of HSDB02_03.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.unique_id
     *
     * @param uniqueId the value for HSDB02_03.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.custodian_name
     *
     * @return the value of HSDB02_03.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.custodian_name
     *
     * @param custodianName the value for HSDB02_03.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.referral_reason
     *
     * @return the value of HSDB02_03.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getReferralReason() {
        return referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.referral_reason
     *
     * @param referralReason the value for HSDB02_03.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralReason(String referralReason) {
        this.referralReason = referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.status
     *
     * @return the value of HSDB02_03.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.status
     *
     * @param status the value for HSDB02_03.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.health_no
     *
     * @return the value of HSDB02_03.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthNo() {
        return healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.health_no
     *
     * @param healthNo the value for HSDB02_03.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthNo(String healthNo) {
        this.healthNo = healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.temperature
     *
     * @return the value of HSDB02_03.temperature
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.temperature
     *
     * @param temperature the value for HSDB02_03.temperature
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemperature(Float temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.register_model
     *
     * @return the value of HSDB02_03.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.register_model
     *
     * @param registerModel the value for HSDB02_03.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.mi_addr
     *
     * @return the value of HSDB02_03.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.mi_addr
     *
     * @param miAddr the value for HSDB02_03.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.palace_mark
     *
     * @return the value of HSDB02_03.palace_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getPalaceMark() {
        return palaceMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.palace_mark
     *
     * @param palaceMark the value for HSDB02_03.palace_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPalaceMark(Boolean palaceMark) {
        this.palaceMark = palaceMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.pk
     *
     * @return the value of HSDB02_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.pk
     *
     * @param pk the value for HSDB02_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.class_code
     *
     * @return the value of HSDB02_03.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.class_code
     *
     * @param classCode the value for HSDB02_03.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.systolic
     *
     * @return the value of HSDB02_03.systolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSystolic() {
        return systolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.systolic
     *
     * @param systolic the value for HSDB02_03.systolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSystolic(String systolic) {
        this.systolic = systolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.fu_date
     *
     * @return the value of HSDB02_03.fu_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getFuDate() {
        return fuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.fu_date
     *
     * @param fuDate the value for HSDB02_03.fu_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuDate(Date fuDate) {
        this.fuDate = fuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.mi_code
     *
     * @return the value of HSDB02_03.mi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.mi_code
     *
     * @param miCode the value for HSDB02_03.mi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.lochia_mark
     *
     * @return the value of HSDB02_03.lochia_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getLochiaMark() {
        return lochiaMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.lochia_mark
     *
     * @param lochiaMark the value for HSDB02_03.lochia_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLochiaMark(Boolean lochiaMark) {
        this.lochiaMark = lochiaMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.guide_desc
     *
     * @return the value of HSDB02_03.guide_desc
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getGuideDesc() {
        return guideDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.guide_desc
     *
     * @param guideDesc the value for HSDB02_03.guide_desc
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setGuideDesc(String guideDesc) {
        this.guideDesc = guideDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.effective_time
     *
     * @return the value of HSDB02_03.effective_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.effective_time
     *
     * @param effectiveTime the value for HSDB02_03.effective_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.health_situation
     *
     * @return the value of HSDB02_03.health_situation
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthSituation() {
        return healthSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.health_situation
     *
     * @param healthSituation the value for HSDB02_03.health_situation
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthSituation(String healthSituation) {
        this.healthSituation = healthSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.inmi_code
     *
     * @return the value of HSDB02_03.inmi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiCode() {
        return inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.inmi_code
     *
     * @param inmiCode the value for HSDB02_03.inmi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiCode(String inmiCode) {
        this.inmiCode = inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.domain_id
     *
     * @return the value of HSDB02_03.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.domain_id
     *
     * @param domainId the value for HSDB02_03.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.author_code
     *
     * @return the value of HSDB02_03.author_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.author_code
     *
     * @param authorCode the value for HSDB02_03.author_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.right_check_code
     *
     * @return the value of HSDB02_03.right_check_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRightCheckCode() {
        return rightCheckCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.right_check_code
     *
     * @param rightCheckCode the value for HSDB02_03.right_check_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRightCheckCode(String rightCheckCode) {
        this.rightCheckCode = rightCheckCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.heal_name
     *
     * @return the value of HSDB02_03.heal_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealName() {
        return healName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.heal_name
     *
     * @param healName the value for HSDB02_03.heal_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealName(String healName) {
        this.healName = healName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.xds_type
     *
     * @return the value of HSDB02_03.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.xds_type
     *
     * @param xdsType the value for HSDB02_03.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.custodian_telecom
     *
     * @return the value of HSDB02_03.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.custodian_telecom
     *
     * @param custodianTelecom the value for HSDB02_03.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.indept_code
     *
     * @return the value of HSDB02_03.indept_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIndeptCode() {
        return indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.indept_code
     *
     * @param indeptCode the value for HSDB02_03.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptCode(String indeptCode) {
        this.indeptCode = indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.empi
     *
     * @return the value of HSDB02_03.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.empi
     *
     * @param empi the value for HSDB02_03.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.patient_name
     *
     * @return the value of HSDB02_03.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.patient_name
     *
     * @param patientName the value for HSDB02_03.patient_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.left_check_code
     *
     * @return the value of HSDB02_03.left_check_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getLeftCheckCode() {
        return leftCheckCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.left_check_code
     *
     * @param leftCheckCode the value for HSDB02_03.left_check_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLeftCheckCode(String leftCheckCode) {
        this.leftCheckCode = leftCheckCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.template_oid
     *
     * @return the value of HSDB02_03.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.template_oid
     *
     * @param templateOid the value for HSDB02_03.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.custodian_code
     *
     * @return the value of HSDB02_03.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.custodian_code
     *
     * @param custodianCode the value for HSDB02_03.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.palace_desc
     *
     * @return the value of HSDB02_03.palace_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPalaceDesc() {
        return palaceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.palace_desc
     *
     * @param palaceDesc the value for HSDB02_03.palace_desc
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPalaceDesc(String palaceDesc) {
        this.palaceDesc = palaceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.referral_mark
     *
     * @return the value of HSDB02_03.referral_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getReferralMark() {
        return referralMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.referral_mark
     *
     * @param referralMark the value for HSDB02_03.referral_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralMark(Boolean referralMark) {
        this.referralMark = referralMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.upload_time
     *
     * @return the value of HSDB02_03.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.upload_time
     *
     * @param uploadTime the value for HSDB02_03.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.xds_version
     *
     * @return the value of HSDB02_03.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.xds_version
     *
     * @param xdsVersion the value for HSDB02_03.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.diastolic
     *
     * @return the value of HSDB02_03.diastolic
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDiastolic() {
        return diastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.diastolic
     *
     * @param diastolic the value for HSDB02_03.diastolic
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDiastolic(String diastolic) {
        this.diastolic = diastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.visited_place
     *
     * @return the value of HSDB02_03.visited_place
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getVisitedPlace() {
        return visitedPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.visited_place
     *
     * @param visitedPlace the value for HSDB02_03.visited_place
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setVisitedPlace(String visitedPlace) {
        this.visitedPlace = visitedPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.mi_name
     *
     * @return the value of HSDB02_03.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.mi_name
     *
     * @param miName the value for HSDB02_03.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.lochia
     *
     * @return the value of HSDB02_03.lochia
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getLochia() {
        return lochia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.lochia
     *
     * @param lochia the value for HSDB02_03.lochia
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLochia(String lochia) {
        this.lochia = lochia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.class_name
     *
     * @return the value of HSDB02_03.class_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.class_name
     *
     * @param className the value for HSDB02_03.class_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.mental_situation
     *
     * @return the value of HSDB02_03.mental_situation
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMentalSituation() {
        return mentalSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.mental_situation
     *
     * @param mentalSituation the value for HSDB02_03.mental_situation
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMentalSituation(String mentalSituation) {
        this.mentalSituation = mentalSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.inmi_name
     *
     * @return the value of HSDB02_03.inmi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiName() {
        return inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.inmi_name
     *
     * @param inmiName the value for HSDB02_03.inmi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiName(String inmiName) {
        this.inmiName = inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.author_name
     *
     * @return the value of HSDB02_03.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.author_name
     *
     * @param authorName the value for HSDB02_03.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.right_check
     *
     * @return the value of HSDB02_03.right_check
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRightCheck() {
        return rightCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.right_check
     *
     * @param rightCheck the value for HSDB02_03.right_check
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRightCheck(String rightCheck) {
        this.rightCheck = rightCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.guide_mark
     *
     * @return the value of HSDB02_03.guide_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getGuideMark() {
        return guideMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.guide_mark
     *
     * @param guideMark the value for HSDB02_03.guide_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setGuideMark(Boolean guideMark) {
        this.guideMark = guideMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.xds_name
     *
     * @return the value of HSDB02_03.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.xds_name
     *
     * @param xdsName the value for HSDB02_03.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.custodian_addr
     *
     * @return the value of HSDB02_03.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.custodian_addr
     *
     * @param custodianAddr the value for HSDB02_03.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.indept_name
     *
     * @return the value of HSDB02_03.indept_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIndeptName() {
        return indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.indept_name
     *
     * @param indeptName the value for HSDB02_03.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptName(String indeptName) {
        this.indeptName = indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.encounter_id
     *
     * @return the value of HSDB02_03.encounter_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.encounter_id
     *
     * @param encounterId the value for HSDB02_03.encounter_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.write_time
     *
     * @return the value of HSDB02_03.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.write_time
     *
     * @param writeTime the value for HSDB02_03.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB02_03.left_check
     *
     * @return the value of HSDB02_03.left_check
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getLeftCheck() {
        return leftCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB02_03.left_check
     *
     * @param leftCheck the value for HSDB02_03.left_check
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLeftCheck(String leftCheck) {
        this.leftCheck = leftCheck;
    }
}