package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("HSDB03_01")
public class Hsdb0301 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.effective_time
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.township
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String township;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.census_county
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String censusCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.vaccine_history
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String vaccineHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.xds_type
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.sex_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.mi_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.domain_id
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.house_number
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String houseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.census_street_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String censusStreetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.out_date
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private Date outDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.template_oid
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.telecom
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String telecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.author_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.empi
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.xds_version
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String custodianAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.province
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.write_time
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.upload_time
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.class_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.abnormal_date
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private Date abnormalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.county
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.census_city
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String censusCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.taboo
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String taboo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.xds_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.sex
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.street_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String streetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.census_township
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String censusTownship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.out_reason
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String outReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.unique_id
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.patient_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.mi_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.health_no
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String healthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.census_house_number
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String censusHouseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.in_date
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private Date inDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.register_model
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String ostalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.author_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.status
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.class_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.process_result
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String processResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.city
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.census_province
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String censusProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.pk
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_01.infectious_history
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    private String infectiousHistory;


    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.effective_time
     *
     * @param effectiveTime the value for HSDB03_01.effective_time
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.custodian_code
     *
     * @return the value of HSDB03_01.custodian_code
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.custodian_code
     *
     * @param custodianCode the value for HSDB03_01.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.township
     *
     * @return the value of HSDB03_01.township
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getTownship() {
        return township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.township
     *
     * @param township the value for HSDB03_01.township
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setTownship(String township) {
        this.township = township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.census_county
     *
     * @return the value of HSDB03_01.census_county
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCensusCounty() {
        return censusCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.census_county
     *
     * @param censusCounty the value for HSDB03_01.census_county
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCensusCounty(String censusCounty) {
        this.censusCounty = censusCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.vaccine_history
     *
     * @return the value of HSDB03_01.vaccine_history
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getVaccineHistory() {
        return vaccineHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.vaccine_history
     *
     * @param vaccineHistory the value for HSDB03_01.vaccine_history
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setVaccineHistory(String vaccineHistory) {
        this.vaccineHistory = vaccineHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.xds_type
     *
     * @return the value of HSDB03_01.xds_type
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.xds_type
     *
     * @param xdsType the value for HSDB03_01.xds_type
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.sex_code
     *
     * @return the value of HSDB03_01.sex_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.sex_code
     *
     * @param sexCode the value for HSDB03_01.sex_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.mi_name
     *
     * @return the value of HSDB03_01.mi_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.mi_name
     *
     * @param miName the value for HSDB03_01.mi_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.domain_id
     *
     * @return the value of HSDB03_01.domain_id
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.domain_id
     *
     * @param domainId the value for HSDB03_01.domain_id
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.house_number
     *
     * @return the value of HSDB03_01.house_number
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.house_number
     *
     * @param houseNumber the value for HSDB03_01.house_number
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.census_street_name
     *
     * @return the value of HSDB03_01.census_street_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCensusStreetName() {
        return censusStreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.census_street_name
     *
     * @param censusStreetName the value for HSDB03_01.census_street_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCensusStreetName(String censusStreetName) {
        this.censusStreetName = censusStreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.out_date
     *
     * @return the value of HSDB03_01.out_date
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public Date getOutDate() {
        return outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.out_date
     *
     * @param outDate the value for HSDB03_01.out_date
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.template_oid
     *
     * @return the value of HSDB03_01.template_oid
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.template_oid
     *
     * @param templateOid the value for HSDB03_01.template_oid
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.telecom
     *
     * @return the value of HSDB03_01.telecom
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getTelecom() {
        return telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.telecom
     *
     * @param telecom the value for HSDB03_01.telecom
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setTelecom(String telecom) {
        this.telecom = telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.author_name
     *
     * @return the value of HSDB03_01.author_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.author_name
     *
     * @param authorName the value for HSDB03_01.author_name
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.empi
     *
     * @return the value of HSDB03_01.empi
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.empi
     *
     * @param empi the value for HSDB03_01.empi
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.xds_version
     *
     * @return the value of HSDB03_01.xds_version
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.xds_version
     *
     * @param xdsVersion the value for HSDB03_01.xds_version
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.custodian_addr
     *
     * @return the value of HSDB03_01.custodian_addr
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.custodian_addr
     *
     * @param custodianAddr the value for HSDB03_01.custodian_addr
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.province
     *
     * @return the value of HSDB03_01.province
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.province
     *
     * @param province the value for HSDB03_01.province
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.write_time
     *
     * @return the value of HSDB03_01.write_time
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.write_time
     *
     * @param writeTime the value for HSDB03_01.write_time
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.upload_time
     *
     * @return the value of HSDB03_01.upload_time
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.upload_time
     *
     * @param uploadTime the value for HSDB03_01.upload_time
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.class_name
     *
     * @return the value of HSDB03_01.class_name
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.class_name
     *
     * @param className the value for HSDB03_01.class_name
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.custodian_name
     *
     * @return the value of HSDB03_01.custodian_name
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.custodian_name
     *
     * @param custodianName the value for HSDB03_01.custodian_name
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.abnormal_date
     *
     * @return the value of HSDB03_01.abnormal_date
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public Date getAbnormalDate() {
        return abnormalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.abnormal_date
     *
     * @param abnormalDate the value for HSDB03_01.abnormal_date
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setAbnormalDate(Date abnormalDate) {
        this.abnormalDate = abnormalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.county
     *
     * @return the value of HSDB03_01.county
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.county
     *
     * @param county the value for HSDB03_01.county
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.census_city
     *
     * @return the value of HSDB03_01.census_city
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCensusCity() {
        return censusCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.census_city
     *
     * @param censusCity the value for HSDB03_01.census_city
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCensusCity(String censusCity) {
        this.censusCity = censusCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.taboo
     *
     * @return the value of HSDB03_01.taboo
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getTaboo() {
        return taboo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.taboo
     *
     * @param taboo the value for HSDB03_01.taboo
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setTaboo(String taboo) {
        this.taboo = taboo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.xds_name
     *
     * @return the value of HSDB03_01.xds_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.xds_name
     *
     * @param xdsName the value for HSDB03_01.xds_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.sex
     *
     * @return the value of HSDB03_01.sex
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.sex
     *
     * @param sex the value for HSDB03_01.sex
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.mi_addr
     *
     * @return the value of HSDB03_01.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.mi_addr
     *
     * @param miAddr the value for HSDB03_01.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.street_name
     *
     * @return the value of HSDB03_01.street_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.street_name
     *
     * @param streetName the value for HSDB03_01.street_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.census_township
     *
     * @return the value of HSDB03_01.census_township
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCensusTownship() {
        return censusTownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.census_township
     *
     * @param censusTownship the value for HSDB03_01.census_township
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCensusTownship(String censusTownship) {
        this.censusTownship = censusTownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.out_reason
     *
     * @return the value of HSDB03_01.out_reason
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getOutReason() {
        return outReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.out_reason
     *
     * @param outReason the value for HSDB03_01.out_reason
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setOutReason(String outReason) {
        this.outReason = outReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.unique_id
     *
     * @return the value of HSDB03_01.unique_id
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.unique_id
     *
     * @param uniqueId the value for HSDB03_01.unique_id
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.patient_name
     *
     * @return the value of HSDB03_01.patient_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.patient_name
     *
     * @param patientName the value for HSDB03_01.patient_name
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.mi_code
     *
     * @return the value of HSDB03_01.mi_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.mi_code
     *
     * @param miCode the value for HSDB03_01.mi_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.encounter_id
     *
     * @return the value of HSDB03_01.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.encounter_id
     *
     * @param encounterId the value for HSDB03_01.encounter_id
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.health_no
     *
     * @return the value of HSDB03_01.health_no
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getHealthNo() {
        return healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.health_no
     *
     * @param healthNo the value for HSDB03_01.health_no
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setHealthNo(String healthNo) {
        this.healthNo = healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.census_house_number
     *
     * @return the value of HSDB03_01.census_house_number
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCensusHouseNumber() {
        return censusHouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.census_house_number
     *
     * @param censusHouseNumber the value for HSDB03_01.census_house_number
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCensusHouseNumber(String censusHouseNumber) {
        this.censusHouseNumber = censusHouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.in_date
     *
     * @return the value of HSDB03_01.in_date
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public Date getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.in_date
     *
     * @param inDate the value for HSDB03_01.in_date
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.register_model
     *
     * @return the value of HSDB03_01.register_model
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.register_model
     *
     * @param registerModel the value for HSDB03_01.register_model
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.ostal_code
     *
     * @return the value of HSDB03_01.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getOstalCode() {
        return ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.ostal_code
     *
     * @param ostalCode the value for HSDB03_01.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setOstalCode(String ostalCode) {
        this.ostalCode = ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.author_code
     *
     * @return the value of HSDB03_01.author_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.author_code
     *
     * @param authorCode the value for HSDB03_01.author_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.status
     *
     * @return the value of HSDB03_01.status
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.status
     *
     * @param status the value for HSDB03_01.status
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.class_code
     *
     * @return the value of HSDB03_01.class_code
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.class_code
     *
     * @param classCode the value for HSDB03_01.class_code
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.custodian_telecom
     *
     * @return the value of HSDB03_01.custodian_telecom
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.custodian_telecom
     *
     * @param custodianTelecom the value for HSDB03_01.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.process_result
     *
     * @return the value of HSDB03_01.process_result
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getProcessResult() {
        return processResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.process_result
     *
     * @param processResult the value for HSDB03_01.process_result
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setProcessResult(String processResult) {
        this.processResult = processResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.city
     *
     * @return the value of HSDB03_01.city
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.city
     *
     * @param city the value for HSDB03_01.city
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.census_province
     *
     * @return the value of HSDB03_01.census_province
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getCensusProvince() {
        return censusProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.census_province
     *
     * @param censusProvince the value for HSDB03_01.census_province
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setCensusProvince(String censusProvince) {
        this.censusProvince = censusProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.pk
     *
     * @return the value of HSDB03_01.pk
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.pk
     *
     * @param pk the value for HSDB03_01.pk
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_01.infectious_history
     *
     * @return the value of HSDB03_01.infectious_history
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public String getInfectiousHistory() {
        return infectiousHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_01.infectious_history
     *
     * @param infectiousHistory the value for HSDB03_01.infectious_history
     *
     * @mbggenerated Fri Apr 24 19:59:55 CST 2020
     */
    public void setInfectiousHistory(String infectiousHistory) {
        this.infectiousHistory = infectiousHistory;
    }
}