package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("HSDB01_01")
public class Hsdb0101 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mstreet_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mstreetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.methnic_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String methnicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.visa_agency
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String visaAgency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fidentify_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fidentifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fhouse_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fhouseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fguardian_birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date fguardianBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mnationality
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mnationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mostalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.signatory_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String signatoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.midentify_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String midentifyTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fprovince
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fnationality_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fnationalityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mcity
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fethnic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fethnic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fcounty
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fcounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.length
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mname
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mtownship
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mtownship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fethnic_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fethnicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.licensee_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String licenseeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fidentify_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fidentifyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fstreet_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fstreetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mhouse_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mhouseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fnationality
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fnationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mguardian_birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date mguardianBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.signatory_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String signatoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.midentify_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String midentifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fostalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mnationality_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mnationalityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mprovince
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.issue_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date issueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fidentify_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fidentifyTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fcity
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.height
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.fname
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.mcounty
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mcounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.methnic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String methnic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.prove_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String proveNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.ftownship
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ftownship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.gestat_week
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String gestatWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB01_01.midentify_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String midentifyNo;


    public String getMstreetName() {
        return mstreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mstreet_name
     *
     * @param mstreetName the value for HSDB01_01.mstreet_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMstreetName(String mstreetName) {
        this.mstreetName = mstreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.custodian_code
     *
     * @return the value of HSDB01_01.custodian_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.custodian_code
     *
     * @param custodianCode the value for HSDB01_01.custodian_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.methnic_code
     *
     * @return the value of HSDB01_01.methnic_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMethnicCode() {
        return methnicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.methnic_code
     *
     * @param methnicCode the value for HSDB01_01.methnic_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMethnicCode(String methnicCode) {
        this.methnicCode = methnicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.class_code
     *
     * @return the value of HSDB01_01.class_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.class_code
     *
     * @param classCode the value for HSDB01_01.class_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.county
     *
     * @return the value of HSDB01_01.county
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.county
     *
     * @param county the value for HSDB01_01.county
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.status
     *
     * @return the value of HSDB01_01.status
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.status
     *
     * @param status the value for HSDB01_01.status
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.visa_agency
     *
     * @return the value of HSDB01_01.visa_agency
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getVisaAgency() {
        return visaAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.visa_agency
     *
     * @param visaAgency the value for HSDB01_01.visa_agency
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setVisaAgency(String visaAgency) {
        this.visaAgency = visaAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fidentify_type
     *
     * @return the value of HSDB01_01.fidentify_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFidentifyType() {
        return fidentifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fidentify_type
     *
     * @param fidentifyType the value for HSDB01_01.fidentify_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFidentifyType(String fidentifyType) {
        this.fidentifyType = fidentifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fhouse_number
     *
     * @return the value of HSDB01_01.fhouse_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFhouseNumber() {
        return fhouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fhouse_number
     *
     * @param fhouseNumber the value for HSDB01_01.fhouse_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFhouseNumber(String fhouseNumber) {
        this.fhouseNumber = fhouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fguardian_birth
     *
     * @return the value of HSDB01_01.fguardian_birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getFguardianBirth() {
        return fguardianBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fguardian_birth
     *
     * @param fguardianBirth the value for HSDB01_01.fguardian_birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFguardianBirth(Date fguardianBirth) {
        this.fguardianBirth = fguardianBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mi_name
     *
     * @return the value of HSDB01_01.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mi_name
     *
     * @param miName the value for HSDB01_01.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mnationality
     *
     * @return the value of HSDB01_01.mnationality
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMnationality() {
        return mnationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mnationality
     *
     * @param mnationality the value for HSDB01_01.mnationality
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMnationality(String mnationality) {
        this.mnationality = mnationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.effective_time
     *
     * @return the value of HSDB01_01.effective_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.effective_time
     *
     * @param effectiveTime the value for HSDB01_01.effective_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mostal_code
     *
     * @return the value of HSDB01_01.mostal_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMostalCode() {
        return mostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mostal_code
     *
     * @param mostalCode the value for HSDB01_01.mostal_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMostalCode(String mostalCode) {
        this.mostalCode = mostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.pk
     *
     * @return the value of HSDB01_01.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.pk
     *
     * @param pk the value for HSDB01_01.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.signatory_code
     *
     * @return the value of HSDB01_01.signatory_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSignatoryCode() {
        return signatoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.signatory_code
     *
     * @param signatoryCode the value for HSDB01_01.signatory_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSignatoryCode(String signatoryCode) {
        this.signatoryCode = signatoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.midentify_type_code
     *
     * @return the value of HSDB01_01.midentify_type_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMidentifyTypeCode() {
        return midentifyTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.midentify_type_code
     *
     * @param midentifyTypeCode the value for HSDB01_01.midentify_type_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMidentifyTypeCode(String midentifyTypeCode) {
        this.midentifyTypeCode = midentifyTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.sex
     *
     * @return the value of HSDB01_01.sex
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.sex
     *
     * @param sex the value for HSDB01_01.sex
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fprovince
     *
     * @return the value of HSDB01_01.fprovince
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFprovince() {
        return fprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fprovince
     *
     * @param fprovince the value for HSDB01_01.fprovince
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFprovince(String fprovince) {
        this.fprovince = fprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.author_name
     *
     * @return the value of HSDB01_01.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.author_name
     *
     * @param authorName the value for HSDB01_01.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fnationality_code
     *
     * @return the value of HSDB01_01.fnationality_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFnationalityCode() {
        return fnationalityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fnationality_code
     *
     * @param fnationalityCode the value for HSDB01_01.fnationality_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFnationalityCode(String fnationalityCode) {
        this.fnationalityCode = fnationalityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.xds_type
     *
     * @return the value of HSDB01_01.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.xds_type
     *
     * @param xdsType the value for HSDB01_01.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mcity
     *
     * @return the value of HSDB01_01.mcity
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMcity() {
        return mcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mcity
     *
     * @param mcity the value for HSDB01_01.mcity
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMcity(String mcity) {
        this.mcity = mcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.custodian_addr
     *
     * @return the value of HSDB01_01.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.custodian_addr
     *
     * @param custodianAddr the value for HSDB01_01.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fethnic
     *
     * @return the value of HSDB01_01.fethnic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFethnic() {
        return fethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fethnic
     *
     * @param fethnic the value for HSDB01_01.fethnic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFethnic(String fethnic) {
        this.fethnic = fethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.patient_name
     *
     * @return the value of HSDB01_01.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.patient_name
     *
     * @param patientName the value for HSDB01_01.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fcounty
     *
     * @return the value of HSDB01_01.fcounty
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFcounty() {
        return fcounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fcounty
     *
     * @param fcounty the value for HSDB01_01.fcounty
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFcounty(String fcounty) {
        this.fcounty = fcounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.write_time
     *
     * @return the value of HSDB01_01.write_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.write_time
     *
     * @param writeTime the value for HSDB01_01.write_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.domain_id
     *
     * @return the value of HSDB01_01.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.domain_id
     *
     * @param domainId the value for HSDB01_01.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.length
     *
     * @return the value of HSDB01_01.length
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.length
     *
     * @param length the value for HSDB01_01.length
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLength(Float length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.template_oid
     *
     * @return the value of HSDB01_01.template_oid
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.template_oid
     *
     * @param templateOid the value for HSDB01_01.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mname
     *
     * @return the value of HSDB01_01.mname
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mname
     *
     * @param mname the value for HSDB01_01.mname
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMname(String mname) {
        this.mname = mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mtownship
     *
     * @return the value of HSDB01_01.mtownship
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMtownship() {
        return mtownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mtownship
     *
     * @param mtownship the value for HSDB01_01.mtownship
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMtownship(String mtownship) {
        this.mtownship = mtownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.custodian_name
     *
     * @return the value of HSDB01_01.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.custodian_name
     *
     * @param custodianName the value for HSDB01_01.custodian_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fethnic_code
     *
     * @return the value of HSDB01_01.fethnic_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFethnicCode() {
        return fethnicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fethnic_code
     *
     * @param fethnicCode the value for HSDB01_01.fethnic_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFethnicCode(String fethnicCode) {
        this.fethnicCode = fethnicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.xds_version
     *
     * @return the value of HSDB01_01.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.xds_version
     *
     * @param xdsVersion the value for HSDB01_01.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.city
     *
     * @return the value of HSDB01_01.city
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.city
     *
     * @param city the value for HSDB01_01.city
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.empi
     *
     * @return the value of HSDB01_01.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.empi
     *
     * @param empi the value for HSDB01_01.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.licensee_code
     *
     * @return the value of HSDB01_01.licensee_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getLicenseeCode() {
        return licenseeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.licensee_code
     *
     * @param licenseeCode the value for HSDB01_01.licensee_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLicenseeCode(String licenseeCode) {
        this.licenseeCode = licenseeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fidentify_no
     *
     * @return the value of HSDB01_01.fidentify_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFidentifyNo() {
        return fidentifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fidentify_no
     *
     * @param fidentifyNo the value for HSDB01_01.fidentify_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFidentifyNo(String fidentifyNo) {
        this.fidentifyNo = fidentifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fstreet_name
     *
     * @return the value of HSDB01_01.fstreet_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFstreetName() {
        return fstreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fstreet_name
     *
     * @param fstreetName the value for HSDB01_01.fstreet_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFstreetName(String fstreetName) {
        this.fstreetName = fstreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mhouse_number
     *
     * @return the value of HSDB01_01.mhouse_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMhouseNumber() {
        return mhouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mhouse_number
     *
     * @param mhouseNumber the value for HSDB01_01.mhouse_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMhouseNumber(String mhouseNumber) {
        this.mhouseNumber = mhouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mi_addr
     *
     * @return the value of HSDB01_01.mi_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mi_addr
     *
     * @param miAddr the value for HSDB01_01.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fnationality
     *
     * @return the value of HSDB01_01.fnationality
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFnationality() {
        return fnationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fnationality
     *
     * @param fnationality the value for HSDB01_01.fnationality
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFnationality(String fnationality) {
        this.fnationality = fnationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.class_name
     *
     * @return the value of HSDB01_01.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.class_name
     *
     * @param className the value for HSDB01_01.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mguardian_birth
     *
     * @return the value of HSDB01_01.mguardian_birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getMguardianBirth() {
        return mguardianBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mguardian_birth
     *
     * @param mguardianBirth the value for HSDB01_01.mguardian_birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMguardianBirth(Date mguardianBirth) {
        this.mguardianBirth = mguardianBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.upload_time
     *
     * @return the value of HSDB01_01.upload_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.upload_time
     *
     * @param uploadTime the value for HSDB01_01.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.signatory_name
     *
     * @return the value of HSDB01_01.signatory_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSignatoryName() {
        return signatoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.signatory_name
     *
     * @param signatoryName the value for HSDB01_01.signatory_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSignatoryName(String signatoryName) {
        this.signatoryName = signatoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.midentify_type
     *
     * @return the value of HSDB01_01.midentify_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMidentifyType() {
        return midentifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.midentify_type
     *
     * @param midentifyType the value for HSDB01_01.midentify_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMidentifyType(String midentifyType) {
        this.midentifyType = midentifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.birth
     *
     * @return the value of HSDB01_01.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.birth
     *
     * @param birth the value for HSDB01_01.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fostal_code
     *
     * @return the value of HSDB01_01.fostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFostalCode() {
        return fostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fostal_code
     *
     * @param fostalCode the value for HSDB01_01.fostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFostalCode(String fostalCode) {
        this.fostalCode = fostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mi_code
     *
     * @return the value of HSDB01_01.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mi_code
     *
     * @param miCode the value for HSDB01_01.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mnationality_code
     *
     * @return the value of HSDB01_01.mnationality_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMnationalityCode() {
        return mnationalityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mnationality_code
     *
     * @param mnationalityCode the value for HSDB01_01.mnationality_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMnationalityCode(String mnationalityCode) {
        this.mnationalityCode = mnationalityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.xds_name
     *
     * @return the value of HSDB01_01.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.xds_name
     *
     * @param xdsName the value for HSDB01_01.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mprovince
     *
     * @return the value of HSDB01_01.mprovince
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMprovince() {
        return mprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mprovince
     *
     * @param mprovince the value for HSDB01_01.mprovince
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMprovince(String mprovince) {
        this.mprovince = mprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.issue_date
     *
     * @return the value of HSDB01_01.issue_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getIssueDate() {
        return issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.issue_date
     *
     * @param issueDate the value for HSDB01_01.issue_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fidentify_type_code
     *
     * @return the value of HSDB01_01.fidentify_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFidentifyTypeCode() {
        return fidentifyTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fidentify_type_code
     *
     * @param fidentifyTypeCode the value for HSDB01_01.fidentify_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFidentifyTypeCode(String fidentifyTypeCode) {
        this.fidentifyTypeCode = fidentifyTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.sex_code
     *
     * @return the value of HSDB01_01.sex_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.sex_code
     *
     * @param sexCode the value for HSDB01_01.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fcity
     *
     * @return the value of HSDB01_01.fcity
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFcity() {
        return fcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fcity
     *
     * @param fcity the value for HSDB01_01.fcity
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFcity(String fcity) {
        this.fcity = fcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.author_code
     *
     * @return the value of HSDB01_01.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.author_code
     *
     * @param authorCode the value for HSDB01_01.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.height
     *
     * @return the value of HSDB01_01.height
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.height
     *
     * @param height the value for HSDB01_01.height
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHeight(String height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.unique_id
     *
     * @return the value of HSDB01_01.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.unique_id
     *
     * @param uniqueId the value for HSDB01_01.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.fname
     *
     * @return the value of HSDB01_01.fname
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.fname
     *
     * @param fname the value for HSDB01_01.fname
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFname(String fname) {
        this.fname = fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.mcounty
     *
     * @return the value of HSDB01_01.mcounty
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMcounty() {
        return mcounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.mcounty
     *
     * @param mcounty the value for HSDB01_01.mcounty
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMcounty(String mcounty) {
        this.mcounty = mcounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.custodian_telecom
     *
     * @return the value of HSDB01_01.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.custodian_telecom
     *
     * @param custodianTelecom the value for HSDB01_01.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.methnic
     *
     * @return the value of HSDB01_01.methnic
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMethnic() {
        return methnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.methnic
     *
     * @param methnic the value for HSDB01_01.methnic
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMethnic(String methnic) {
        this.methnic = methnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.prove_no
     *
     * @return the value of HSDB01_01.prove_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getProveNo() {
        return proveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.prove_no
     *
     * @param proveNo the value for HSDB01_01.prove_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setProveNo(String proveNo) {
        this.proveNo = proveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.ftownship
     *
     * @return the value of HSDB01_01.ftownship
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFtownship() {
        return ftownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.ftownship
     *
     * @param ftownship the value for HSDB01_01.ftownship
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFtownship(String ftownship) {
        this.ftownship = ftownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.province
     *
     * @return the value of HSDB01_01.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.province
     *
     * @param province the value for HSDB01_01.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.encounter_id
     *
     * @return the value of HSDB01_01.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.encounter_id
     *
     * @param encounterId the value for HSDB01_01.encounter_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.gestat_week
     *
     * @return the value of HSDB01_01.gestat_week
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getGestatWeek() {
        return gestatWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.gestat_week
     *
     * @param gestatWeek the value for HSDB01_01.gestat_week
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setGestatWeek(String gestatWeek) {
        this.gestatWeek = gestatWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.register_model
     *
     * @return the value of HSDB01_01.register_model
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.register_model
     *
     * @param registerModel the value for HSDB01_01.register_model
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB01_01.midentify_no
     *
     * @return the value of HSDB01_01.midentify_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMidentifyNo() {
        return midentifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB01_01.midentify_no
     *
     * @param midentifyNo the value for HSDB01_01.midentify_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMidentifyNo(String midentifyNo) {
        this.midentifyNo = midentifyNo;
    }
}