package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("HSDB03_03")
public class Hsdb0303 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.duration
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.ethnic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ethnic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.key_death_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String keyDeathCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.census_city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String maritalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.diagnose_botype_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String diagnoseBotypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.census_township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusTownship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.occupation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String occupationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.place_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String placeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.mi_level_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miLevelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String streetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.census_house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusHouseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.death_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date deathDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.edu_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String eduCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.inpatient
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inpatient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.ethnic_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ethnicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.key_death_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String keyDeathReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ostalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.census_province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.marital_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String maritalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.diagnose_botype
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String diagnoseBotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.census_county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.occupation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String occupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.death_hospital
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String deathHospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.mi_level_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miLevelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String township;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.census_street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusStreetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.place_type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String placeTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.edu_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String eduName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String houseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.workplace
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String workplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.workplace_tel
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String workplaceTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.identify_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String identifyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB03_03.census_ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String censusOstalCode;


    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.author_name
     *
     * @param authorName the value for HSDB03_03.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.duration
     *
     * @return the value of HSDB03_03.duration
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.duration
     *
     * @param duration the value for HSDB03_03.duration
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDuration(String duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.health_no
     *
     * @return the value of HSDB03_03.health_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthNo() {
        return healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.health_no
     *
     * @param healthNo the value for HSDB03_03.health_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthNo(String healthNo) {
        this.healthNo = healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.ethnic
     *
     * @return the value of HSDB03_03.ethnic
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEthnic() {
        return ethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.ethnic
     *
     * @param ethnic the value for HSDB03_03.ethnic
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEthnic(String ethnic) {
        this.ethnic = ethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.encounter_id
     *
     * @return the value of HSDB03_03.encounter_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.encounter_id
     *
     * @param encounterId the value for HSDB03_03.encounter_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.custodian_addr
     *
     * @return the value of HSDB03_03.custodian_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.custodian_addr
     *
     * @param custodianAddr the value for HSDB03_03.custodian_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.register_model
     *
     * @return the value of HSDB03_03.register_model
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.register_model
     *
     * @param registerModel the value for HSDB03_03.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.key_death_code
     *
     * @return the value of HSDB03_03.key_death_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getKeyDeathCode() {
        return keyDeathCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.key_death_code
     *
     * @param keyDeathCode the value for HSDB03_03.key_death_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setKeyDeathCode(String keyDeathCode) {
        this.keyDeathCode = keyDeathCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.province
     *
     * @return the value of HSDB03_03.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.province
     *
     * @param province the value for HSDB03_03.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.census_city
     *
     * @return the value of HSDB03_03.census_city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusCity() {
        return censusCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.census_city
     *
     * @param censusCity the value for HSDB03_03.census_city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusCity(String censusCity) {
        this.censusCity = censusCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.write_time
     *
     * @return the value of HSDB03_03.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.write_time
     *
     * @param writeTime the value for HSDB03_03.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.class_code
     *
     * @return the value of HSDB03_03.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.class_code
     *
     * @param classCode the value for HSDB03_03.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.marital_name
     *
     * @return the value of HSDB03_03.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMaritalName() {
        return maritalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.marital_name
     *
     * @param maritalName the value for HSDB03_03.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMaritalName(String maritalName) {
        this.maritalName = maritalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.status
     *
     * @return the value of HSDB03_03.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.status
     *
     * @param status the value for HSDB03_03.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.custodian_name
     *
     * @return the value of HSDB03_03.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.custodian_name
     *
     * @param custodianName the value for HSDB03_03.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.diagnose_botype_code
     *
     * @return the value of HSDB03_03.diagnose_botype_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDiagnoseBotypeCode() {
        return diagnoseBotypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.diagnose_botype_code
     *
     * @param diagnoseBotypeCode the value for HSDB03_03.diagnose_botype_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDiagnoseBotypeCode(String diagnoseBotypeCode) {
        this.diagnoseBotypeCode = diagnoseBotypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.county
     *
     * @return the value of HSDB03_03.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.county
     *
     * @param county the value for HSDB03_03.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.census_township
     *
     * @return the value of HSDB03_03.census_township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusTownship() {
        return censusTownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.census_township
     *
     * @param censusTownship the value for HSDB03_03.census_township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusTownship(String censusTownship) {
        this.censusTownship = censusTownship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.occupation_code
     *
     * @return the value of HSDB03_03.occupation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOccupationCode() {
        return occupationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.occupation_code
     *
     * @param occupationCode the value for HSDB03_03.occupation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOccupationCode(String occupationCode) {
        this.occupationCode = occupationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.place_type
     *
     * @return the value of HSDB03_03.place_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPlaceType() {
        return placeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.place_type
     *
     * @param placeType the value for HSDB03_03.place_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPlaceType(String placeType) {
        this.placeType = placeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.effective_time
     *
     * @return the value of HSDB03_03.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.effective_time
     *
     * @param effectiveTime the value for HSDB03_03.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.sex
     *
     * @return the value of HSDB03_03.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.sex
     *
     * @param sex the value for HSDB03_03.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.pk
     *
     * @return the value of HSDB03_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.pk
     *
     * @param pk the value for HSDB03_03.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.mi_addr
     *
     * @return the value of HSDB03_03.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.mi_addr
     *
     * @param miAddr the value for HSDB03_03.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.mi_level_code
     *
     * @return the value of HSDB03_03.mi_level_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiLevelCode() {
        return miLevelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.mi_level_code
     *
     * @param miLevelCode the value for HSDB03_03.mi_level_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiLevelCode(String miLevelCode) {
        this.miLevelCode = miLevelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.street_name
     *
     * @return the value of HSDB03_03.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.street_name
     *
     * @param streetName the value for HSDB03_03.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.census_house_number
     *
     * @return the value of HSDB03_03.census_house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusHouseNumber() {
        return censusHouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.census_house_number
     *
     * @param censusHouseNumber the value for HSDB03_03.census_house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusHouseNumber(String censusHouseNumber) {
        this.censusHouseNumber = censusHouseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.death_date
     *
     * @return the value of HSDB03_03.death_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getDeathDate() {
        return deathDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.death_date
     *
     * @param deathDate the value for HSDB03_03.death_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDeathDate(Date deathDate) {
        this.deathDate = deathDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.xds_type
     *
     * @return the value of HSDB03_03.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.xds_type
     *
     * @param xdsType the value for HSDB03_03.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.patient_name
     *
     * @return the value of HSDB03_03.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.patient_name
     *
     * @param patientName the value for HSDB03_03.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.edu_code
     *
     * @return the value of HSDB03_03.edu_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEduCode() {
        return eduCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.edu_code
     *
     * @param eduCode the value for HSDB03_03.edu_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEduCode(String eduCode) {
        this.eduCode = eduCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.mi_code
     *
     * @return the value of HSDB03_03.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.mi_code
     *
     * @param miCode the value for HSDB03_03.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.inpatient
     *
     * @return the value of HSDB03_03.inpatient
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInpatient() {
        return inpatient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.inpatient
     *
     * @param inpatient the value for HSDB03_03.inpatient
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInpatient(String inpatient) {
        this.inpatient = inpatient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.ethnic_code
     *
     * @return the value of HSDB03_03.ethnic_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEthnicCode() {
        return ethnicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.ethnic_code
     *
     * @param ethnicCode the value for HSDB03_03.ethnic_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEthnicCode(String ethnicCode) {
        this.ethnicCode = ethnicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.domain_id
     *
     * @return the value of HSDB03_03.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.domain_id
     *
     * @param domainId the value for HSDB03_03.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.template_oid
     *
     * @return the value of HSDB03_03.template_oid
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.template_oid
     *
     * @param templateOid the value for HSDB03_03.template_oid
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.key_death_reason
     *
     * @return the value of HSDB03_03.key_death_reason
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getKeyDeathReason() {
        return keyDeathReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.key_death_reason
     *
     * @param keyDeathReason the value for HSDB03_03.key_death_reason
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setKeyDeathReason(String keyDeathReason) {
        this.keyDeathReason = keyDeathReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.ostal_code
     *
     * @return the value of HSDB03_03.ostal_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOstalCode() {
        return ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.ostal_code
     *
     * @param ostalCode the value for HSDB03_03.ostal_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOstalCode(String ostalCode) {
        this.ostalCode = ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.census_province
     *
     * @return the value of HSDB03_03.census_province
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusProvince() {
        return censusProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.census_province
     *
     * @param censusProvince the value for HSDB03_03.census_province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusProvince(String censusProvince) {
        this.censusProvince = censusProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.author_code
     *
     * @return the value of HSDB03_03.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.author_code
     *
     * @param authorCode the value for HSDB03_03.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.xds_version
     *
     * @return the value of HSDB03_03.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.xds_version
     *
     * @param xdsVersion the value for HSDB03_03.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.marital_code
     *
     * @return the value of HSDB03_03.marital_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMaritalCode() {
        return maritalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.marital_code
     *
     * @param maritalCode the value for HSDB03_03.marital_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMaritalCode(String maritalCode) {
        this.maritalCode = maritalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.empi
     *
     * @return the value of HSDB03_03.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.empi
     *
     * @param empi the value for HSDB03_03.empi
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.custodian_telecom
     *
     * @return the value of HSDB03_03.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.custodian_telecom
     *
     * @param custodianTelecom the value for HSDB03_03.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.diagnose_botype
     *
     * @return the value of HSDB03_03.diagnose_botype
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDiagnoseBotype() {
        return diagnoseBotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.diagnose_botype
     *
     * @param diagnoseBotype the value for HSDB03_03.diagnose_botype
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDiagnoseBotype(String diagnoseBotype) {
        this.diagnoseBotype = diagnoseBotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.city
     *
     * @return the value of HSDB03_03.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.city
     *
     * @param city the value for HSDB03_03.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.census_county
     *
     * @return the value of HSDB03_03.census_county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusCounty() {
        return censusCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.census_county
     *
     * @param censusCounty the value for HSDB03_03.census_county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusCounty(String censusCounty) {
        this.censusCounty = censusCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.occupation
     *
     * @return the value of HSDB03_03.occupation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.occupation
     *
     * @param occupation the value for HSDB03_03.occupation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.death_hospital
     *
     * @return the value of HSDB03_03.death_hospital
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDeathHospital() {
        return deathHospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.death_hospital
     *
     * @param deathHospital the value for HSDB03_03.death_hospital
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDeathHospital(String deathHospital) {
        this.deathHospital = deathHospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.class_name
     *
     * @return the value of HSDB03_03.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.class_name
     *
     * @param className the value for HSDB03_03.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.birth
     *
     * @return the value of HSDB03_03.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.birth
     *
     * @param birth the value for HSDB03_03.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.upload_time
     *
     * @return the value of HSDB03_03.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.upload_time
     *
     * @param uploadTime the value for HSDB03_03.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.custodian_code
     *
     * @return the value of HSDB03_03.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.custodian_code
     *
     * @param custodianCode the value for HSDB03_03.custodian_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.mi_level_name
     *
     * @return the value of HSDB03_03.mi_level_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiLevelName() {
        return miLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.mi_level_name
     *
     * @param miLevelName the value for HSDB03_03.mi_level_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiLevelName(String miLevelName) {
        this.miLevelName = miLevelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.township
     *
     * @return the value of HSDB03_03.township
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTownship() {
        return township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.township
     *
     * @param township the value for HSDB03_03.township
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTownship(String township) {
        this.township = township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.census_street_name
     *
     * @return the value of HSDB03_03.census_street_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusStreetName() {
        return censusStreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.census_street_name
     *
     * @param censusStreetName the value for HSDB03_03.census_street_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusStreetName(String censusStreetName) {
        this.censusStreetName = censusStreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.place_type_code
     *
     * @return the value of HSDB03_03.place_type_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPlaceTypeCode() {
        return placeTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.place_type_code
     *
     * @param placeTypeCode the value for HSDB03_03.place_type_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPlaceTypeCode(String placeTypeCode) {
        this.placeTypeCode = placeTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.xds_name
     *
     * @return the value of HSDB03_03.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.xds_name
     *
     * @param xdsName the value for HSDB03_03.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.sex_code
     *
     * @return the value of HSDB03_03.sex_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.sex_code
     *
     * @param sexCode the value for HSDB03_03.sex_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.edu_name
     *
     * @return the value of HSDB03_03.edu_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEduName() {
        return eduName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.edu_name
     *
     * @param eduName the value for HSDB03_03.edu_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEduName(String eduName) {
        this.eduName = eduName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.mi_name
     *
     * @return the value of HSDB03_03.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.mi_name
     *
     * @param miName the value for HSDB03_03.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.house_number
     *
     * @return the value of HSDB03_03.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.house_number
     *
     * @param houseNumber the value for HSDB03_03.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.workplace
     *
     * @return the value of HSDB03_03.workplace
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWorkplace() {
        return workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.workplace
     *
     * @param workplace the value for HSDB03_03.workplace
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWorkplace(String workplace) {
        this.workplace = workplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.workplace_tel
     *
     * @return the value of HSDB03_03.workplace_tel
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getWorkplaceTel() {
        return workplaceTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.workplace_tel
     *
     * @param workplaceTel the value for HSDB03_03.workplace_tel
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWorkplaceTel(String workplaceTel) {
        this.workplaceTel = workplaceTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.unique_id
     *
     * @return the value of HSDB03_03.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.unique_id
     *
     * @param uniqueId the value for HSDB03_03.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.identify_no
     *
     * @return the value of HSDB03_03.identify_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIdentifyNo() {
        return identifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.identify_no
     *
     * @param identifyNo the value for HSDB03_03.identify_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIdentifyNo(String identifyNo) {
        this.identifyNo = identifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB03_03.census_ostal_code
     *
     * @return the value of HSDB03_03.census_ostal_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCensusOstalCode() {
        return censusOstalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB03_03.census_ostal_code
     *
     * @param censusOstalCode the value for HSDB03_03.census_ostal_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCensusOstalCode(String censusOstalCode) {
        this.censusOstalCode = censusOstalCode;
    }
}