package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("HSDB04_02")
public class Hsdb0402 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.mental_situation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mentalSituationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String township;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.fu_way_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fuWayCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.mass_index
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Double massIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.aims_drink
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String aimsDrink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.insulin_frequency_unit
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String insulinFrequencyUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.referral_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean referralMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.exercise_duration
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String exerciseDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String houseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.hemoglobin_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date hemoglobinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.diastolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String diastolic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.aims_constitution
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Double aimsConstitution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String telecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.cm_category
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String cmCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.insulin_dose_unit
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String insulinDoseUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.exercise_frequency_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String exerciseFrequencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.blood_sugar
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String bloodSugar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.fu_evaluation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fuEvaluation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.fd_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fdResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.ethnic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ethnic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.smoke
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String smoke;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.aims_motion
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String aimsMotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.hypoglycemia_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String hypoglycemiaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.mental_situation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String mentalSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String maritalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.fu_way
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fuWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.beat_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean beatMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.aims_frequency_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String aimsFrequencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.insulin_drug_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String insulinDrugName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String referralReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.staple_food
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String stapleFood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String streetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.fu_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date fuDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.height
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.aims_smoke
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String aimsSmoke;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.insulin_frequency_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String insulinFrequencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.frequency
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.hemoglobin
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float hemoglobin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.next_fu_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date nextFuDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.aims_weight
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float aimsWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ostalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.cm_category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String cmCategoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.ethnic_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ethnicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.insulin_drug_dose
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Float insulinDrugDose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.systolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String systolic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.drink
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String drink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.aims_staple_food
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String aimsStapleFood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.fu_evaluation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fuEvaluationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.fd_result_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String fdResultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.marital_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String maritalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.positive_signs
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String positiveSigns;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.aims_frequency
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String aimsFrequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDB04_02.hypoglycemia_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String hypoglycemiaCode;


    public String getIndeptCode() {
        return indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.indept_code
     *
     * @param indeptCode the value for HSDB04_02.indept_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptCode(String indeptCode) {
        this.indeptCode = indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.mental_situation_code
     *
     * @return the value of HSDB04_02.mental_situation_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMentalSituationCode() {
        return mentalSituationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.mental_situation_code
     *
     * @param mentalSituationCode the value for HSDB04_02.mental_situation_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMentalSituationCode(String mentalSituationCode) {
        this.mentalSituationCode = mentalSituationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.empi
     *
     * @return the value of HSDB04_02.empi
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.empi
     *
     * @param empi the value for HSDB04_02.empi
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.township
     *
     * @return the value of HSDB04_02.township
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTownship() {
        return township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.township
     *
     * @param township the value for HSDB04_02.township
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTownship(String township) {
        this.township = township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.birth
     *
     * @return the value of HSDB04_02.birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.birth
     *
     * @param birth the value for HSDB04_02.birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.fu_way_code
     *
     * @return the value of HSDB04_02.fu_way_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFuWayCode() {
        return fuWayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.fu_way_code
     *
     * @param fuWayCode the value for HSDB04_02.fu_way_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuWayCode(String fuWayCode) {
        this.fuWayCode = fuWayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.mass_index
     *
     * @return the value of HSDB04_02.mass_index
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Double getMassIndex() {
        return massIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.mass_index
     *
     * @param massIndex the value for HSDB04_02.mass_index
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMassIndex(Double massIndex) {
        this.massIndex = massIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.upload_time
     *
     * @return the value of HSDB04_02.upload_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.upload_time
     *
     * @param uploadTime the value for HSDB04_02.upload_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.xds_type
     *
     * @return the value of HSDB04_02.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.xds_type
     *
     * @param xdsType the value for HSDB04_02.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.aims_drink
     *
     * @return the value of HSDB04_02.aims_drink
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAimsDrink() {
        return aimsDrink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.aims_drink
     *
     * @param aimsDrink the value for HSDB04_02.aims_drink
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAimsDrink(String aimsDrink) {
        this.aimsDrink = aimsDrink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.author_name
     *
     * @return the value of HSDB04_02.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.author_name
     *
     * @param authorName the value for HSDB04_02.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.insulin_frequency_unit
     *
     * @return the value of HSDB04_02.insulin_frequency_unit
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInsulinFrequencyUnit() {
        return insulinFrequencyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.insulin_frequency_unit
     *
     * @param insulinFrequencyUnit the value for HSDB04_02.insulin_frequency_unit
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInsulinFrequencyUnit(String insulinFrequencyUnit) {
        this.insulinFrequencyUnit = insulinFrequencyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.referral_mark
     *
     * @return the value of HSDB04_02.referral_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getReferralMark() {
        return referralMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.referral_mark
     *
     * @param referralMark the value for HSDB04_02.referral_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralMark(Boolean referralMark) {
        this.referralMark = referralMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.exercise_duration
     *
     * @return the value of HSDB04_02.exercise_duration
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getExerciseDuration() {
        return exerciseDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.exercise_duration
     *
     * @param exerciseDuration the value for HSDB04_02.exercise_duration
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setExerciseDuration(String exerciseDuration) {
        this.exerciseDuration = exerciseDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.house_number
     *
     * @return the value of HSDB04_02.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.house_number
     *
     * @param houseNumber the value for HSDB04_02.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.hemoglobin_time
     *
     * @return the value of HSDB04_02.hemoglobin_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getHemoglobinTime() {
        return hemoglobinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.hemoglobin_time
     *
     * @param hemoglobinTime the value for HSDB04_02.hemoglobin_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHemoglobinTime(Date hemoglobinTime) {
        this.hemoglobinTime = hemoglobinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.sex_code
     *
     * @return the value of HSDB04_02.sex_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.sex_code
     *
     * @param sexCode the value for HSDB04_02.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.custodian_addr
     *
     * @return the value of HSDB04_02.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.custodian_addr
     *
     * @param custodianAddr the value for HSDB04_02.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.diastolic
     *
     * @return the value of HSDB04_02.diastolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDiastolic() {
        return diastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.diastolic
     *
     * @param diastolic the value for HSDB04_02.diastolic
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDiastolic(String diastolic) {
        this.diastolic = diastolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.template_oid
     *
     * @return the value of HSDB04_02.template_oid
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.template_oid
     *
     * @param templateOid the value for HSDB04_02.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.aims_constitution
     *
     * @return the value of HSDB04_02.aims_constitution
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Double getAimsConstitution() {
        return aimsConstitution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.aims_constitution
     *
     * @param aimsConstitution the value for HSDB04_02.aims_constitution
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAimsConstitution(Double aimsConstitution) {
        this.aimsConstitution = aimsConstitution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.telecom
     *
     * @return the value of HSDB04_02.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTelecom() {
        return telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.telecom
     *
     * @param telecom the value for HSDB04_02.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTelecom(String telecom) {
        this.telecom = telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.cm_category
     *
     * @return the value of HSDB04_02.cm_category
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCmCategory() {
        return cmCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.cm_category
     *
     * @param cmCategory the value for HSDB04_02.cm_category
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCmCategory(String cmCategory) {
        this.cmCategory = cmCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.write_time
     *
     * @return the value of HSDB04_02.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.write_time
     *
     * @param writeTime the value for HSDB04_02.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.insulin_dose_unit
     *
     * @return the value of HSDB04_02.insulin_dose_unit
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInsulinDoseUnit() {
        return insulinDoseUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.insulin_dose_unit
     *
     * @param insulinDoseUnit the value for HSDB04_02.insulin_dose_unit
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInsulinDoseUnit(String insulinDoseUnit) {
        this.insulinDoseUnit = insulinDoseUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.exercise_frequency_code
     *
     * @return the value of HSDB04_02.exercise_frequency_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getExerciseFrequencyCode() {
        return exerciseFrequencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.exercise_frequency_code
     *
     * @param exerciseFrequencyCode the value for HSDB04_02.exercise_frequency_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setExerciseFrequencyCode(String exerciseFrequencyCode) {
        this.exerciseFrequencyCode = exerciseFrequencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.xds_version
     *
     * @return the value of HSDB04_02.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.xds_version
     *
     * @param xdsVersion the value for HSDB04_02.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.blood_sugar
     *
     * @return the value of HSDB04_02.blood_sugar
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getBloodSugar() {
        return bloodSugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.blood_sugar
     *
     * @param bloodSugar the value for HSDB04_02.blood_sugar
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBloodSugar(String bloodSugar) {
        this.bloodSugar = bloodSugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.custodian_name
     *
     * @return the value of HSDB04_02.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.custodian_name
     *
     * @param custodianName the value for HSDB04_02.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.fu_evaluation
     *
     * @return the value of HSDB04_02.fu_evaluation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFuEvaluation() {
        return fuEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.fu_evaluation
     *
     * @param fuEvaluation the value for HSDB04_02.fu_evaluation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuEvaluation(String fuEvaluation) {
        this.fuEvaluation = fuEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.inmi_name
     *
     * @return the value of HSDB04_02.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiName() {
        return inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.inmi_name
     *
     * @param inmiName the value for HSDB04_02.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiName(String inmiName) {
        this.inmiName = inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.fd_result
     *
     * @return the value of HSDB04_02.fd_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFdResult() {
        return fdResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.fd_result
     *
     * @param fdResult the value for HSDB04_02.fd_result
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFdResult(String fdResult) {
        this.fdResult = fdResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.province
     *
     * @return the value of HSDB04_02.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.province
     *
     * @param province the value for HSDB04_02.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.ethnic
     *
     * @return the value of HSDB04_02.ethnic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEthnic() {
        return ethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.ethnic
     *
     * @param ethnic the value for HSDB04_02.ethnic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEthnic(String ethnic) {
        this.ethnic = ethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.smoke
     *
     * @return the value of HSDB04_02.smoke
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSmoke() {
        return smoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.smoke
     *
     * @param smoke the value for HSDB04_02.smoke
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSmoke(String smoke) {
        this.smoke = smoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.class_name
     *
     * @return the value of HSDB04_02.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.class_name
     *
     * @param className the value for HSDB04_02.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.aims_motion
     *
     * @return the value of HSDB04_02.aims_motion
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAimsMotion() {
        return aimsMotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.aims_motion
     *
     * @param aimsMotion the value for HSDB04_02.aims_motion
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAimsMotion(String aimsMotion) {
        this.aimsMotion = aimsMotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.mi_addr
     *
     * @return the value of HSDB04_02.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.mi_addr
     *
     * @param miAddr the value for HSDB04_02.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.hypoglycemia_name
     *
     * @return the value of HSDB04_02.hypoglycemia_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHypoglycemiaName() {
        return hypoglycemiaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.hypoglycemia_name
     *
     * @param hypoglycemiaName the value for HSDB04_02.hypoglycemia_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHypoglycemiaName(String hypoglycemiaName) {
        this.hypoglycemiaName = hypoglycemiaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.indept_name
     *
     * @return the value of HSDB04_02.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIndeptName() {
        return indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.indept_name
     *
     * @param indeptName the value for HSDB04_02.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptName(String indeptName) {
        this.indeptName = indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.mental_situation
     *
     * @return the value of HSDB04_02.mental_situation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMentalSituation() {
        return mentalSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.mental_situation
     *
     * @param mentalSituation the value for HSDB04_02.mental_situation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMentalSituation(String mentalSituation) {
        this.mentalSituation = mentalSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.encounter_id
     *
     * @return the value of HSDB04_02.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.encounter_id
     *
     * @param encounterId the value for HSDB04_02.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.county
     *
     * @return the value of HSDB04_02.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.county
     *
     * @param county the value for HSDB04_02.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.marital_name
     *
     * @return the value of HSDB04_02.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMaritalName() {
        return maritalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.marital_name
     *
     * @param maritalName the value for HSDB04_02.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMaritalName(String maritalName) {
        this.maritalName = maritalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.fu_way
     *
     * @return the value of HSDB04_02.fu_way
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFuWay() {
        return fuWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.fu_way
     *
     * @param fuWay the value for HSDB04_02.fu_way
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuWay(String fuWay) {
        this.fuWay = fuWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.beat_mark
     *
     * @return the value of HSDB04_02.beat_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getBeatMark() {
        return beatMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.beat_mark
     *
     * @param beatMark the value for HSDB04_02.beat_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBeatMark(Boolean beatMark) {
        this.beatMark = beatMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.xds_name
     *
     * @return the value of HSDB04_02.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.xds_name
     *
     * @param xdsName the value for HSDB04_02.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.aims_frequency_code
     *
     * @return the value of HSDB04_02.aims_frequency_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAimsFrequencyCode() {
        return aimsFrequencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.aims_frequency_code
     *
     * @param aimsFrequencyCode the value for HSDB04_02.aims_frequency_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAimsFrequencyCode(String aimsFrequencyCode) {
        this.aimsFrequencyCode = aimsFrequencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.mi_code
     *
     * @return the value of HSDB04_02.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.mi_code
     *
     * @param miCode the value for HSDB04_02.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.insulin_drug_name
     *
     * @return the value of HSDB04_02.insulin_drug_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInsulinDrugName() {
        return insulinDrugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.insulin_drug_name
     *
     * @param insulinDrugName the value for HSDB04_02.insulin_drug_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInsulinDrugName(String insulinDrugName) {
        this.insulinDrugName = insulinDrugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.referral_reason
     *
     * @return the value of HSDB04_02.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getReferralReason() {
        return referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.referral_reason
     *
     * @param referralReason the value for HSDB04_02.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralReason(String referralReason) {
        this.referralReason = referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.staple_food
     *
     * @return the value of HSDB04_02.staple_food
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStapleFood() {
        return stapleFood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.staple_food
     *
     * @param stapleFood the value for HSDB04_02.staple_food
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStapleFood(String stapleFood) {
        this.stapleFood = stapleFood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.status
     *
     * @return the value of HSDB04_02.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.status
     *
     * @param status the value for HSDB04_02.status
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.street_name
     *
     * @return the value of HSDB04_02.street_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.street_name
     *
     * @param streetName the value for HSDB04_02.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.sex
     *
     * @return the value of HSDB04_02.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.sex
     *
     * @param sex the value for HSDB04_02.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.fu_date
     *
     * @return the value of HSDB04_02.fu_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getFuDate() {
        return fuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.fu_date
     *
     * @param fuDate the value for HSDB04_02.fu_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuDate(Date fuDate) {
        this.fuDate = fuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.height
     *
     * @return the value of HSDB04_02.height
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.height
     *
     * @param height the value for HSDB04_02.height
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.pk
     *
     * @return the value of HSDB04_02.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.pk
     *
     * @param pk the value for HSDB04_02.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.unique_id
     *
     * @return the value of HSDB04_02.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.unique_id
     *
     * @param uniqueId the value for HSDB04_02.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.aims_smoke
     *
     * @return the value of HSDB04_02.aims_smoke
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAimsSmoke() {
        return aimsSmoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.aims_smoke
     *
     * @param aimsSmoke the value for HSDB04_02.aims_smoke
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAimsSmoke(String aimsSmoke) {
        this.aimsSmoke = aimsSmoke;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.patient_name
     *
     * @return the value of HSDB04_02.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.patient_name
     *
     * @param patientName the value for HSDB04_02.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.author_code
     *
     * @return the value of HSDB04_02.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.author_code
     *
     * @param authorCode the value for HSDB04_02.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.insulin_frequency_code
     *
     * @return the value of HSDB04_02.insulin_frequency_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInsulinFrequencyCode() {
        return insulinFrequencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.insulin_frequency_code
     *
     * @param insulinFrequencyCode the value for HSDB04_02.insulin_frequency_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInsulinFrequencyCode(String insulinFrequencyCode) {
        this.insulinFrequencyCode = insulinFrequencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.frequency
     *
     * @return the value of HSDB04_02.frequency
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.frequency
     *
     * @param frequency the value for HSDB04_02.frequency
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.health_no
     *
     * @return the value of HSDB04_02.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthNo() {
        return healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.health_no
     *
     * @param healthNo the value for HSDB04_02.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthNo(String healthNo) {
        this.healthNo = healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.hemoglobin
     *
     * @return the value of HSDB04_02.hemoglobin
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getHemoglobin() {
        return hemoglobin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.hemoglobin
     *
     * @param hemoglobin the value for HSDB04_02.hemoglobin
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHemoglobin(Float hemoglobin) {
        this.hemoglobin = hemoglobin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.custodian_telecom
     *
     * @return the value of HSDB04_02.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.custodian_telecom
     *
     * @param custodianTelecom the value for HSDB04_02.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.next_fu_date
     *
     * @return the value of HSDB04_02.next_fu_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getNextFuDate() {
        return nextFuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.next_fu_date
     *
     * @param nextFuDate the value for HSDB04_02.next_fu_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setNextFuDate(Date nextFuDate) {
        this.nextFuDate = nextFuDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.register_model
     *
     * @return the value of HSDB04_02.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.register_model
     *
     * @param registerModel the value for HSDB04_02.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.aims_weight
     *
     * @return the value of HSDB04_02.aims_weight
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getAimsWeight() {
        return aimsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.aims_weight
     *
     * @param aimsWeight the value for HSDB04_02.aims_weight
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAimsWeight(Float aimsWeight) {
        this.aimsWeight = aimsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.ostal_code
     *
     * @return the value of HSDB04_02.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOstalCode() {
        return ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.ostal_code
     *
     * @param ostalCode the value for HSDB04_02.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOstalCode(String ostalCode) {
        this.ostalCode = ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.cm_category_code
     *
     * @return the value of HSDB04_02.cm_category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCmCategoryCode() {
        return cmCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.cm_category_code
     *
     * @param cmCategoryCode the value for HSDB04_02.cm_category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCmCategoryCode(String cmCategoryCode) {
        this.cmCategoryCode = cmCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.ethnic_code
     *
     * @return the value of HSDB04_02.ethnic_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEthnicCode() {
        return ethnicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.ethnic_code
     *
     * @param ethnicCode the value for HSDB04_02.ethnic_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEthnicCode(String ethnicCode) {
        this.ethnicCode = ethnicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.insulin_drug_dose
     *
     * @return the value of HSDB04_02.insulin_drug_dose
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Float getInsulinDrugDose() {
        return insulinDrugDose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.insulin_drug_dose
     *
     * @param insulinDrugDose the value for HSDB04_02.insulin_drug_dose
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInsulinDrugDose(Float insulinDrugDose) {
        this.insulinDrugDose = insulinDrugDose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.systolic
     *
     * @return the value of HSDB04_02.systolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSystolic() {
        return systolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.systolic
     *
     * @param systolic the value for HSDB04_02.systolic
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSystolic(String systolic) {
        this.systolic = systolic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.drink
     *
     * @return the value of HSDB04_02.drink
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDrink() {
        return drink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.drink
     *
     * @param drink the value for HSDB04_02.drink
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDrink(String drink) {
        this.drink = drink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.class_code
     *
     * @return the value of HSDB04_02.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.class_code
     *
     * @param classCode the value for HSDB04_02.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.aims_staple_food
     *
     * @return the value of HSDB04_02.aims_staple_food
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAimsStapleFood() {
        return aimsStapleFood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.aims_staple_food
     *
     * @param aimsStapleFood the value for HSDB04_02.aims_staple_food
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAimsStapleFood(String aimsStapleFood) {
        this.aimsStapleFood = aimsStapleFood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.custodian_code
     *
     * @return the value of HSDB04_02.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.custodian_code
     *
     * @param custodianCode the value for HSDB04_02.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.fu_evaluation_code
     *
     * @return the value of HSDB04_02.fu_evaluation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFuEvaluationCode() {
        return fuEvaluationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.fu_evaluation_code
     *
     * @param fuEvaluationCode the value for HSDB04_02.fu_evaluation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFuEvaluationCode(String fuEvaluationCode) {
        this.fuEvaluationCode = fuEvaluationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.inmi_code
     *
     * @return the value of HSDB04_02.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiCode() {
        return inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.inmi_code
     *
     * @param inmiCode the value for HSDB04_02.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiCode(String inmiCode) {
        this.inmiCode = inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.fd_result_code
     *
     * @return the value of HSDB04_02.fd_result_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFdResultCode() {
        return fdResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.fd_result_code
     *
     * @param fdResultCode the value for HSDB04_02.fd_result_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFdResultCode(String fdResultCode) {
        this.fdResultCode = fdResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.domain_id
     *
     * @return the value of HSDB04_02.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.domain_id
     *
     * @param domainId the value for HSDB04_02.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.city
     *
     * @return the value of HSDB04_02.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.city
     *
     * @param city the value for HSDB04_02.city
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.marital_code
     *
     * @return the value of HSDB04_02.marital_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMaritalCode() {
        return maritalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.marital_code
     *
     * @param maritalCode the value for HSDB04_02.marital_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMaritalCode(String maritalCode) {
        this.maritalCode = maritalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.positive_signs
     *
     * @return the value of HSDB04_02.positive_signs
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPositiveSigns() {
        return positiveSigns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.positive_signs
     *
     * @param positiveSigns the value for HSDB04_02.positive_signs
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPositiveSigns(String positiveSigns) {
        this.positiveSigns = positiveSigns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.effective_time
     *
     * @return the value of HSDB04_02.effective_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.effective_time
     *
     * @param effectiveTime the value for HSDB04_02.effective_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.aims_frequency
     *
     * @return the value of HSDB04_02.aims_frequency
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAimsFrequency() {
        return aimsFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.aims_frequency
     *
     * @param aimsFrequency the value for HSDB04_02.aims_frequency
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAimsFrequency(String aimsFrequency) {
        this.aimsFrequency = aimsFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.mi_name
     *
     * @return the value of HSDB04_02.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.mi_name
     *
     * @param miName the value for HSDB04_02.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDB04_02.hypoglycemia_code
     *
     * @return the value of HSDB04_02.hypoglycemia_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHypoglycemiaCode() {
        return hypoglycemiaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDB04_02.hypoglycemia_code
     *
     * @param hypoglycemiaCode the value for HSDB04_02.hypoglycemia_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHypoglycemiaCode(String hypoglycemiaCode) {
        this.hypoglycemiaCode = hypoglycemiaCode;
    }
}