package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("HSDC00_05")
public class Hsdc0005 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String referralReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String streetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.response_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String responseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.treatment_programs
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String treatmentPrograms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.inspect_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inspectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.medical_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String medicalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.response_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date responseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.cm_category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String cmCategoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ostalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.medical_history
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String medicalHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.outmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String outmiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.admission_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String admissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String township;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.turn_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String turnTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.measure_guide
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String measureGuide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.referral_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date referralDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String houseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.response_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String responseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.cm_category
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String cmCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String telecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.out_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String outName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.medical_treatment
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String medicalTreatment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.admission_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String admissionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.referral_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String referralName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_05.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sex;


    public String getReferralReason() {
        return referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.referral_reason
     *
     * @param referralReason the value for HSDC00_05.referral_reason
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralReason(String referralReason) {
        this.referralReason = referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.street_name
     *
     * @return the value of HSDC00_05.street_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.street_name
     *
     * @param streetName the value for HSDC00_05.street_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.mi_addr
     *
     * @return the value of HSDC00_05.mi_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.mi_addr
     *
     * @param miAddr the value for HSDC00_05.mi_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.status
     *
     * @return the value of HSDC00_05.status
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.status
     *
     * @param status the value for HSDC00_05.status
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.response_name
     *
     * @return the value of HSDC00_05.response_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getResponseName() {
        return responseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.response_name
     *
     * @param responseName the value for HSDC00_05.response_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setResponseName(String responseName) {
        this.responseName = responseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.xds_type
     *
     * @return the value of HSDC00_05.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.xds_type
     *
     * @param xdsType the value for HSDC00_05.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.treatment_programs
     *
     * @return the value of HSDC00_05.treatment_programs
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTreatmentPrograms() {
        return treatmentPrograms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.treatment_programs
     *
     * @param treatmentPrograms the value for HSDC00_05.treatment_programs
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTreatmentPrograms(String treatmentPrograms) {
        this.treatmentPrograms = treatmentPrograms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.patient_name
     *
     * @return the value of HSDC00_05.patient_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.patient_name
     *
     * @param patientName the value for HSDC00_05.patient_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.inspect_type
     *
     * @return the value of HSDC00_05.inspect_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInspectType() {
        return inspectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.inspect_type
     *
     * @param inspectType the value for HSDC00_05.inspect_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInspectType(String inspectType) {
        this.inspectType = inspectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.medical_no
     *
     * @return the value of HSDC00_05.medical_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMedicalNo() {
        return medicalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.medical_no
     *
     * @param medicalNo the value for HSDC00_05.medical_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMedicalNo(String medicalNo) {
        this.medicalNo = medicalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.mi_code
     *
     * @return the value of HSDC00_05.mi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.mi_code
     *
     * @param miCode the value for HSDC00_05.mi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.pk
     *
     * @return the value of HSDC00_05.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.pk
     *
     * @param pk the value for HSDC00_05.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.response_time
     *
     * @return the value of HSDC00_05.response_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.response_time
     *
     * @param responseTime the value for HSDC00_05.response_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.cm_category_code
     *
     * @return the value of HSDC00_05.cm_category_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCmCategoryCode() {
        return cmCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.cm_category_code
     *
     * @param cmCategoryCode the value for HSDC00_05.cm_category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCmCategoryCode(String cmCategoryCode) {
        this.cmCategoryCode = cmCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.template_oid
     *
     * @return the value of HSDC00_05.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.template_oid
     *
     * @param templateOid the value for HSDC00_05.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.inmi_code
     *
     * @return the value of HSDC00_05.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiCode() {
        return inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.inmi_code
     *
     * @param inmiCode the value for HSDC00_05.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiCode(String inmiCode) {
        this.inmiCode = inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.ostal_code
     *
     * @return the value of HSDC00_05.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOstalCode() {
        return ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.ostal_code
     *
     * @param ostalCode the value for HSDC00_05.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOstalCode(String ostalCode) {
        this.ostalCode = ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.medical_history
     *
     * @return the value of HSDC00_05.medical_history
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMedicalHistory() {
        return medicalHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.medical_history
     *
     * @param medicalHistory the value for HSDC00_05.medical_history
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMedicalHistory(String medicalHistory) {
        this.medicalHistory = medicalHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.xds_version
     *
     * @return the value of HSDC00_05.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.xds_version
     *
     * @param xdsVersion the value for HSDC00_05.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.author_code
     *
     * @return the value of HSDC00_05.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.author_code
     *
     * @param authorCode the value for HSDC00_05.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.domain_id
     *
     * @return the value of HSDC00_05.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.domain_id
     *
     * @param domainId the value for HSDC00_05.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.indept_code
     *
     * @return the value of HSDC00_05.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIndeptCode() {
        return indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.indept_code
     *
     * @param indeptCode the value for HSDC00_05.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptCode(String indeptCode) {
        this.indeptCode = indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.city
     *
     * @return the value of HSDC00_05.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.city
     *
     * @param city the value for HSDC00_05.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.custodian_telecom
     *
     * @return the value of HSDC00_05.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.custodian_telecom
     *
     * @param custodianTelecom the value for HSDC00_05.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.outmi_code
     *
     * @return the value of HSDC00_05.outmi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOutmiCode() {
        return outmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.outmi_code
     *
     * @param outmiCode the value for HSDC00_05.outmi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOutmiCode(String outmiCode) {
        this.outmiCode = outmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.class_name
     *
     * @return the value of HSDC00_05.class_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.class_name
     *
     * @param className the value for HSDC00_05.class_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.birth
     *
     * @return the value of HSDC00_05.birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.birth
     *
     * @param birth the value for HSDC00_05.birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.admission_name
     *
     * @return the value of HSDC00_05.admission_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAdmissionName() {
        return admissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.admission_name
     *
     * @param admissionName the value for HSDC00_05.admission_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAdmissionName(String admissionName) {
        this.admissionName = admissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.township
     *
     * @return the value of HSDC00_05.township
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTownship() {
        return township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.township
     *
     * @param township the value for HSDC00_05.township
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTownship(String township) {
        this.township = township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.custodian_code
     *
     * @return the value of HSDC00_05.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.custodian_code
     *
     * @param custodianCode the value for HSDC00_05.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.empi
     *
     * @return the value of HSDC00_05.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.empi
     *
     * @param empi the value for HSDC00_05.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.turn_telecom
     *
     * @return the value of HSDC00_05.turn_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTurnTelecom() {
        return turnTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.turn_telecom
     *
     * @param turnTelecom the value for HSDC00_05.turn_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTurnTelecom(String turnTelecom) {
        this.turnTelecom = turnTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.xds_name
     *
     * @return the value of HSDC00_05.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.xds_name
     *
     * @param xdsName the value for HSDC00_05.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.measure_guide
     *
     * @return the value of HSDC00_05.measure_guide
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMeasureGuide() {
        return measureGuide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.measure_guide
     *
     * @param measureGuide the value for HSDC00_05.measure_guide
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMeasureGuide(String measureGuide) {
        this.measureGuide = measureGuide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.sex_code
     *
     * @return the value of HSDC00_05.sex_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.sex_code
     *
     * @param sexCode the value for HSDC00_05.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.referral_date
     *
     * @return the value of HSDC00_05.referral_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getReferralDate() {
        return referralDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.referral_date
     *
     * @param referralDate the value for HSDC00_05.referral_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralDate(Date referralDate) {
        this.referralDate = referralDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.house_number
     *
     * @return the value of HSDC00_05.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.house_number
     *
     * @param houseNumber the value for HSDC00_05.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.mi_name
     *
     * @return the value of HSDC00_05.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.mi_name
     *
     * @param miName the value for HSDC00_05.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.upload_time
     *
     * @return the value of HSDC00_05.upload_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.upload_time
     *
     * @param uploadTime the value for HSDC00_05.upload_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.response_code
     *
     * @return the value of HSDC00_05.response_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.response_code
     *
     * @param responseCode the value for HSDC00_05.response_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setResponseCode(String responseCode) {
        this.responseCode = responseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.cm_category
     *
     * @return the value of HSDC00_05.cm_category
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCmCategory() {
        return cmCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.cm_category
     *
     * @param cmCategory the value for HSDC00_05.cm_category
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCmCategory(String cmCategory) {
        this.cmCategory = cmCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.unique_id
     *
     * @return the value of HSDC00_05.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.unique_id
     *
     * @param uniqueId the value for HSDC00_05.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.inmi_name
     *
     * @return the value of HSDC00_05.inmi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiName() {
        return inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.inmi_name
     *
     * @param inmiName the value for HSDC00_05.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiName(String inmiName) {
        this.inmiName = inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.telecom
     *
     * @return the value of HSDC00_05.telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTelecom() {
        return telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.telecom
     *
     * @param telecom the value for HSDC00_05.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTelecom(String telecom) {
        this.telecom = telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.health_no
     *
     * @return the value of HSDC00_05.health_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthNo() {
        return healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.health_no
     *
     * @param healthNo the value for HSDC00_05.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthNo(String healthNo) {
        this.healthNo = healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.author_name
     *
     * @return the value of HSDC00_05.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.author_name
     *
     * @param authorName the value for HSDC00_05.author_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.custodian_addr
     *
     * @return the value of HSDC00_05.custodian_addr
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.custodian_addr
     *
     * @param custodianAddr the value for HSDC00_05.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.register_model
     *
     * @return the value of HSDC00_05.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.register_model
     *
     * @param registerModel the value for HSDC00_05.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.indept_name
     *
     * @return the value of HSDC00_05.indept_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIndeptName() {
        return indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.indept_name
     *
     * @param indeptName the value for HSDC00_05.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptName(String indeptName) {
        this.indeptName = indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.province
     *
     * @return the value of HSDC00_05.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.province
     *
     * @param province the value for HSDC00_05.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.out_name
     *
     * @return the value of HSDC00_05.out_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOutName() {
        return outName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.out_name
     *
     * @param outName the value for HSDC00_05.out_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOutName(String outName) {
        this.outName = outName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.medical_treatment
     *
     * @return the value of HSDC00_05.medical_treatment
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMedicalTreatment() {
        return medicalTreatment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.medical_treatment
     *
     * @param medicalTreatment the value for HSDC00_05.medical_treatment
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMedicalTreatment(String medicalTreatment) {
        this.medicalTreatment = medicalTreatment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.class_code
     *
     * @return the value of HSDC00_05.class_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.class_code
     *
     * @param classCode the value for HSDC00_05.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.write_time
     *
     * @return the value of HSDC00_05.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.write_time
     *
     * @param writeTime the value for HSDC00_05.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.admission_code
     *
     * @return the value of HSDC00_05.admission_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAdmissionCode() {
        return admissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.admission_code
     *
     * @param admissionCode the value for HSDC00_05.admission_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAdmissionCode(String admissionCode) {
        this.admissionCode = admissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.county
     *
     * @return the value of HSDC00_05.county
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.county
     *
     * @param county the value for HSDC00_05.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.custodian_name
     *
     * @return the value of HSDC00_05.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.custodian_name
     *
     * @param custodianName the value for HSDC00_05.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.encounter_id
     *
     * @return the value of HSDC00_05.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.encounter_id
     *
     * @param encounterId the value for HSDC00_05.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.referral_name
     *
     * @return the value of HSDC00_05.referral_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getReferralName() {
        return referralName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.referral_name
     *
     * @param referralName the value for HSDC00_05.referral_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralName(String referralName) {
        this.referralName = referralName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.effective_time
     *
     * @return the value of HSDC00_05.effective_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.effective_time
     *
     * @param effectiveTime the value for HSDC00_05.effective_time
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_05.sex
     *
     * @return the value of HSDC00_05.sex
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_05.sex
     *
     * @param sex the value for HSDC00_05.sex
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }
}