package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.BaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName("HSDC00_02")
public class Hsdc0002 extends BaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.street_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String streetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.referral_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean referralMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.treatment_programs
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String treatmentPrograms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.identify_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String identifyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.infee_settlement
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String infeeSettlement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date writeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.health_evaluate
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String healthEvaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.service_require
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String serviceRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String registerModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String ostalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.pay_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.cm_category
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String cmCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String maritalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.visitmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String visitmiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.inspect_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inspectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.fee_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String feeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.visit_dept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String visitDeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String township;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String referralReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.measure_guide
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String measureGuide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.patient_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String patientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.visit_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date visitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.fee
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Double fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.house_number
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String houseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.medical_treatment
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String medicalTreatment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String authorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.disposal_plan
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String disposalPlan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String templateOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String telecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianTelecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.infee_settlement_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String infeeSettlementCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String encounterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.marital_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String maritalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.referral_record
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String referralRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.counseling
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String counseling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String custodianCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.pay_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String payCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.cm_category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String cmCategoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.class_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.birth
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.visitmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String visitmiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.county
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.indept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String indeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.mi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String miName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.fee_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.xds_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.sex_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String sexCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HSDC00_02.visit_dept
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String visitDept;


    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.street_name
     *
     * @param streetName the value for HSDC00_02.street_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.referral_mark
     *
     * @return the value of HSDC00_02.referral_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getReferralMark() {
        return referralMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.referral_mark
     *
     * @param referralMark the value for HSDC00_02.referral_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralMark(Boolean referralMark) {
        this.referralMark = referralMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.author_name
     *
     * @return the value of HSDC00_02.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.author_name
     *
     * @param authorName the value for HSDC00_02.author_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.treatment_programs
     *
     * @return the value of HSDC00_02.treatment_programs
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTreatmentPrograms() {
        return treatmentPrograms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.treatment_programs
     *
     * @param treatmentPrograms the value for HSDC00_02.treatment_programs
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTreatmentPrograms(String treatmentPrograms) {
        this.treatmentPrograms = treatmentPrograms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.unique_id
     *
     * @return the value of HSDC00_02.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.unique_id
     *
     * @param uniqueId the value for HSDC00_02.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.identify_no
     *
     * @return the value of HSDC00_02.identify_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIdentifyNo() {
        return identifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.identify_no
     *
     * @param identifyNo the value for HSDC00_02.identify_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIdentifyNo(String identifyNo) {
        this.identifyNo = identifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.custodian_addr
     *
     * @return the value of HSDC00_02.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianAddr() {
        return custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.custodian_addr
     *
     * @param custodianAddr the value for HSDC00_02.custodian_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianAddr(String custodianAddr) {
        this.custodianAddr = custodianAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.infee_settlement
     *
     * @return the value of HSDC00_02.infee_settlement
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInfeeSettlement() {
        return infeeSettlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.infee_settlement
     *
     * @param infeeSettlement the value for HSDC00_02.infee_settlement
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInfeeSettlement(String infeeSettlement) {
        this.infeeSettlement = infeeSettlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.domain_id
     *
     * @return the value of HSDC00_02.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.domain_id
     *
     * @param domainId the value for HSDC00_02.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.health_no
     *
     * @return the value of HSDC00_02.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthNo() {
        return healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.health_no
     *
     * @param healthNo the value for HSDC00_02.health_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthNo(String healthNo) {
        this.healthNo = healthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.write_time
     *
     * @return the value of HSDC00_02.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.write_time
     *
     * @param writeTime the value for HSDC00_02.write_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.health_evaluate
     *
     * @return the value of HSDC00_02.health_evaluate
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHealthEvaluate() {
        return healthEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.health_evaluate
     *
     * @param healthEvaluate the value for HSDC00_02.health_evaluate
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHealthEvaluate(String healthEvaluate) {
        this.healthEvaluate = healthEvaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.service_require
     *
     * @return the value of HSDC00_02.service_require
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getServiceRequire() {
        return serviceRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.service_require
     *
     * @param serviceRequire the value for HSDC00_02.service_require
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setServiceRequire(String serviceRequire) {
        this.serviceRequire = serviceRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.register_model
     *
     * @return the value of HSDC00_02.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getRegisterModel() {
        return registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.register_model
     *
     * @param registerModel the value for HSDC00_02.register_model
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setRegisterModel(String registerModel) {
        this.registerModel = registerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.ostal_code
     *
     * @return the value of HSDC00_02.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOstalCode() {
        return ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.ostal_code
     *
     * @param ostalCode the value for HSDC00_02.ostal_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOstalCode(String ostalCode) {
        this.ostalCode = ostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.custodian_name
     *
     * @return the value of HSDC00_02.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianName() {
        return custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.custodian_name
     *
     * @param custodianName the value for HSDC00_02.custodian_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianName(String custodianName) {
        this.custodianName = custodianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.pay_name
     *
     * @return the value of HSDC00_02.pay_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.pay_name
     *
     * @param payName the value for HSDC00_02.pay_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPayName(String payName) {
        this.payName = payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.empi
     *
     * @return the value of HSDC00_02.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.empi
     *
     * @param empi the value for HSDC00_02.empi
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEmpi(String empi) {
        this.empi = empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.cm_category
     *
     * @return the value of HSDC00_02.cm_category
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCmCategory() {
        return cmCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.cm_category
     *
     * @param cmCategory the value for HSDC00_02.cm_category
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCmCategory(String cmCategory) {
        this.cmCategory = cmCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.class_code
     *
     * @return the value of HSDC00_02.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.class_code
     *
     * @param classCode the value for HSDC00_02.class_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.marital_name
     *
     * @return the value of HSDC00_02.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMaritalName() {
        return maritalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.marital_name
     *
     * @param maritalName the value for HSDC00_02.marital_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMaritalName(String maritalName) {
        this.maritalName = maritalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.inmi_name
     *
     * @return the value of HSDC00_02.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiName() {
        return inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.inmi_name
     *
     * @param inmiName the value for HSDC00_02.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiName(String inmiName) {
        this.inmiName = inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.visitmi_name
     *
     * @return the value of HSDC00_02.visitmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getVisitmiName() {
        return visitmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.visitmi_name
     *
     * @param visitmiName the value for HSDC00_02.visitmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setVisitmiName(String visitmiName) {
        this.visitmiName = visitmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.inspect_type
     *
     * @return the value of HSDC00_02.inspect_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInspectType() {
        return inspectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.inspect_type
     *
     * @param inspectType the value for HSDC00_02.inspect_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInspectType(String inspectType) {
        this.inspectType = inspectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.city
     *
     * @return the value of HSDC00_02.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.city
     *
     * @param city the value for HSDC00_02.city
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.mi_addr
     *
     * @return the value of HSDC00_02.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiAddr() {
        return miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.mi_addr
     *
     * @param miAddr the value for HSDC00_02.mi_addr
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiAddr(String miAddr) {
        this.miAddr = miAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.fee_code
     *
     * @return the value of HSDC00_02.fee_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFeeCode() {
        return feeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.fee_code
     *
     * @param feeCode the value for HSDC00_02.fee_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.upload_time
     *
     * @return the value of HSDC00_02.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.upload_time
     *
     * @param uploadTime the value for HSDC00_02.upload_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.effective_time
     *
     * @return the value of HSDC00_02.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.effective_time
     *
     * @param effectiveTime the value for HSDC00_02.effective_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.sex
     *
     * @return the value of HSDC00_02.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.sex
     *
     * @param sex the value for HSDC00_02.sex
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.indept_name
     *
     * @return the value of HSDC00_02.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIndeptName() {
        return indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.indept_name
     *
     * @param indeptName the value for HSDC00_02.indept_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptName(String indeptName) {
        this.indeptName = indeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.visit_dept_code
     *
     * @return the value of HSDC00_02.visit_dept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getVisitDeptCode() {
        return visitDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.visit_dept_code
     *
     * @param visitDeptCode the value for HSDC00_02.visit_dept_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setVisitDeptCode(String visitDeptCode) {
        this.visitDeptCode = visitDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.township
     *
     * @return the value of HSDC00_02.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTownship() {
        return township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.township
     *
     * @param township the value for HSDC00_02.township
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTownship(String township) {
        this.township = township;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.referral_reason
     *
     * @return the value of HSDC00_02.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getReferralReason() {
        return referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.referral_reason
     *
     * @param referralReason the value for HSDC00_02.referral_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralReason(String referralReason) {
        this.referralReason = referralReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.mi_code
     *
     * @return the value of HSDC00_02.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiCode() {
        return miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.mi_code
     *
     * @param miCode the value for HSDC00_02.mi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiCode(String miCode) {
        this.miCode = miCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.measure_guide
     *
     * @return the value of HSDC00_02.measure_guide
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMeasureGuide() {
        return measureGuide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.measure_guide
     *
     * @param measureGuide the value for HSDC00_02.measure_guide
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMeasureGuide(String measureGuide) {
        this.measureGuide = measureGuide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.xds_type
     *
     * @return the value of HSDC00_02.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.xds_type
     *
     * @param xdsType the value for HSDC00_02.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.patient_name
     *
     * @return the value of HSDC00_02.patient_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.patient_name
     *
     * @param patientName the value for HSDC00_02.patient_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.visit_date
     *
     * @return the value of HSDC00_02.visit_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getVisitDate() {
        return visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.visit_date
     *
     * @param visitDate the value for HSDC00_02.visit_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.fee
     *
     * @return the value of HSDC00_02.fee
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Double getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.fee
     *
     * @param fee the value for HSDC00_02.fee
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFee(Double fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.house_number
     *
     * @return the value of HSDC00_02.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.house_number
     *
     * @param houseNumber the value for HSDC00_02.house_number
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.medical_treatment
     *
     * @return the value of HSDC00_02.medical_treatment
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMedicalTreatment() {
        return medicalTreatment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.medical_treatment
     *
     * @param medicalTreatment the value for HSDC00_02.medical_treatment
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMedicalTreatment(String medicalTreatment) {
        this.medicalTreatment = medicalTreatment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.author_code
     *
     * @return the value of HSDC00_02.author_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getAuthorCode() {
        return authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.author_code
     *
     * @param authorCode the value for HSDC00_02.author_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setAuthorCode(String authorCode) {
        this.authorCode = authorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.disposal_plan
     *
     * @return the value of HSDC00_02.disposal_plan
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDisposalPlan() {
        return disposalPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.disposal_plan
     *
     * @param disposalPlan the value for HSDC00_02.disposal_plan
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDisposalPlan(String disposalPlan) {
        this.disposalPlan = disposalPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.template_oid
     *
     * @return the value of HSDC00_02.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTemplateOid() {
        return templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.template_oid
     *
     * @param templateOid the value for HSDC00_02.template_oid
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTemplateOid(String templateOid) {
        this.templateOid = templateOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.telecom
     *
     * @return the value of HSDC00_02.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTelecom() {
        return telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.telecom
     *
     * @param telecom the value for HSDC00_02.telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTelecom(String telecom) {
        this.telecom = telecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.custodian_telecom
     *
     * @return the value of HSDC00_02.custodian_telecom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianTelecom() {
        return custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.custodian_telecom
     *
     * @param custodianTelecom the value for HSDC00_02.custodian_telecom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianTelecom(String custodianTelecom) {
        this.custodianTelecom = custodianTelecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.infee_settlement_code
     *
     * @return the value of HSDC00_02.infee_settlement_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInfeeSettlementCode() {
        return infeeSettlementCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.infee_settlement_code
     *
     * @param infeeSettlementCode the value for HSDC00_02.infee_settlement_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInfeeSettlementCode(String infeeSettlementCode) {
        this.infeeSettlementCode = infeeSettlementCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.encounter_id
     *
     * @return the value of HSDC00_02.encounter_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getEncounterId() {
        return encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.encounter_id
     *
     * @param encounterId the value for HSDC00_02.encounter_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setEncounterId(String encounterId) {
        this.encounterId = encounterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.xds_version
     *
     * @return the value of HSDC00_02.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.xds_version
     *
     * @param xdsVersion the value for HSDC00_02.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.marital_code
     *
     * @return the value of HSDC00_02.marital_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMaritalCode() {
        return maritalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.marital_code
     *
     * @param maritalCode the value for HSDC00_02.marital_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMaritalCode(String maritalCode) {
        this.maritalCode = maritalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.referral_record
     *
     * @return the value of HSDC00_02.referral_record
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getReferralRecord() {
        return referralRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.referral_record
     *
     * @param referralRecord the value for HSDC00_02.referral_record
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setReferralRecord(String referralRecord) {
        this.referralRecord = referralRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.counseling
     *
     * @return the value of HSDC00_02.counseling
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCounseling() {
        return counseling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.counseling
     *
     * @param counseling the value for HSDC00_02.counseling
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCounseling(String counseling) {
        this.counseling = counseling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.province
     *
     * @return the value of HSDC00_02.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.province
     *
     * @param province the value for HSDC00_02.province
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.custodian_code
     *
     * @return the value of HSDC00_02.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCustodianCode() {
        return custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.custodian_code
     *
     * @param custodianCode the value for HSDC00_02.custodian_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCustodianCode(String custodianCode) {
        this.custodianCode = custodianCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.pay_code
     *
     * @return the value of HSDC00_02.pay_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.pay_code
     *
     * @param payCode the value for HSDC00_02.pay_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.status
     *
     * @return the value of HSDC00_02.status
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.status
     *
     * @param status the value for HSDC00_02.status
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.cm_category_code
     *
     * @return the value of HSDC00_02.cm_category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCmCategoryCode() {
        return cmCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.cm_category_code
     *
     * @param cmCategoryCode the value for HSDC00_02.cm_category_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCmCategoryCode(String cmCategoryCode) {
        this.cmCategoryCode = cmCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.class_name
     *
     * @return the value of HSDC00_02.class_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.class_name
     *
     * @param className the value for HSDC00_02.class_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.birth
     *
     * @return the value of HSDC00_02.birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.birth
     *
     * @param birth the value for HSDC00_02.birth
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.inmi_code
     *
     * @return the value of HSDC00_02.inmi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiCode() {
        return inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.inmi_code
     *
     * @param inmiCode the value for HSDC00_02.inmi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiCode(String inmiCode) {
        this.inmiCode = inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.visitmi_code
     *
     * @return the value of HSDC00_02.visitmi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getVisitmiCode() {
        return visitmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.visitmi_code
     *
     * @param visitmiCode the value for HSDC00_02.visitmi_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setVisitmiCode(String visitmiCode) {
        this.visitmiCode = visitmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.county
     *
     * @return the value of HSDC00_02.county
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.county
     *
     * @param county the value for HSDC00_02.county
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.indept_code
     *
     * @return the value of HSDC00_02.indept_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getIndeptCode() {
        return indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.indept_code
     *
     * @param indeptCode the value for HSDC00_02.indept_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setIndeptCode(String indeptCode) {
        this.indeptCode = indeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.mi_name
     *
     * @return the value of HSDC00_02.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMiName() {
        return miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.mi_name
     *
     * @param miName the value for HSDC00_02.mi_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMiName(String miName) {
        this.miName = miName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.fee_type
     *
     * @return the value of HSDC00_02.fee_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.fee_type
     *
     * @param feeType the value for HSDC00_02.fee_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.pk
     *
     * @return the value of HSDC00_02.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.pk
     *
     * @param pk the value for HSDC00_02.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.xds_name
     *
     * @return the value of HSDC00_02.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsName() {
        return xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.xds_name
     *
     * @param xdsName the value for HSDC00_02.xds_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsName(String xdsName) {
        this.xdsName = xdsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.sex_code
     *
     * @return the value of HSDC00_02.sex_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSexCode() {
        return sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.sex_code
     *
     * @param sexCode the value for HSDC00_02.sex_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSexCode(String sexCode) {
        this.sexCode = sexCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HSDC00_02.visit_dept
     *
     * @return the value of HSDC00_02.visit_dept
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getVisitDept() {
        return visitDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HSDC00_02.visit_dept
     *
     * @param visitDept the value for HSDC00_02.visit_dept
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setVisitDept(String visitDept) {
        this.visitDept = visitDept;
    }
}