package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("inhosp_history_info")
public class InhospHistoryInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_history_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_history_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_history_info.in_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date inDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_history_info.in_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_history_info.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_history_info.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inmiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_history_info.medical_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String medicalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_history_info.out_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date outDate;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_history_info.pk
     *
     * @param pk the value for inhosp_history_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_history_info.domain_id
     *
     * @return the value of inhosp_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_history_info.domain_id
     *
     * @param domainId the value for inhosp_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_history_info.unique_id
     *
     * @return the value of inhosp_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_history_info.unique_id
     *
     * @param uniqueId the value for inhosp_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_history_info.xds_type
     *
     * @return the value of inhosp_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_history_info.xds_type
     *
     * @param xdsType the value for inhosp_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_history_info.xds_version
     *
     * @return the value of inhosp_history_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_history_info.xds_version
     *
     * @param xdsVersion the value for inhosp_history_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_history_info.in_date
     *
     * @return the value of inhosp_history_info.in_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_history_info.in_date
     *
     * @param inDate the value for inhosp_history_info.in_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_history_info.in_reason
     *
     * @return the value of inhosp_history_info.in_reason
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInReason() {
        return inReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_history_info.in_reason
     *
     * @param inReason the value for inhosp_history_info.in_reason
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInReason(String inReason) {
        this.inReason = inReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_history_info.inmi_code
     *
     * @return the value of inhosp_history_info.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiCode() {
        return inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_history_info.inmi_code
     *
     * @param inmiCode the value for inhosp_history_info.inmi_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiCode(String inmiCode) {
        this.inmiCode = inmiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_history_info.inmi_name
     *
     * @return the value of inhosp_history_info.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInmiName() {
        return inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_history_info.inmi_name
     *
     * @param inmiName the value for inhosp_history_info.inmi_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInmiName(String inmiName) {
        this.inmiName = inmiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_history_info.medical_no
     *
     * @return the value of inhosp_history_info.medical_no
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getMedicalNo() {
        return medicalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_history_info.medical_no
     *
     * @param medicalNo the value for inhosp_history_info.medical_no
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setMedicalNo(String medicalNo) {
        this.medicalNo = medicalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_history_info.out_date
     *
     * @return the value of inhosp_history_info.out_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getOutDate() {
        return outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_history_info.out_date
     *
     * @param outDate the value for inhosp_history_info.out_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }
}