package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("inhosp_info")
public class InhospInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_info.in_happen
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inHappen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_info.in_happen_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inHappenCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inhosp_info.lastin_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date lastinTime;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_info.pk
     *
     * @param pk the value for inhosp_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_info.domain_id
     *
     * @return the value of inhosp_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_info.domain_id
     *
     * @param domainId the value for inhosp_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_info.unique_id
     *
     * @return the value of inhosp_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_info.unique_id
     *
     * @param uniqueId the value for inhosp_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_info.xds_type
     *
     * @return the value of inhosp_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_info.xds_type
     *
     * @param xdsType the value for inhosp_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_info.xds_version
     *
     * @return the value of inhosp_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_info.xds_version
     *
     * @param xdsVersion the value for inhosp_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_info.in_happen
     *
     * @return the value of inhosp_info.in_happen
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInHappen() {
        return inHappen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_info.in_happen
     *
     * @param inHappen the value for inhosp_info.in_happen
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInHappen(String inHappen) {
        this.inHappen = inHappen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_info.in_happen_code
     *
     * @return the value of inhosp_info.in_happen_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInHappenCode() {
        return inHappenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_info.in_happen_code
     *
     * @param inHappenCode the value for inhosp_info.in_happen_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInHappenCode(String inHappenCode) {
        this.inHappenCode = inHappenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inhosp_info.lastin_time
     *
     * @return the value of inhosp_info.lastin_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getLastinTime() {
        return lastinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inhosp_info.lastin_time
     *
     * @param lastinTime the value for inhosp_info.lastin_time
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setLastinTime(Date lastinTime) {
        this.lastinTime = lastinTime;
    }
}