package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("injury_history_info")
public class InjuryHistoryInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_history_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_history_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_history_info.trauma_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date traumaDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_history_info.trauma_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean traumaMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column injury_history_info.trauma_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String traumaName;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_history_info.pk
     *
     * @param pk the value for injury_history_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_history_info.domain_id
     *
     * @return the value of injury_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_history_info.domain_id
     *
     * @param domainId the value for injury_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_history_info.unique_id
     *
     * @return the value of injury_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_history_info.unique_id
     *
     * @param uniqueId the value for injury_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_history_info.xds_type
     *
     * @return the value of injury_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_history_info.xds_type
     *
     * @param xdsType the value for injury_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_history_info.xds_version
     *
     * @return the value of injury_history_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_history_info.xds_version
     *
     * @param xdsVersion the value for injury_history_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_history_info.trauma_date
     *
     * @return the value of injury_history_info.trauma_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getTraumaDate() {
        return traumaDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_history_info.trauma_date
     *
     * @param traumaDate the value for injury_history_info.trauma_date
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTraumaDate(Date traumaDate) {
        this.traumaDate = traumaDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_history_info.trauma_mark
     *
     * @return the value of injury_history_info.trauma_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getTraumaMark() {
        return traumaMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_history_info.trauma_mark
     *
     * @param traumaMark the value for injury_history_info.trauma_mark
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTraumaMark(Boolean traumaMark) {
        this.traumaMark = traumaMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column injury_history_info.trauma_name
     *
     * @return the value of injury_history_info.trauma_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTraumaName() {
        return traumaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column injury_history_info.trauma_name
     *
     * @param traumaName the value for injury_history_info.trauma_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTraumaName(String traumaName) {
        this.traumaName = traumaName;
    }
}