package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("inoculation_info")
public class InoculationInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.company
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.company_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.inoculation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inoculationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.inoculation_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date inoculationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.inoculation_dose
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inoculationDose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.inoculation_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inoculationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.inoculation_part
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String inoculationPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.manufacturer
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.vaccine_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String vaccineCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.vaccine_lotno
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String vaccineLotno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inoculation_info.vaccine_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String vaccineName;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.pk
     *
     * @param pk the value for inoculation_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.domain_id
     *
     * @return the value of inoculation_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.domain_id
     *
     * @param domainId the value for inoculation_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.unique_id
     *
     * @return the value of inoculation_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.unique_id
     *
     * @param uniqueId the value for inoculation_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.xds_type
     *
     * @return the value of inoculation_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.xds_type
     *
     * @param xdsType the value for inoculation_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.xds_version
     *
     * @return the value of inoculation_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.xds_version
     *
     * @param xdsVersion the value for inoculation_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.company
     *
     * @return the value of inoculation_info.company
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.company
     *
     * @param company the value for inoculation_info.company
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.company_code
     *
     * @return the value of inoculation_info.company_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.company_code
     *
     * @param companyCode the value for inoculation_info.company_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.inoculation_code
     *
     * @return the value of inoculation_info.inoculation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInoculationCode() {
        return inoculationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.inoculation_code
     *
     * @param inoculationCode the value for inoculation_info.inoculation_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInoculationCode(String inoculationCode) {
        this.inoculationCode = inoculationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.inoculation_date
     *
     * @return the value of inoculation_info.inoculation_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getInoculationDate() {
        return inoculationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.inoculation_date
     *
     * @param inoculationDate the value for inoculation_info.inoculation_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInoculationDate(Date inoculationDate) {
        this.inoculationDate = inoculationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.inoculation_dose
     *
     * @return the value of inoculation_info.inoculation_dose
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInoculationDose() {
        return inoculationDose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.inoculation_dose
     *
     * @param inoculationDose the value for inoculation_info.inoculation_dose
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInoculationDose(String inoculationDose) {
        this.inoculationDose = inoculationDose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.inoculation_name
     *
     * @return the value of inoculation_info.inoculation_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInoculationName() {
        return inoculationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.inoculation_name
     *
     * @param inoculationName the value for inoculation_info.inoculation_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInoculationName(String inoculationName) {
        this.inoculationName = inoculationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.inoculation_part
     *
     * @return the value of inoculation_info.inoculation_part
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getInoculationPart() {
        return inoculationPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.inoculation_part
     *
     * @param inoculationPart the value for inoculation_info.inoculation_part
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setInoculationPart(String inoculationPart) {
        this.inoculationPart = inoculationPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.manufacturer
     *
     * @return the value of inoculation_info.manufacturer
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.manufacturer
     *
     * @param manufacturer the value for inoculation_info.manufacturer
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.vaccine_code
     *
     * @return the value of inoculation_info.vaccine_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getVaccineCode() {
        return vaccineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.vaccine_code
     *
     * @param vaccineCode the value for inoculation_info.vaccine_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setVaccineCode(String vaccineCode) {
        this.vaccineCode = vaccineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.vaccine_lotno
     *
     * @return the value of inoculation_info.vaccine_lotno
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getVaccineLotno() {
        return vaccineLotno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.vaccine_lotno
     *
     * @param vaccineLotno the value for inoculation_info.vaccine_lotno
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setVaccineLotno(String vaccineLotno) {
        this.vaccineLotno = vaccineLotno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inoculation_info.vaccine_name
     *
     * @return the value of inoculation_info.vaccine_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getVaccineName() {
        return vaccineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inoculation_info.vaccine_name
     *
     * @param vaccineName the value for inoculation_info.vaccine_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setVaccineName(String vaccineName) {
        this.vaccineName = vaccineName;
    }
}