package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
@TableName("oper_history_info")
public class OperHistoryInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_history_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_history_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_history_info.oper_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_history_info.oper_history
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String operHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_history_info.oper_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean operMark;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_history_info.pk
     *
     * @param pk the value for oper_history_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_history_info.domain_id
     *
     * @return the value of oper_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_history_info.domain_id
     *
     * @param domainId the value for oper_history_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_history_info.unique_id
     *
     * @return the value of oper_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_history_info.unique_id
     *
     * @param uniqueId the value for oper_history_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_history_info.xds_type
     *
     * @return the value of oper_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_history_info.xds_type
     *
     * @param xdsType the value for oper_history_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_history_info.xds_version
     *
     * @return the value of oper_history_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_history_info.xds_version
     *
     * @param xdsVersion the value for oper_history_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_history_info.oper_date
     *
     * @return the value of oper_history_info.oper_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_history_info.oper_date
     *
     * @param operDate the value for oper_history_info.oper_date
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_history_info.oper_history
     *
     * @return the value of oper_history_info.oper_history
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getOperHistory() {
        return operHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_history_info.oper_history
     *
     * @param operHistory the value for oper_history_info.oper_history
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOperHistory(String operHistory) {
        this.operHistory = operHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_history_info.oper_mark
     *
     * @return the value of oper_history_info.oper_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getOperMark() {
        return operMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_history_info.oper_mark
     *
     * @param operMark the value for oper_history_info.oper_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setOperMark(Boolean operMark) {
        this.operMark = operMark;
    }
}