package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;

@Data
@TableName("physique_classify_info")
public class PhysiqueClassifyInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physique_classify_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physique_classify_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physique_classify_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physique_classify_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physique_classify_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physique_classify_info.constitution_category_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String constitutionCategoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column physique_classify_info.constitution_category
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String constitutionCategory;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physique_classify_info.pk
     *
     * @param pk the value for physique_classify_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physique_classify_info.domain_id
     *
     * @return the value of physique_classify_info.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physique_classify_info.domain_id
     *
     * @param domainId the value for physique_classify_info.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physique_classify_info.unique_id
     *
     * @return the value of physique_classify_info.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physique_classify_info.unique_id
     *
     * @param uniqueId the value for physique_classify_info.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physique_classify_info.xds_type
     *
     * @return the value of physique_classify_info.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physique_classify_info.xds_type
     *
     * @param xdsType the value for physique_classify_info.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physique_classify_info.xds_version
     *
     * @return the value of physique_classify_info.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physique_classify_info.xds_version
     *
     * @param xdsVersion the value for physique_classify_info.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physique_classify_info.constitution_category_code
     *
     * @return the value of physique_classify_info.constitution_category_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getConstitutionCategoryCode() {
        return constitutionCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physique_classify_info.constitution_category_code
     *
     * @param constitutionCategoryCode the value for physique_classify_info.constitution_category_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setConstitutionCategoryCode(String constitutionCategoryCode) {
        this.constitutionCategoryCode = constitutionCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column physique_classify_info.constitution_category
     *
     * @return the value of physique_classify_info.constitution_category
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getConstitutionCategory() {
        return constitutionCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column physique_classify_info.constitution_category
     *
     * @param constitutionCategory the value for physique_classify_info.constitution_category
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setConstitutionCategory(String constitutionCategory) {
        this.constitutionCategory = constitutionCategory;
    }
}