package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;
@Data
@TableName("profession_expose_info")
public class ProfessionExposeInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.career_duration
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String careerDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.dangerous_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String dangerousName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.dangerous_occupation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String dangerousOccupation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.exposed_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean exposedMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.protection_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Boolean protectionMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession_expose_info.type_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String typeName;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.pk
     *
     * @param pk the value for profession_expose_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession_expose_info.domain_id
     *
     * @return the value of profession_expose_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.domain_id
     *
     * @param domainId the value for profession_expose_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession_expose_info.unique_id
     *
     * @return the value of profession_expose_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.unique_id
     *
     * @param uniqueId the value for profession_expose_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession_expose_info.xds_type
     *
     * @return the value of profession_expose_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.xds_type
     *
     * @param xdsType the value for profession_expose_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession_expose_info.xds_version
     *
     * @return the value of profession_expose_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.xds_version
     *
     * @param xdsVersion the value for profession_expose_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession_expose_info.career_duration
     *
     * @return the value of profession_expose_info.career_duration
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getCareerDuration() {
        return careerDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.career_duration
     *
     * @param careerDuration the value for profession_expose_info.career_duration
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setCareerDuration(String careerDuration) {
        this.careerDuration = careerDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession_expose_info.dangerous_name
     *
     * @return the value of profession_expose_info.dangerous_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDangerousName() {
        return dangerousName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.dangerous_name
     *
     * @param dangerousName the value for profession_expose_info.dangerous_name
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDangerousName(String dangerousName) {
        this.dangerousName = dangerousName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession_expose_info.dangerous_occupation
     *
     * @return the value of profession_expose_info.dangerous_occupation
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDangerousOccupation() {
        return dangerousOccupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.dangerous_occupation
     *
     * @param dangerousOccupation the value for profession_expose_info.dangerous_occupation
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDangerousOccupation(String dangerousOccupation) {
        this.dangerousOccupation = dangerousOccupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession_expose_info.exposed_mark
     *
     * @return the value of profession_expose_info.exposed_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getExposedMark() {
        return exposedMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.exposed_mark
     *
     * @param exposedMark the value for profession_expose_info.exposed_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setExposedMark(Boolean exposedMark) {
        this.exposedMark = exposedMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession_expose_info.protection_mark
     *
     * @return the value of profession_expose_info.protection_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public Boolean getProtectionMark() {
        return protectionMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.protection_mark
     *
     * @param protectionMark the value for profession_expose_info.protection_mark
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setProtectionMark(Boolean protectionMark) {
        this.protectionMark = protectionMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession_expose_info.type_code
     *
     * @return the value of profession_expose_info.type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.type_code
     *
     * @param typeCode the value for profession_expose_info.type_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession_expose_info.type_name
     *
     * @return the value of profession_expose_info.type_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession_expose_info.type_name
     *
     * @param typeName the value for profession_expose_info.type_name
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}