package com.ylz.hf.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import com.ylz.common.bean.SubBaseBean;
import lombok.Data;

import java.io.Serializable;

@Data
@TableName("spirit_info")
public class SpiritInfo extends SubBaseBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spirit_info.pk
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private Integer pk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spirit_info.domain_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spirit_info.unique_id
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spirit_info.xds_type
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spirit_info.xds_version
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String xdsVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spirit_info.spirit_code
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String spiritCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spirit_info.spirit_symptom
     *
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    private String spiritSymptom;


    public Integer getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spirit_info.pk
     *
     * @param pk the value for spirit_info.pk
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spirit_info.domain_id
     *
     * @return the value of spirit_info.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spirit_info.domain_id
     *
     * @param domainId the value for spirit_info.domain_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spirit_info.unique_id
     *
     * @return the value of spirit_info.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spirit_info.unique_id
     *
     * @param uniqueId the value for spirit_info.unique_id
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spirit_info.xds_type
     *
     * @return the value of spirit_info.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsType() {
        return xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spirit_info.xds_type
     *
     * @param xdsType the value for spirit_info.xds_type
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsType(String xdsType) {
        this.xdsType = xdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spirit_info.xds_version
     *
     * @return the value of spirit_info.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getXdsVersion() {
        return xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spirit_info.xds_version
     *
     * @param xdsVersion the value for spirit_info.xds_version
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setXdsVersion(String xdsVersion) {
        this.xdsVersion = xdsVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spirit_info.spirit_code
     *
     * @return the value of spirit_info.spirit_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSpiritCode() {
        return spiritCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spirit_info.spirit_code
     *
     * @param spiritCode the value for spirit_info.spirit_code
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSpiritCode(String spiritCode) {
        this.spiritCode = spiritCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spirit_info.spirit_symptom
     *
     * @return the value of spirit_info.spirit_symptom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public String getSpiritSymptom() {
        return spiritSymptom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spirit_info.spirit_symptom
     *
     * @param spiritSymptom the value for spirit_info.spirit_symptom
     * @mbggenerated Fri Apr 24 19:51:42 CST 2020
     */
    public void setSpiritSymptom(String spiritSymptom) {
        this.spiritSymptom = spiritSymptom;
    }
}