package com.ylz.hf.show.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;

@Data
@TableName("bs_info")
public class BsInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_info.start_time
     *
     * @mbggenerated Thu Apr 30 17:52:02 CST 2020
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_info.global_id
     *
     * @mbggenerated Thu Apr 30 17:52:02 CST 2020
     */
    private String globalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_info.bs_value
     *
     * @mbggenerated Thu Apr 30 17:52:02 CST 2020
     */
    private String bsValue;


    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_info.start_time
     *
     * @param startTime the value for bs_info.start_time
     * @mbggenerated Thu Apr 30 17:52:02 CST 2020
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_info.global_id
     *
     * @return the value of bs_info.global_id
     * @mbggenerated Thu Apr 30 17:52:02 CST 2020
     */
    public String getGlobalId() {
        return globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_info.global_id
     *
     * @param globalId the value for bs_info.global_id
     * @mbggenerated Thu Apr 30 17:52:02 CST 2020
     */
    public void setGlobalId(String globalId) {
        this.globalId = globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_info.bs_value
     *
     * @return the value of bs_info.bs_value
     * @mbggenerated Thu Apr 30 17:52:02 CST 2020
     */
    public String getBsValue() {
        return bsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_info.bs_value
     *
     * @param bsValue the value for bs_info.bs_value
     * @mbggenerated Thu Apr 30 17:52:02 CST 2020
     */
    public void setBsValue(String bsValue) {
        this.bsValue = bsValue;
    }
}