package com.ylz.hf.show.bean;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;

@Data
@TableName("height_info")
public class HeightInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column height_info.start_time
     *
     * @mbggenerated Thu Apr 30 17:52:03 CST 2020
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column height_info.global_id
     *
     * @mbggenerated Thu Apr 30 17:52:03 CST 2020
     */
    private String globalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column height_info.height
     *
     * @mbggenerated Thu Apr 30 17:52:03 CST 2020
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column height_info.unit
     *
     * @mbggenerated Thu Apr 30 17:52:03 CST 2020
     */
    private String unit;


    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column height_info.start_time
     *
     * @param startTime the value for height_info.start_time
     * @mbggenerated Thu Apr 30 17:52:03 CST 2020
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column height_info.global_id
     *
     * @return the value of height_info.global_id
     * @mbggenerated Thu Apr 30 17:52:03 CST 2020
     */
    public String getGlobalId() {
        return globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column height_info.global_id
     *
     * @param globalId the value for height_info.global_id
     * @mbggenerated Thu Apr 30 17:52:03 CST 2020
     */
    public void setGlobalId(String globalId) {
        this.globalId = globalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column height_info.height
     *
     * @return the value of height_info.height
     * @mbggenerated Thu Apr 30 17:52:03 CST 2020
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column height_info.height
     *
     * @param height the value for height_info.height
     * @mbggenerated Thu Apr 30 17:52:03 CST 2020
     */
    public void setHeight(String height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column height_info.unit
     *
     * @return the value of height_info.unit
     * @mbggenerated Thu Apr 30 17:52:03 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column height_info.unit
     *
     * @param unit the value for height_info.unit
     * @mbggenerated Thu Apr 30 17:52:03 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }
}